### ISSUE TITLE
packages for LAMMPS stable release 22 Aug 2018

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#1073]
For myself to track progress:

- [x] OpenSuse https://build.opensuse.org/request/show/631123
- [x] Fedora 30 (Rawhide): https://koji.fedoraproject.org/koji/taskinfo?taskID=29237816
- [x] Fedora 29: https://koji.fedoraproject.org/koji/taskinfo?taskID=29237861
- [x] Fedora 28: https://bodhi.fedoraproject.org/updates/FEDORA-2018-994d80bf41
- [x] Fedora 27: https://bodhi.fedoraproject.org/updates/FEDORA-2018-a8d5415e03
- [x] CentOS 7: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2018-99b748f6f4
- [x] Gentoo (found #1079): https://github.com/gentoo/gentoo/commit/b16e2bf244f7dca3c69b3462ed859ed258f27b84
- [x] Spack: https://github.com/spack/spack/pull/9081
- [ ] Debian package

**Comment by junghans** [comment]
@gladk, could you please add the last stable release to debian as well?

**Comment by gladk** [comment]
Sure, it will be done together with the switch to cmake.

**Comment by junghans** [comment]
All done, but Debian! @gladk close issue whenever are done.

**Comment by gladk** [comment]
Done for Ubuntus ([trough PPA](https://launchpad.net/~gladky-anton/+archive/ubuntu/lammps)) also. Supported versions: 16.04 (i386 failed, needs to be investigated), 18.04 and upcoming 18.10.

Also daily version is available (/usr/bin/lmp_daily) which is built from master-branch. And stable version (/usr/bin/lmp_stable), which is built from the stable branch. Both of them are co-installable.

I am not able to close this issue (maybe because I am not a member of this team).
