### ISSUE TITLE
Mark old issue / pull requests stale

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#1087]
We could use stale bot to mark old issue and pull requests stale.

Instructions here:
https://github.com/probot/stale

**Comment by junghans** [comment]
I remember the last time we have many open issues, you went through all of them manually, so the bot could act like a first filter.

**Comment by akohlmey** [comment]
Filter how? The bot doesn't know what I know about certain issues and since
they are sorted by age and open projects already flagged with 'volunteer
needed' I don't see any added value, only added bother. Besides at < 100
open issues, there is not effort required to browse through them.

Axel



--
Dr. Axel Kohlmeyer  akohlmey@gmail.com  http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste. Italy.

**Comment by junghans** [comment]
Then keep browsing!
