### ISSUE TITLE
Fix efield with region option

### ISSUE THREAD

**Issue by Inoel5** [lammps/lammps#1176]
When using fix efield with region option for water, total energy does not conserve.
However, when applying fixe field with no region option to water, total energy  conserves.
That is because region option adds force to atoms within the area. 

So, I want to add option in fix efield applying force to molecules in the case where a part of molecule is included in the region.

**Comment by giacomofiorin** [comment]
Is energy conservation your goal?  Even if you applied the electric field only to the centers of mass of the molecules (as opposed to individual atoms) there would be discontinuities in the energy when the molecules' centers of mass cross the region boundaries, similarly to when atoms do.

Perhaps what you are looking for is a continuous switch-on of the electric field inside the region, so that work done by/against the electric field forces at the boundaries of the region are properly accounted for in changes in the kinetic energy.

**Comment by akohlmey** [comment]
@Inoel5 there has been no reaction to the comment by @giacomofiorin are you still working on this? or have decided to go a different route? should this issue remain open for further comments? or can it be closed? please let us know. thanks.

**Comment by akohlmey** [comment]
closed due to inactivity
