### ISSUE TITLE
implement generic logger class to replace "logfile" and "screen"

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#120]
we should have a logger class with semantics similar to C++ iostreams, which would make logging simpler and less programming effort, as all choices whether output should be sent to "screen" or "logfile" would be delegated to the logger. using iostream semantics would allow to get rid of temporary fixed size buffers. VMD uses something similar. it would be nice to also have an option to choose verbosity, i.e. assign "urgency" levels, so that output would be either very terse or more verbose.
the error class already serves some of the same purposes, but primarily suffers from requiring a char \* argument. perhaps those can be combined. using a little preprocessor trickery, it may be possible to also hide the FLERR macro.

**Comment by ExpHP** [comment]
My lousy 2 cents:

I'm not sure precisely what kind of design you have in mind, but I hope it is not the iostream API itself! This is one of the most awkwardly designed parts of C++, and I think it would bring a great loss of clarity to the code base to see it replace the existing C formatting routines.

And I'm not just talking about the verbose and ugly syntax. Treating formatting flags as printable values was a terrible idea, and the iostream API has many gotchas:

* Some flags like `setprecision` are sticky, which can lead to unintended side-effects.
* Some other flags like `setw` are automatically reset under a seemingly arbitrary selection of cases.
* Just weird inconsistencies everywhere.  E.g. you can't print 8-bit integers because `unsigned char` and `signed char` are for some reason formatted like `char` (despite all three being recognized as independent types in the language)

Having something closer to the C API would not only make migration easier, but I honestly believe it would lead to less bugs in the end.  The main troubles with this approach though are:

* I doubt that a function with a signature like `template<class... Args> void function(const char *format, Args... args)` could be type-checked or linted with a static analyzer in the same manner that `printf` and friends are. (a macro might work, but... ick)
* Be it a macro or template, it will be tricky to avoid code bloat.

**Comment by akohlmey** [comment]
this issue is (mostly) obsolete now due to using fmtlib and having `utils::logmesg()`
