### ISSUE TITLE
Using encapsulated pointers instead of raw pointers

### ISSUE THREAD

**Issue by DiscreteLogarithm** [lammps/lammps#1200]
## Summary

Raw pointers need to be explicitly deleted and also to be initialized to null when default constructed, while encapsulated pointers automatically deallocate the memory (if not null) in their destructor and their default constructors initialize the pointer to null.

## Type of Issue

Suggestion for an Enhancement

## Detailed Description

The encapsulated pointer object itself is allocated on the stack and therefore its destructor is automatically called when it goes out of scope. This eliminates any chance for a memory leak and easily fixes issues like #1109 (memory leak in fix bocs).

A great candidate for this is the STL's `unique_ptr` (or we could implement a class with a similar interface):
- its default constructor initializes the pointer to null
- its destructor checks whether the pointer in null before calling the deleter
- it provides dereference `*` (for single object), dereference member `->` (for single object), subscript `[]` (for array) and bool conversion operators, so it could be used almost like a raw pointer
- has a `get` method to get the raw pointer
- has a `release` method which releases ownership of the pointer
- has a `reset` method which checks and deallocates the memory first before assigning the new content
- can have custom deleter, so the C-style `free` function could be used
- has very low overhead (does not perform reference counting since it has exclusive ownership semantics)

In many places in LAMMPS there's an `allocated` flag which is set after allocation and checked in destructor before deallocation. Also in many places there's a manual C++ reallocation where a pointer is `delete`d if not null and then allocated with a new size. So with this change a lot of repeating codes are also eliminated.

`unique_ptr` was introduced in C++11 so there's two solutions to preserve C++98 compatibility:
- implement a simplified version of the `unique_ptr` without move semantics and using one of the two based on `__cplusplus` macro
- implement a simplified version of the `unique_ptr` without move semantics and use it for all C++ standards

Move semantics are not needed in our case, since pointers are created and destroyed within the same class/function and other classes could still use the `get` method to access the pointer.

If this idea and these solutions are acceptable, I volunteer to implement them and to fix issue #1109.

There's no need to change all of LAMMPS at once and this could be implemented gradually (one class at a time).

**Comment by Pakketeretet2** [comment]
I don't know if unique_ptrs are appropriate for all of the pointers used but for a lot of cases they would be a sensible default.

**Comment by akohlmey** [comment]
A few general comments:
- i think reviewing memory management in LAMMPS is a good idea. different parts of the code do different things and having a mix of `malloc()` based and `new / delete` based allocations is often not a good idea. it would be great to have a single mechanism to be used everywhere.
- if effort is invested into changing the memory management infrastructure, it should also be compatible with memory alignment requirements for vectorization. Those go beyond what malloc/new do.
- whether to do this specific change would be up to @sjplimp. he has the final word on this.
- anything using c++-11 or c++-14 code, is currently not acceptable for the base LAMMPS code. it can only be done in specific packages like KOKKOS. so a suitable template class would have to be added
- nothing is more convincing like an example. since the memory leaks in fix bocs were mentioned, how about providing a pull request, that converts and fixes up that one particular class with the proposed new memory management strategy
- since changing such a basic part of the code base and thus potentially affects many LAMMPS developers *and* contributors, it might be a good idea to submit a more detailed proposal (with examples) to be presented at the next LAMMPS Users workshop (tentatively planned for 
Summer 2019 in Albuquerque) in the developer session

**Comment by DiscreteLogarithm** [comment]
Thanks. I'll send a pull request in a few days. It will be compatible with the memory alignment requirements because only the way pointers are stored will be altered not the way they're allocated.

**Comment by akohlmey** [comment]
@DiscreteLogarithm your last comment was over 3 weeks ago. Can you give us an update of what your progress is, if any?

**Comment by DiscreteLogarithm** [comment]
@akohlmey I'm so sorry. I was busy with my thesis defence and forgot about this. I have created a pull request.

**Comment by akohlmey** [comment]
please see my comment for PR #1250
