### ISSUE TITLE
several minor issues

### ISSUE THREAD

**Issue by dfedosov** [lammps/lammps#1205]
## Summary

Several minor issues/inconsistencies I've noticed while updating our LAMMPS version. It is likely that they will nearly never appear. 

## Type of Issue

Bug Report

## LAMMPS Version (Bug Report)

9 Nov 2018

## Description (Bug Report)

1) MOLECULE/atom_vec_molecular.cpp: in functions unpack_exchange(...) and unpack_restart(...) a number of variables (e.g. bond_atom, angle_atom*, dihedral_atom*, improper_atom*, special) are unpacked as int, while they should be tagint.

2) read_data.cpp: line 1438: shouldn't 'for (int i = 0; i < nlocal; i++)' be 'for (int i = nlocal_previous; i < nlocal; i++)' here?

3) write_restart.cpp: near lines 535-536: there was a property 'EXTRA_SPECIAL_PER_ATOM' added, while a line of something like 'write_int(EXTRA_SPECIAL_PER_ATOM,force->special_extra);' is missing. So, it is not written into restarts, but it can be read in read_restart.cpp (line 927).

**Comment by akohlmey** [comment]
Thanks for your report and careful observations.

> 1. MOLECULE/atom_vec_molecular.cpp: in functions unpack_exchange(...) and unpack_restart(...) a number of variables (e.g. bond_atom, angle_atom*, dihedral_atom*, improper_atom*, special) are unpacked as int, while they should be tagint.

Correct. This will be addressed in an upcoming pull request.

> 2. read_data.cpp: line 1438: shouldn't 'for (int i = 0; i < nlocal; i++)' be 'for (int i = nlocal_previous; i < nlocal; i++)' here?

Correct. This will be addressed in an upcoming pull request.

> 3. write_restart.cpp: near lines 535-536: there was a property 'EXTRA_SPECIAL_PER_ATOM' added, while a line of something like 'write_int(EXTRA_SPECIAL_PER_ATOM,force->special_extra);' is missing. So, it is not written into restarts, but it can be read in read_restart.cpp (line 927).

That is intentional. Using EXTRA_SPECIAL_PER_ATOM for restarts was incorrect and worked only in some cases. This was replaced by saving ATOM_MAXSPECIAL, which works always. The entry in the enum and the ability to read (but not write) was left in the code for backward compatibility with restart files that have this entry. I will added a comment to read_restart with a note explaining this.
