### ISSUE TITLE
[Feature Request] "soft" version of lj/class2 pair potentials

### ISSUE THREAD

**Issue by evoyiatzis** [lammps/lammps#1269]
## Summary

A "soft" version of the lj/class2 potentials (similar to the lj/cut/soft potential) would allow for free energy calculations using class 2 potentials such as PCFF and COMPASS. Following the spirit of Beutler in Chem Phys Lett, 222, 529 (1994), the potential could read:

V(r) = (lamda^n) epsilon (2 * denominator ^(-1.5) - 3 *denominator^(-1))

where denominator = alpha_{LJ} *(1 - lamda)^2 + (r/sigma)^6.

## Type of Issue

'Suggestion for an Enhancement'

## Detailed Description (Enhancement Suggestion)

The pair_style would be very similar to the pair_style lj/cut/soft with only the exponent of the repulsive term modified. A first attempt for such "soft" versions of lj/class2 and lj/class2/coul/cut (with names lj/class2/soft and lj/class2/coul/cut/soft) is included in the attached zip file. I am willing to participate in the implementation of this pair_style.

## Further Information, Files, and Links

[class_2_smooth.zip](https://github.com/lammps/lammps/files/2717295/class_2_smooth.zip)

**Comment by akohlmey** [comment]
@agiliopadua is the author of the `USER_FEP` package and thus the best person to collaborate with.

**Comment by evoyiatzis** [comment]
Thanks for the suggestion @akohlmey. I will contact him directly.

**Comment by Pakketeretet2** [comment]
Just a note on terminology, LAMMPS uses "soft" for these types of
potentials, while "smooth" refers to potentials that go smoothly to 0 at
the cut-off. That's why everything in USER-FEP is called */soft.

**Comment by evoyiatzis** [comment]
Thanks for the note. I have updated the text accordingly.

**Comment by agiliopadua** [comment]
@evoyiatzis just a few points concerning the implementation.
Have you tested your pair_lj_class2_soft* by running simple examples, e.g.:
- 2 atoms at a series of distances,
- a liquid of class2 atoms with lambda=1 comparing with (not soft) pair_lj_class2,
- a simple FEP calculation
It would be useful to have a pair style with coul_long.

**Comment by evoyiatzis** [comment]
In the attached file, I have included a lj_class2_coul_long_soft pair_style and I have updated primarily the formatting of the other two styles.

[class_2_soft.tar.gz](https://github.com/lammps/lammps/files/2724754/class_2_soft.tar.gz)

For testing purposes, I  evaluated configurations of a polyamide-6 system with these three styles using lamda = 1, n = 1, alpha_LJ = 0 and alpha_C = 0 (i.e. no soft) and compared with the original class2 pair_styles. The energies I got agree up to numerical precision. A short nve run (50 timesteps) gave almost identical results.

I used the pair_write command to get the pair potentials as a function of distance and compared them with values I calculated using an excel spreadsheet. There was a very good agreement. (maybe this is a test of only the single() method and not the compute() ).

For the case of lj_class2_soft (i.e. without electrostatics) I wrote the forces & distances from the compute() method during the evaluation of few polyamide condifurations to a dump file. I compared them with the expected values from the pair_write command and there is also good agreement.

I have not done any FEP calculation yet.

**Comment by evoyiatzis** [comment]
@akohlmey I will prepare an example (insertion of short polymer in methane) similar to the existing example of CH4 hydration. Should I submit it as part of the class2 package, of the user-fep or user-misc?

**Comment by agiliopadua** [comment]
Yes, I also think it makes sense to include it in USER-FEP. We have to decide where the doc will go: with the pair styles lj/soft or with pair style class2 (as is the case with morse/soft). @evoyiatzis I cloned your fork. so I can test and contribute but I can't see the files in your branch: soft_class2_potentials

**Comment by akohlmey** [comment]
I suggest to use this opportunity to change to a consistent pattern. I think it would be best to consolidate all /soft potential docs into a single file or a few files (lj, coul, class2, morse) and in the case of the single file perhaps rename the file from `pair_lj_soft.txt` to `pair_fep_soft.txt`. But then there should be a mutual links (e.g. on `pair_morse.txt`, that there is a `/soft` version in `USER-FEP` and documented in `pair_fep_soft.html`, and on `pair_fep_soft.txt`, that the base morse potential (for lambda=1) is documented in `pair_morse.html`) and correspondingly for the other pair styles.
This way the (hypothetical) `pair_fep_soft.txt` docs can focus on the *differences* from the regular versions. This way only on the `/soft` documentation a reference to installation of `USER-FEP` is required. Equivalently, if there are multiple `pair_XXX_soft.txt`. My personal preference at the moment would be to have a single file for all `/soft` styles, but i leave it to you guys to make a judgement call, since it may look overloaded when everything is added.

**Comment by agiliopadua** [comment]
Makes sense. I will work on consolidating the doc.

**Comment by evoyiatzis** [comment]
@agiliopadua  please check the soft_class2_potentials branch. I have included the source files and made a small addition to the Install.sh file.
