### ISSUE TITLE
[BUG] _Global variable in USER-REAXC can cause segfaults_

### ISSUE THREAD

**Issue by ellio167** [lammps/lammps#1432]
**Summary**

The LR variable defined in reaxc_lookup.cpp (line 32) is global and can cause problems if multiple pair_reaxc objects are created.

**Comments**

The LR variable should be made local to the pair_reaxc object or a new class should be defined that could contain the LR variable and have all of the reax functions as member variables.  This would involve a good deal of changes/additions/adjustments to the code, but I'm not thinking of a better approach.  Suggestions would be welcome.  I can likely implement a solution if we agree on the approach.

**Comment by mkanski** [comment]
The bug is more severe, because even if there are no segfaults, the results are wrong, since the tabulated long range interactions are taken from the last potential file. However, the fix is not complicated. `LR` is used only in three functions and all of them use the `reax_system` structure, so all you need to do is to move `LR` there.
There is also a second problem - reax/c relies on a fix to communicate some variables (see snippet below). If two reax/c instances share some atoms, their forces and energies will be wrong. 
https://github.com/lammps/lammps/blob/898860328b45aa938547490af4261f5d80386f31/src/USER-REAXC/pair_reaxc.cpp#L413-L417

**Comment by ellio167** [comment]
@mkanski  Thanks for the comment.  Indeed, you are right that the results will be incorrect!  Your suggested fix for the LR variable is nice.  I would be happy to go with this approach.

For your second problem, I'm trying to understand what is going on.  It looks to me that each instance of pair_reaxc will create its own copy of fix_reaxc using the add_fix() function.  Or, does the add_fix() routine ensure that there is only one copy of each unique fix?

**Comment by akohlmey** [comment]
@ellio167 since the fix label is hardcoded into pair reax/c, Modify::add_fix() will replace the previous fix instance with a new one in the same place. see the comments in modify.cpp.
This is obviously not the desired behavior. to ensure, that each instance of pair reax/c has access to a unique fix reax, the fix label has to be made unique (and stored). This could be done by appending the string value of Pair::instance_me to the REAXC label.
