### ISSUE TITLE
[Feature Request] implement atom-style variables for fix adapt diameter

### ISSUE THREAD

**Issue by jibril-b-coulibaly** [lammps/lammps#1508]
Dear developers,

Would it be possible to enable the use atom-style variables for the 'diameter' attribute of the 'fix adapt' command ? The same way 'fix setforce' accepts atom-style variable for example ? The present 'fix adapt' command only supports equal-style variables: all particles have the same diameter and it is not possible to adapt diameter for polydisperse granular systems.

This would be a very helpful feature as the only way to modify the diameter of polydisperse particles is currently to use 'set diameter' periodically in a loop or in a 'run xx every yy' which can become hefty when a smooth evolution of diameter is needed.

Thank you very much for your consideration.

**Comment by agiliopadua** [comment]
Hi,
The fix adapt/fep variant accepts per-atom variables such as diameter or charge specified by atom type.
You can install it with the USER-FEP package.
Agilio Padua

**Comment by jibril-b-coulibaly** [comment]
Hi,
I tried fix adapt/fep with an atom-style variable and get the error:
ERROR: Variable for fix adapt/fep is invalid style (C:\lammps\src\USER-FEP\fix_adapt_fep.cpp:307)
From the documentation it seems that fix adapt/fep can be applied on a per-type basis using equal-style variables. In granular simulations however all particles have the same type and diameter is assigned on a per-atom basis which fix adapt/fep cannot deal with.
Jibril

**Comment by akohlmey** [comment]
@jibril-b-coulibaly please note, that a similar situation would exist for charges, which are per-atom properties and independent from atom types. However, fix adapt can be applied to them, because the corresponding pair styles have been modified to include a 2-d array `scale`, that contains a scaling factor for charge-charge interactions that defaults to 1.0 and can be set on a per-type basis. Please note, that while (most) granular pair styles do not use atom types, you can still assign them and use them for partitioning (e.g. to apply the radius scaling to a subgroup of atoms). The (new) generalized granular pair style (called `granular`) does use types, though and per-type settings. So rather than changing fix adapt, it would be more consistent with the rest of LAMMPS to change the granular pair styles to support a `scale` property, that can be made accessible to fix adapt through an "extract()" function. You can look at pair style `coul/cut` as an example.

**Comment by jibril-b-coulibaly** [comment]
@akohlmey Thank you for the information and suggestions, I will look into the `scale` property for the `granular` style. I have one reservation remaining in regards of systems with many different diameters.

My goal is to proportionally and continuously expand the diameter of polydisperse particles over time. Say I want to double the diameter, particles of diameter 0.8 and 1.0 at the beginning of the run would respectively have their diameter ramp up to 1.6 and 2.0 at the end of the run.

If I understand you correctly, partitioning would mean having a discrete set of diameter values, like 0.8 and 1.0 in my previous example, each assigned to a type. I am working with systems having a continuous distribution of diameters, hence that approach would require to assign a different type for each diameter (i.e. nearly each particle) which becomes unpractical. That case of continuous diameter distribution was my initial motivation in using an atom-style variable in the fix/adapt command. 

Jibril

**Comment by akohlmey** [comment]
> If I understand you correctly, partitioning would mean having a discrete set of diameter values, like 0.8 and 1.0 in my previous example, each assigned to a type. I am working with systems having a continuous distribution of diameters, hence that approach would require to assign a different type for each diameter (i.e. nearly each particle) which becomes unpractical. That case of continuous diameter distribution was my initial motivation in using an atom-style variable in the fix/adapt command.

no, you are misunderstanding me. as you have stated, all granular pair styles (with the exception of the recent addition `granular`) are ignorant toward atom types. So you can use the atom type property to identify groups of particles (similar as sometimes the molecule id is used). That could be used, if you want to scale the diameter of only a subset of particles, but those could have polydisperse diameters each. the atom type would only determine for which pairs of particles the scaling factor is modified by fix adapt.

 
> Jibril

**Comment by jibril-b-coulibaly** [comment]
Thank you for the precision. I was mistaken with the notion of partition as I wish to adapt diameter for all particles.

- In my case I suspect I should define a `scale` array for the pair style `granular` and modify it using `fix/adapt pair granular scale v_myvalue` ?

- My initial understanding was that I would have to use multiple `fix/adapt/dep atom type diameter v_myvalue` for each `type` assigned to each diameter

I looked into the `coul_cut` pair_style and the `scale` parameter is applied for energy and force calculation of pairs within the cutoff distance. For `granular` pair style, the diameter affects contact detection and calculation of overlap, relative velocities etc. Were you thinking of scaling the radius before performing all these tasks ? Something looking like:
`radi = radius[i]*scale[itype][jtype]` 
`radj = radius[j]*scale[itype][jtype]` 
and go on with the rest of the calculation ?

That could work for the interaction but other properties like mass would be left unchanged. If I want the diameter change to be effective not only for force calculation but for these other associated properties, would the use of a `scale` work ? I suspect the value of diameter, e.g. accessed by fixes, would also remain unscaled as seen from other commands. In that regard, it would seem more consistent to me to have a way to hard-code a diameter change the way `fix/adapt atom  diameter` does it.

Jibril

**Comment by akohlmey** [comment]
sorry, i am not an expert on granular media simulations and i have spent as much time on this as i am able to spare. LAMMPS is acquiring features because people who need them, implement them. sometimes this takes some additional figuring out and learning (and programming). if we had all the answers and knew exactly how to do things, we would have done (much of) it already.

**Comment by jibril-b-coulibaly** [comment]
I will start working on this enhancement
