### ISSUE TITLE
[BUG] Possible bug in comm_brick calling grow_send

### ISSUE THREAD

**Issue by valleymouth** [lammps/lammps#1528]
**Summary**

In the following lines of code:
https://github.com/lammps/lammps/blob/bb11344424a468254c320e3cfa0cf263a1005630/src/comm_brick.cpp#L610-L614
grow_send is called if there is any change in bufextra. If there happens to be frequent change in maxexchange_fix, which happens when FixNeighHistory is instantiated and the number of neighbours is constantly increasing, it triggers grow_send that will multiply maxsend with BUFFACTOR. That might lead to an unintended overflow of maxsend integer variable. Just as a reference CommTiled takes a different approach and just calls memory->grow:
https://github.com/lammps/lammps/blob/bb11344424a468254c320e3cfa0cf263a1005630/src/comm_tiled.cpp#L654-L655

**LAMMPS Version and Platform**

Master branch, independent of platform.

**Expected Behavior**

The variable maxsend shouldn't be modified in this case. We either need to modify grow_send to account for cases where bufextra is increased, or just call memory->grow directly as in CommTiled.

**Actual Behavior**

The function grow_send is called and maxsend is increased.

**Steps to Reproduce**

This is really hard to reproduce. It was only spotted because our application have a lot of instatiation of atoms which triggers a constant change in the numbers of partners in FixNeighHistory and a constant modification of maxexchange_fix in CommBrick. I am unable to provide a simulation case with the present modules. I hope that the problem become obvious by a quick code review.

**Further Information, Files, and Links**

No further information.

**Comment by Adrian-Diaz** [comment]
The objective of that segment is just to grow the buffer for the calls to pack exchange. Its essentially a safety size that comes after the delimiter imposed by maxsend. As a result it should always be larger than the largest pack occurring for one atom/particle (hence the use of max_exchange in case the default value of BUFEXTRA 1000 was not enough for a particle type with many extended properties being stored). In Summary, it should work just fine the way it is in tiled.cpp using memory->grow directly without causing geometric memory growth due to the bufextra_old check.

**Comment by valleymouth** [comment]
@Adrian-Diaz Ok, based on what you said I will issue a pull-request changing the call to grow_send to a direct call to memory->grow in CommBrick.
