### ISSUE TITLE
[BUG]  Multiple crossing of periodic boundary

### ISSUE THREAD

**Issue by bugsbunnyyyyy** [lammps/lammps#1577]
Hello everyone,

I made a very simple simulation (fix NVE) with a CO2 molecule in the middle of a box with boundary "p p p". Each atom of the molecule is given the same velocity in one specific direction (let say along Z). The simulation goes on very smoothly, the molecule cross the periodic boundary one time (I can check it by dumping the xu yu and zu coordinates). The problem comes when this molecule crosses the periodic boundary for the second time, the molecule explodes at the exact moment one atom crosses the boundary. Are multiple crossing not supported in LAMMPS? I find it strange... Is there any problem in my input script?

LAMMPS (16 Feb 2016)
Linux machine 

#################################################
input file:
units              metal 
atom_style         full
atom_modify        sort 1 1.0
boundary           p p p

read_data          CO2.data

bond_style         harmonic 
bond_coeff         1 48.3716974 1.161

angle_style        class2
angle_coeff        1 180.0 2.397722532 0.0 0.0
angle_coeff        1 bb 8.11396214 1.161 1.161
angle_coeff        1 ba 0.0 0.0 1.161 1.161

thermo_style       custom step ebond eangle emol ke etotal
thermo_modify      format float %.12f
thermo             10
dump               1 all custom 10 admol.posvel id x y z vx vy vz xu yu zu
dump_modify        1 sort id append yes

fix                1 all nve
timestep           0.0005

run                20000

################################################
CO2.data:
CO2 MOLECULE

3 atoms
2 bonds
1 angles

2 atom types
1 bond types
1 angle types

0.000000 100.000000 xlo xhi 
0.000000 100.000000 ylo yhi
0.000000 100.000000 zlo zhi

Masses

1 12.01070
2 15.99940

Atoms

1 1 1 0.6645 63.130173 59.008433 73.153475
2 1 2 -0.33225 63.349992 57.885916 72.926641
3 1 2 -0.33225 62.903269 60.126593 73.393580

Bonds

1 1 1 2
2 1 1 3

Angles

1 1 2 1 3

Velocities

1 20.939790 0.000000 0.000000
2 20.939790 0.000000 0.000000
3 20.939790 0.000000 0.000000

**Comment by akohlmey** [comment]
confirmed with the current development version of LAMMPS. no idea what is causing this. seems to be independent of bond/angle style and direction of the center of mass motion.
@sjplimp anything that catches your eye?

**Comment by evoyiatzis** [comment]
The equilibrium angle of the CO2 molecule is 180.0 which can cause some
numerical difficulties
Maybe using fix shake to constrain the geometry would fix this problem


Στις Δευ, 22 Ιουλ 2019 στις 2:44 μ.μ., ο/η Axel Kohlmeyer <
notifications@github.com> έγραψε:

**Comment by akohlmey** [comment]
> The equilibrium angle of the CO2 molecule is 180.0 which can cause some numerical difficulties Maybe using fix shake to constrain the geometry would fix this problem 

no, and no. angle styles have provisions against the discontinuity at angles around 180 degrees and fix shake cannot be applied to atoms on a straight line for exactly that discontinuity. the same issue also happens, with setting the angle style to zero and only allowing bond forces, which have no problem with a discontinuity at 180 degrees.

**Comment by bugsbunnyyyyy** [comment]
I made more simulations in order to understand this issue but I realize the more I am digging in the less it makes sense at all...
* First I tried this exact same simulation just by changing the velocity of each atom. It always crash when the molecule meets the periodic boundary, but not always the same!!!
=> For a velocity (on each atom in the x-direction) of 5, 10 or 50A.ps-1 it crashes when the molecule meets the 1st periodic boundary.
=> For a velocity (on each atom in the x-direction) of 20.939790A.ps-1 it crashes when the molecule meets the 2nd periodic boundary.
It does not make sense... It is not a matter of simulation time, it is not a matter of distance.... There is no logic here.

* Secondly I tried to add a pair style to the simulation with random coefficients and now it never crashes (whatever is the velocity I apply to each atom)... If someone could explain me what is going on I would be very glad. I am just starting my PhD and I want to use an opensource software to perform MD simulations but looking to these results I am wondering if I should rely on this program. Did anyone experience such results also?
Hereby is the new input file:
#################################################
input file:
units metal
atom_style full
atom_modify sort 1 1.0
boundary p p p

read_data CO2.data

bond_style harmonic
bond_coeff 1 48.3716974 1.161

angle_style class2
angle_coeff 1 180.0 2.397722532 0.0 0.0
angle_coeff 1 bb 8.11396214 1.161 1.161
angle_coeff 1 ba 0.0 0.0 1.161 1.161

pair_style lj/cut/coul/cut 20.0
pair_coeff 1 1 1.0 5.0
pair_coeff 1 2 2.0 10.0
pair_coeff 2 2 3.0 5.0

thermo_style custom step ebond eangle emol ke etotal
thermo_modify format float %.12f
thermo 10
dump 1 all custom 10 admol.posvel id x y z vx vy vz xu yu zu
dump_modify 1 sort id append yes

fix 1 all nve
timestep 0.0005

run 20000

**Comment by ndtrung81** [comment]
Hi,

your test with adding a pair style is actually helpful. Now if you add the following line to the original input script,

comm_modify cutoff 2.0

where 2.0 is just some value comparable to the equilibrium bond length (1.61 in this case), I think the simulation would run normally.

@akohlmey and @sjplimp : The issue seems to arise when there is no pair style defined, cutghost[0], cutghost[1] and cutghost[2] in the Comm class are all 0, and cutghostuser is not set (hence also 0). Above is simply a workaround from the input script level, and I suppose there are more than one places (and ways) to resolve it. The abrupted changes in the image flag of the bonded atoms may be a consequence of this use case.

Hope it helps,
-Trung

**Comment by akohlmey** [comment]
> @akohlmey and @sjplimp : The issue seems to arise when there is no pair style defined, cutghost[0], cutghost[1] and cutghost[2] in the Comm class are all 0, and cutghostuser is not set (hence also 0). Above is simply a workaround from the input script level, and I suppose there are more than one places (and ways) to resolve it. The abrupted changes in the image flag of the bonded atoms may be a consequence of this use case.
> 
> Hope it helps,
> -Trung

@ndtrung81 thanks.
i am a bit surprised that it is possible to run without a pair style. i recall that there was a test guarding against it, which is why we have pair style zero, which does not request a neighbor list and has no compute, but does set a pairwise cutoff and have a similar - if not better - effect than setting the communication cutoff. a safe choice for the cutoff would be to go for 3x the bond length, to allow for all 4 atoms in a straight line included (since there is also the skin cutoff) and thus cover bond, angles, dihedrals, and impropers. in fact, adding the two lines:
```
pair_style zero 4.0
pair_coeff * *
```
is working nicely to avoid the unexpected jumps.

**Comment by akohlmey** [comment]
@sjplimp do you remember removing the test for running without a pair style, and if yes why?
what is the best way to proceed in your opinion?
we could probably also (or only?) add a test (and print a warning), if the pairwise cutoff is shorter than 3x the equilibrium bond length (in case a bond style is defined) and then provide a recommendation to define pair style zero with a suitable cutoff.

**Comment by sjplimp** [comment]
@akohlmey It should be allowed to run w/out a pair style.  E.g. some models only have bonds (angles, etc).  E.g. a harmonic crystal.  That said, I don't remember removing any checks.  I will look at the example script.

**Comment by sjplimp** [comment]
As @ndtrung81 indicated, the problem is there is no pair style and no comm_modify cufoff set (default = 0.0), so there are no ghost atoms.  If reneighboring occurs when a bond straddles the boundary, then it will "find" the bond partner on the other side of the box (not the ghost atom), the bond will
be very long, and bad dynamics results.  If you run this on 8 procs, you get a "lost atom" error b/c the proc does not find the other bond atom.

I think the solution is to print a warning when the user has no pair style to be sure and set comm_modify cutoff.  Or it could just be issued when there is no pair style and comm_modify cutoff = 0.0.

Steve

**Comment by akohlmey** [comment]
@sjplimp i think we can do better. If there *is* a bond style, we can use some heuristic based on the equilibrium bond length (say 1.5x for bonds only, 2.5x for angles and bonds, 3.5x for others) as default for the communication cutoff. If we take the maximum of this and the maximum pairwise cutoff, we also guard against the case of short cutoff pair styles (e.g. repulsive only) and long bonds (e.g. in certain coarse grain models). I've added PR #1581 with those changes **and** a warning in case the communication cutoff is 0.0 (which now requires no bonds and no pair style).
