### ISSUE TITLE
[BUG] No rigid body rotation for rigid/nve styles

### ISSUE THREAD

**Issue by jibril-b-coulibaly** [lammps/lammps#1657]
**Summary**

The `fix rigid/nve` styles do not perform rotation of granular rigid bodies

**LAMMPS Version and Platform**

07 Aug 2019, Windows

**Expected Behavior**

The orientation of the non-spherical rigid bodies should be altered when getting in contact with one other

**Actual Behavior**

The rigid bodies only undergo translations when using `fix rigid/nve` styles. Rotations are obtained when using `fix rigid` style.

**Steps to Reproduce**

- run input file `in.norot_issue` and visualize dump : no rotation observed using `fix rigid/nve`
- the same simulation with different dimensions of the system/rigid bodies (`in.rot_noissue`) has the expected behavior with rotations for all `fix rigid` commands

**Further Information, Files, and Links**

[in.norot_issue.txt](https://github.com/lammps/lammps/files/3571657/in.norot_issue.txt)
[in.rot_noissue.txt](https://github.com/lammps/lammps/files/3571658/in.rot_noissue.txt)
[clump.mol.txt](https://github.com/lammps/lammps/files/3571680/clump.mol.txt)

**Comment by akohlmey** [comment]
This is less of a bug in the code but an omission in the documentation. There is no support for extended particles of all kinds in `fix rigid/nve` and all similar styles. There should be an update to the documentation and a for better information of users a check added and some warnings printed in the rigid styles that don't support extended particles.

**Comment by jibril-b-coulibaly** [comment]
Thank you very much for the clarification. Rotations are observed when running the `in.rot_noissue` script which makes uses of `atom_style sphere` and `fix rigid/nve`, is that just a lucky case ?

**Comment by akohlmey** [comment]
> Thank you very much for the clarification. Rotations are observed when running the `in.rot_noissue` script which makes uses of `atom_style sphere` and `fix rigid/nve`, is that just a lucky case ?

the situation is more complex than i thought. when i made my comment, i overlooked that the FixRigidNH* classes make calls into the corresponding FixRigid* classes, so support for handling extended particles is actually present, but it is not clear whether this is handled consistently and thus i need to take a closer look. One thing that needs to be done is to consolidate the various constants and enumerators that must be kept consistent across the multiple styles or classes into a single namespace and header file.

**Comment by akohlmey** [comment]
after closer inspection, i cannot confirm that there is a difference between fix rigid and fix rigid/nve beyond the numerical differences. i get identical trajectories that start diverging eventually. one major difference between the issue and noissue input is the different choice of units, but using the same molecule file. because of that, the length unit is very different and thus the moments of inertia are quite different in both cases since the diameter parameter is taken to be the same.

**Comment by jibril-b-coulibaly** [comment]
Thank you very much for closely inspecting the code for `fix rigid` and `fix rigid/nve`.

Regarding the inertia, I do not think this should occur since the "issue" input scales down the molecule size: `molecule mol_poly_clump clump.mol scale 0.0004` which should scale down the inertia as well.

Do you also obtain identical trajectories when running the "issue" input using `fix rigid` instead of `rigid/nve` ?

**Comment by akohlmey** [comment]
> Thank you very much for closely inspecting the code for `fix rigid` and `fix rigid/nve`.
> 
> Regarding the inertia, I do not think this should occur since the "issue" input scales down the molecule size: `molecule mol_poly_clump clump.mol scale 0.0004` which should scale down the inertia as well.
> 
> Do you also obtain identical trajectories when running the "issue" input using `fix rigid` instead of `rigid/nve` ?

just re-checked with clean inputs. the trajectories start out identical and then gradually diverge for using fix rigid, rigid/small, rigid/nve, rigid/nve/small

i've modified the inputs to print out some more thermo info. too. 
the difference between the rot and norot variants has to be due to some units related setting. there is probably more that needs to be adjusted than the scaling factor for the molecule files.

i am tempted to close this issue, since i cannot see a convincing argument that something is amiss here.




[comparing-inputs.zip](https://github.com/lammps/lammps/files/3664113/comparing-inputs.zip)

**Comment by sjplimp** [comment]
I looked at these inputs and outputs and I don't understand the physical
problem.  The issue vs noissue scripts are orders of magnitude different
in length and timescales.  In particular the "issue" script has a tiny
neighbor skin and a humongous shear rate in the deformation. 
Thus I'm not convinced that for the "issue" ones that
you have formulated a numerically correct model.  Please post 2 scripts
that differ only in their use of fix rigid versus fix rigid/nve and that have
as small a number of particles as possible and run for as few timesteps
as possible.  I saw difference in the dump output for the "issue" case
after 100 time steps in the omega.  So why do these need to run for 10K steps?

**Comment by sjplimp** [comment]
Also note that in the current LAMMPS you need to put your
pair granular commands before the fix deform commands.

Also, do whatever problems you are seeing go away if
you do not use fix deform?

Steve

**Comment by jibril-b-coulibaly** [comment]
Thank you for taking the time to continue investigating. The "no_issue" and "issue" input are indeed dramatically apart in terms of physical setup. I initially included both for demonstration purposes but we could narrow the focus on the "issue" ones to illustrate the problem. For the `norot_issue` scripts, changing only `fix rigid` to `fix rigid/nve` results in distinct behavior.

To better illustrate the issue, I herein enclose a few VMD movies of the different simulations (10000 steps):
- `norot_issue.avi`: trajectory of the `in.norot_issue` input file (`dump.co_norot.lammpstrj`) using `fix rigid/nve`. This shows rigid molecules undergoing only translation
- `norot_issue_mod.avi`: trajectory of the `in.norot_issue_mod` input file (`dump.co_norot_mod.lammpstrj`) using `fix rigid` (this is the only difference with the preceding input). This shows rigid molecules undergoing both translation and rotation as expected.

I ran these scripts with 15 Apr 2020 and no issue related to defining `fix deform` before `pair_style granular` occurred.

As suggested, I also tested similar input scripts by deleting the `fix deform` and creating an initial velocity and obtained similar results (enclosed):
- `norot_issue_nodeform.avi`: trajectory of the `in.norot_issue_nodeform` input file (`dump.co_norot_nodeform.lammpstrj`) using `fix rigid/nve`. This shows rigid molecules given only translational velocity by the `velocity` command and undergoing only translation upon impact with other molecules
- `norot_issue_mod_nodeform.avi`: trajectory of the `in.norot_issue_mod_nodeform` input file (`dump.co_norot_mod_nodeform.lammpstrj`) using `fix rigid` (this is the only difference with the preceding input). This shows rigid molecules given both translational and rotational velocity by the `velocity` command and undergoing changes in direction and orientation upon impact with other molecules.
[norot_movies_nodeform.zip](https://github.com/lammps/lammps/files/4652029/norot_movies_nodeform.zip)

**Comment by sjplimp** [comment]
thanks for these inputs and movies - this helps me understand what I'm looking for.  I'll take a further look.

**Comment by sjplimp** [comment]
@jibril-b-coulibaly Here is something I'm still confused by.  As Axel said, the 2 input scripts for the no-deformation case run identically for about 100 steps, then slowly diverge, if you look at various output values. But if I look at your 2 movies for these scripts, they seem different instantly.  Part of it may be due to looking at different portions of the box in the 2 movies?  But in the one with rotation (fix rigid) one of the bodies is spinning from time 0.  If that is not happening in the fix rigid/nve case (it doesn't appear to be), that means time 0 velocities for all the particles would be different.  But I added velocities to the dump files, and they are identical up until step 100.  So this seems inconsistent with what the movies show?

**Comment by sjplimp** [comment]
Also, you might tell me that the 2nd frame in the movie is after 1000 steps (I think),
so that is later than 100 steps.  However between the first frame (step 0) and the
second frame (step 1000), none of the bodies appear to have collided yet, so they
are just spinning freely, due to their original angular momentum of the body.  Again,
this is the no-deformation fix rigid case.  But if I dump atom velocities out every
10 steps up to step 100, the velocities are identical for fix rigid vs fix rigid/nve.  That
doesn't make sense to me.
