### ISSUE TITLE
[Feature Request]  Improve OOM error message

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#1712]
**Summary**

The following type of error can be confusing for users because it doesn't specifically mention "out of memory" and the number of bytes is negative.

`
ERROR on proc 4: Failed to reallocate -12624743936 bytes for array bond/react:constraints (../memory.cpp:99)
`

**Detailed Description**

Can we make this more verbose and remove the negative number, something like:

`ERROR on proc 4: Out of memory: Tried to reallocate too many bytes for array bond/react:constraints (../memory.cpp:99)`

**Comment by akohlmey** [comment]
I am not sure that this kind of change is really helping that much. I suspect in many cases, the cause of the wraparound is not that actually that much memory is requested, but either the number is computed from an uninitialized variable (which on Linux boxes often, but not always, will contain 0 due to the way malloc() is implemented, and thus it will not always show), or from doing 32-bit integer operations where 64-bit would be required (typically for large systems). In both cases, it would be sufficient to stop with an even more generic "memory allocation failure" message, but then it should print the line of the source, where this allocation actually is being called from. rather then applying the FLERR macro in place and pointing to the line in memory.cpp. the string for the array that is passed along is not that helpful. This is another case of LAMMPS showing its age by using what was considered best practice at times when when serious programs would be written in fortran. I've seen the same kind of thing in several fortran based MD codes (for classical and ab initio MD).
