### ISSUE TITLE
[Feature Request]  Adding GPU support to pair style meam/c potential

### ISSUE THREAD

**Issue by arpitem** [lammps/lammps#1773]
Summary:

Request for adding GPU support to pair style meam/c potential.

Detailed Description:

The package gpu command currently doesn’t have support for switching on Newton’s 3rd law. My understanding is that, due to the unavailability of newton on, the pair styles which require newton pair on (like pair style meam/c) do not have GPU support. I want to accelerate some large scale simulations which I am running using MEAM potential. This enhancement will help in decreasing the time required for very large simulations and in increasing the usage of hardware available at HPCs. Is the implementation of “newton pair on” in the package gpu and eventually GPU support for pair style meam planned for the future? 

Thank you,

**Comment by akohlmey** [comment]
@arpiitr you understanding is incorrect. The reason why the GPU package does not support "newton pair on" because it is using full neighbor lists since those are faster despite requiring twice the force evaluations, as there is no need for atomic operations or locks to avoid race conditions, which limit parallel efficiency significantly.
The reason that there is no GPU version of pair styles like meam/c is because it is a complex potential that is not easy to translate to GPU code. I am not aware of any plans to write a GPU version of MEAM, be it in the GPU package, be it in the KOKKOS package. I am attaching a "volunteer needed" label to this feature request.

**Comment by arpitem** [comment]
Thanks for the clarification.
I read in the documentation that the GPU package does not support "newton pair on" because "more computation is done, but less communication" but I was not sure about the reason for not having GPU support for pair style meam/c. I hope someone who knows GPU programming finds this enough interesting to work upon it.

**Comment by stanmoore1** [comment]
We are working on a Kokkos version of MEAM now.
