### ISSUE TITLE
Question about building LAMMPS with all user packages - including USER-ADIOS

### ISSUE THREAD

**Issue by pnorbert** [lammps/lammps#1780]
**Summary**

@andraslibal is trying to build LAMMPS with all user packages. Since USER-ADIOS is included in the list of packages (in cmake/presets/all_on.cmake) and he has no care about the ADIOS2 software, the cmake configuration breaks at the point where it is looking for ADIOS2.

What is the expected behavior of configuring packages when building all_on? Should a package just be turned off when its configuration fails, or should the configuration stop with error as it is happening when ADIOS2 is not found? If the former case is preferred, can you point me to an example how you deal with errors in the configuration process?

He reported the issue on ADIOS2 github repo:  [#1081](https://github.com/ornladios/ADIOS2/pull/1081)

**LAMMPS Version and Platform**
This I don't know but it is present in the stable branch.

**Comment by akohlmey** [comment]
What you see is the expected behavior. When you turn all packages on, you have to make certain that all prerequisites are available and suitably configured. This applies to the conventional build and the cmake based build. If you want to exclude specific packages, you can load the preset and then disable specific packages that are not desired. I would recommend against using the "all on" preset, but instead use the "most" preset, which is limited to packages that should build automatically, or have the ability to download and configure/compile prerequisites as part of the build process. This can, of course, be augmented by additionally enabling or disabling packages. The "most" preset skips over some large packages that are rarely used, but would compile cleanly in most configurations (like USER-ATC).

**Comment by akohlmey** [comment]
haven't seen any followup on this here or in the ADIOS2 repo for a week. i assume the problem has been solved and will thus close this here now.
