### ISSUE TITLE
[BUG] SRP Documentation Equation Error

### ISSUE THREAD

**Issue by tabedzki** [lammps/lammps#1919]
**Summary**

The SRP Documentation has a `Misplaced &` in the first equation on the lammps documentation website.

**LAMMPS Version and Platform**
March 3 2020

**Expected Behavior**

Display equation.

**Actual Behavior**

Displays error message (`Misplaced &`).

**Steps to Reproduce**
Visit https://lammps.sandia.gov/doc/pair_srp.html

**Further Information, Files, and Links**
I tried looking into the documentation source code to see if it was fixed recently but I can't compile the documentation included in LAMMPS. I don't know if this has something to do with the documentation rewrite or not. 

Screenshot from the website
![image](https://user-images.githubusercontent.com/35670232/76022735-b717a500-5ef5-11ea-9950-2b595ff13851.png)

**Comment by akohlmey** [comment]
thanks for reporting, this will be fixed in the next LAMMPS patch

**Comment by akohlmey** [comment]
BTW: there is another issue in the example where it has `\*` instead of `*`. Given the amount of changes that both @rbberger and me applied to the documentation to embed all math expressions, there are likely more of these little issues. There are about 500 equations and about 2000 math symbols that were embedded into the manual. That said, we also fixed issues that had gone unnoticed for many months, so in the end it should more than even out.
Instructions for building the manual and the necessary prerequisite software are in the manual itself.
