### ISSUE TITLE
[BUG] Skin distance dependence of DPD thermostat

### ISSUE THREAD

**Issue by janmees** [lammps/lammps#1925]
**Summary**

When using the dpd/tstat pair style (thermostat), pressure measurement (thermo pressure tensor) seems to be dependent on the neighbour list skin distance. To my knowledge, there is nothing in the documentation that could explain this behaviour (I'm using the same number of cores).  

**LAMMPS Version and Platform**
5 Jun 2019, Also tested on August 2019 and January 2020

**Steps to Reproduce**
I have attached a minimal working example. If you run it twice with the same skin distance, you get identical results (expected). However, if you change the skin distance (for example, from "neighbor  0.4 bin" to "neighbor   1.0 bin"), the results also change (unexpected). The test also includes the possibility to switch to the LJ potential. This gives back reproducible results, regardless of skin distance. 

[dpd_test.txt](https://github.com/lammps/lammps/files/4311399/dpd_test.txt)

**Comment by akohlmey** [comment]
This is not unexpected behavior. Since the pair style will modify forces with a (velocity dependent) random term, everything that will cause a difference in the sequence of random numbers will cause changes. Changing the neighbor list skin has thus a similar effect as using a different number of MPI ranks as both change the order of atoms in the neighbor list and thus the random numbers used for the per-atom thermostat will be different for each run.

**Comment by janmees** [comment]
Ah I see, thank you for the quick response!
