### ISSUE TITLE
[BUG] Out of range atoms - cannot compute PPPM with triclinic box and user-intel

### ISSUE THREAD

**Issue by wapisani** [lammps/lammps#1935]
**Summary**
There seems to be a bug with pppm/intel and triclinic boxes. Attached is a tar.gz file containing two files, a simple input deck (PEEK0313PCFFTrS0.in) that reproduces the error and the data file (PEEK0313PCFFEq2S0.dat) the input script reads in.

The script reads in an orthogonal data file containing 5 PEEK molecules for a total of 170 atoms. The system has been equilibrated for 200 ps after a 20 Angstrom/ns densification to the bulk density of PEEK 1.30 g/cc.

The simulation is run with the command line arguments "-pk intel 0 omp 2 -sf intel". After the read_data command, the simulation is run for 0 time steps and then the box is changed to a triclinic box (with 0 tilt) and the atoms remapped. The simulation is run again for 0 time steps. The purpose of this is to compare the energies between orthogonal and triclinic with zero tilts. The error occurs at the second run command before the 0 time step thermo is printed. The error is "Out of range atoms - cannot compute PPPM (../pppm_intel.cpp:405)".  

**LAMMPS Version and Platform**
3 Mar 2020, Linux Mint 19.3 (Ubuntu 18.04)

**Expected Behavior**
The energies before and after the change from orthogonal to triclinic should be the same. Also, out of range atoms - cannot compute PPPM errors should not occur when running with user-intel.

**Actual Behavior**
Out of range atoms - cannot compute PPPM errors when running with "-pk intel 0 omp 2 -sf intel". Running the simulation without the Intel package command line arguments does not give any errors. However, the thermo values at each run command (orthogonal vs triclinic) are different. Below are the differences (second run minus first run values):

diff in Step: 0.0
diff in v_Time: 0.0
diff in Temp: 0.0
diff in Press: 0.029999999998835847
diff in TotEng: 0.0006000000000767614
diff in KinEng: 0.0
diff in PotEng: 0.0007000000000516593
diff in E_pair: 0.0007000000000516593
diff in E_bond: 0.0
diff in E_angle: 0.0
diff in E_dihed: 0.0
diff in E_impro: 0.0
diff in E_long: -0.9972000000000065
diff in Lx: 0.0
diff in Ly: 0.0
diff in Lz: 0.0
diff in Density: 0.0

**Steps to Reproduce**
Run PEEK0313PCFFTrS0.in with "-pk intel 0 omp 2 -sf intel" with a LAMMPS binary built with user-intel to observe out of range atoms error. Run PEEK0313PCFFTrS0.in without "-pk intel 0 omp 2 -sf intel" to observe the energy difference.

[triclinic_pppm_user_intel.tar.gz](https://github.com/lammps/lammps/files/4330869/triclinic_pppm_user_intel.tar.gz)

**Comment by akohlmey** [comment]
@wapisani thanks for submitting this. I have looked into it and figured out what happens. The USER-INTEL package translates coordinates and some other per-atom properties into special buffers, so it can do single precision and vector operations on them. However, that will result in problems with triclinic cell processing. When doing grid related operations, first all coordinates are translated to fractional coordinates, so they are orthogonal again and most of the existing code for orthogonal boxes can be used (just some factors and offsets need to be computed differently). That is why you get the out-of-range error, since the non-fractional coordinates are indeed *waaay* outside the (fractional) cell. There is currently no easy way to work around this. I have a few ideas that would restore the original code from pppm.cpp in case of a triclinic cell, but it is more likely that we need to flag pppm/intel for now as incompatible with triclinic cells and we would need to create a feature request to implement it.

**Comment by akohlmey** [comment]
Commit 924629538f556b7b009dd2af11e0b95c960732d2 should recover triclinic support for pppm/intel, but calling the corresponding functions from plain pppm that do not use the coordinate buffers while coordinates are converted to fractional coordinates.

**Comment by wapisani** [comment]
@akohlmey Thanks for the fix! It's working great! I'm getting through about eight times the number of time steps with the fix in four hours on 88 cores (across two nodes) than when running without user-intel with the same time frame and core/node count.
