### ISSUE TITLE
[Feature Request] new pair style

### ISSUE THREAD

**Issue by stanos4** [lammps/lammps#1942]
**Summary**

implementing new pair style but wrong energy is returned

**Detailed Description**

Dear all,

Not a feature request per se but a developer help request. I'm trying to write a new pair and angular styles. The "dirty" version is already in my fork, but I've got a problem with energies. When I do geometry optimization (using quickmin), I see that energy is rising instead of decreasing. I don't know where this come from, because when I print out numbers I pass to *ev_tally* and just sum them, then I get decreasing energy for each GO step. Any help is highly appreciated.

source: https://github.com/stanos4/lammps
branch: stable_7Aug2019-angle_vfm
(*angle_vfm* and *pair_repcubic* should be the only changes with respect to the corresponding lammps:stable_7Aug2019)

I use older stable version for the development - this is purely for laziness reasons as my deployment machine is offline and the source available there is of that version;
The code is not cleaned up, it contains many print statements to track down issues on the way, but hopefully is well readable.

Attached are input files to run a simple geometry optimization of a simple system.
note: running any of the "cg/sd/hftn" results in "wrong" final geometry.

Thank you a lot!

[lammps.txt](https://github.com/lammps/lammps/files/4334545/lammps.txt)
[par.txt](https://github.com/lammps/lammps/files/4334546/par.txt)

**Comment by akohlmey** [comment]
@stanos4 the LAMMPS developers have no time to debug your own code.
I have some general comments. You can set up a system with just 2 or three atoms and then change the distance for one of them with fix move and thus get energy vs. distance curves that you can compare to your potential function. From that you could also verify the forces from finite differences. What you describes could happen, if your forces are applied with the wrong sign.

In general, please do not (ab-)use a feature request issue template if you don't want to request a new feature. There are other templates available, including one for generic requests that do not fit into the existing templates. However, in this case the better approach would be to send an e-mail to the lammps-users mailing list to get some feedback from other people having implemented pair styles of their own and perhaps can tell you where the problem was. It is highly unlikely that this is an issue of LAMMPS itself, but most likely of your implementation.
