### ISSUE TITLE
[Feature Request] add an example on how to use lammps library to read trajectories

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#1976]
**Summary**

Please we add an example to how to use liblammps to read / write trajectory. 

**Detailed Description**

This feature would be use for external package to read / write lammps trajectories.

**Further Information, Files, and Links**

We currently have an reversed engineered data reader https://github.com/votca/csg/blob/master/src/libcsg/modules/io/lammpsdatareader.cc
but using liblammps would be better.

/cc @JoshuaSBrown

**Comment by akohlmey** [comment]
LAMMPS doesn't really have a clean interface so that trajectory data can be exported for other programs to use it. All you could do is to fake a simulation with a given number of atoms, no pair style, no integrator and then create a dump style of your choice and then use `lammps_scatter_atoms()` to update the data. Similarly, you would set up a reader with the  `read_dump` command and then use `lammps_gater_atoms()` to retrieve the data.

The major problem with LAMMPS is that its design if from ground up optimized for distributed data parallel processing and that conflicts with a dedicated reader/writer API, which is by design serial.
You can see the downside of that in the dump styles for dcd, xtc, molfile and so on.

A more specific read/write support is in the LAMMPS molfile plugin for VMD https://www.ks.uiuc.edu/Research/vmd/plugins/molfile/lammpsplugin.html
This is, however, limited by the restrictions of the molfile API itself. But ultimately, this is essentially also a reverse engineered solution (but supported and adding a molfile interface would provide read/write support for many file formats. cf USER-MOLFILE).

**Comment by junghans** [comment]
Hence this is a feature request, as you are in the process of redesigning the API, it would be nice to have some way to parse lammps dump and data files. Writing is secondary for now.

**Comment by akohlmey** [comment]
> Hence this is a feature request, as you are in the process of redesigning the API, it would be nice to have some way to parse lammps dump and data files. Writing is secondary for now.

sorry, but there must be some miscommunication. where does it say (or where did I say) that the API (and which API?) is being redesigned?

**Comment by junghans** [comment]
Redesign might have been a too strong word, I was reading https://github.com/lammps/lammps/pull/1956#discussion_r399612987 and (mostly) hoping I/O could be one of the header that will get exported in the API.

**Comment by akohlmey** [comment]
> Redesign might have been a too strong word, I was reading [#1956 (comment)](https://github.com/lammps/lammps/pull/1956#discussion_r399612987) and (mostly) hoping I/O could be one of the header that will get exported in the API.

ok. I see where this is going now. This is not going to be easy for the general case, and rather hackish. You need to create a LAMMPS instance with compatible settings (which usually you cannot know unless you already know what is in the file). The molfile library does this protocol: (1) open file -> number of atoms, (2) read structure -> number of types, residues, charges and other constant per-atom info, (3) read next frame (get coordinates, plus velocities and other metadata, if available). (4) repeat until end. Thus molfile will read the first frame twice. When reading through LAMMPS you need the information from (2) to be able to do (1), so that is going to be very difficult to make it work.

**Comment by akohlmey** [comment]
...and on top of that, reading data files in a standalone way is even more complex and often problematic, since the format is not self-descriptive. There are some conventions to place comments in the right places to provide additional information, but they are not required by LAMMPS and it will only warn, if there are inconsistencies.  Reading a data file requires to have a LAMMPS simulation system set up *exactly* as the data file requires. So there is no simple way to expose this as an I/O library, but you have to do a similar thing as mentioned before, set up a system, issue a read_data command and then extract the information you want from the LAMMPS instance with the corresponding lammps_gather_atoms() call.

**Comment by akohlmey** [comment]
Nobody seems interested or thinks it is worth doing.

**Comment by junghans** [comment]
Correction: nobody except the VOTCA team ;-)

**Comment by akohlmey** [comment]
> Correction: nobody except the VOTCA team ;-)

i meant interest among the LAMMPS developers.

But let me repeat that this suggestion is based on a misunderstanding of the format and the requirements to read it.
The whole suggestion is ill-conceived. It seems to be based on the assumption that there is a single piece of code somewhere that does the reading of data files, which is not the case. Data files in LAMMPS can only be read with additional information not contained in the file and thus you *must* set up a new system from inside LAMMPS to read it with compatible settings. for that you need to create a LAMMPS instance, and use read_data which does communication and all kinds of other "LAMMPS things". this doesn't need any code changes.
