### ISSUE TITLE
[BUG] Build with Win4MPI fails on Windows

### ISSUE THREAD

**Issue by jibril-b-coulibaly** [lammps/lammps#2028]
**Summary**

I am building LAMMPS with MPI on Windows 10 using minGW as follows:

`cmake -C ../cmake/presets/most.cmake -C ../cmake/presets/nolib.cmake  -D BUILD_MPI=yes -D LAMMPS_MACHINE=mpi -D CMAKE_INSTALL_PREFIX=.. ../cmake -G "MinGW Makefiles"`

When I run `make`, the compilation fails when trying to link to lmp_mpi.exe with a slew of  MPI related errors such as:
`liblammps_mpi.a(fix_viscosity.cpp.obj): In function 'LAMMPS_NS::FixViscosity::FixViscosity(LAMMPS_NS::LAMMPS*, int, char**)':
C:/lammps/src/MISC/fix_viscosity.cpp:44: undefined reference to 'MPI_Comm_rank'`

**LAMMPS Version and Platform**

This issue occurs with 15 Apr 2020. I did not have this issue with 7 Aug 2019 (same computer with CMake 3.14.13, g++, gcc and gfortran 8.3.0, same `cmake` command as above)

**Expected Behavior**

As of 7 Aug 2019, I had a separate installation of MPI (Microsoft MPI) and the `find_package(MPI)` command would locate it and compilation would go through.

**Actual Behavior**

There appears to be an issue with finding the static libraries. I noticed the handling of MPI for Windows has changed in the CMakeLists, without being able to pinpoint the issue myself.

In the summary printed by CMake, the variables `CMAKE_STATIC_LINKER_FLAGS`, `MPI_CXX_INCLUDE_PATH`, `MPI_CXX_LIBRARIES` and `MPI_Fortran_LIBRARIES` are all empty.

I have tried passing the path to includes and libs that mpi4win installed in my `build` directory through:
 `-D MPI_CXX_INCLUDE_PATH=C:\lammps\build\mpi4win_build-prefix\src\mpi4win_build\include`
 `-D MPI_CXX_LIBRARIES=C:\lammps\build\mpi4win_build-prefix\src\mpi4win_build\lib`
or using those of my Microsoft MPI installation without success.

Would there be a way for CMake to locate the related dependencies installed automatically by the new mpi4win ? Or should additional `-D` configuration settings be set ? I could not find that information in the manual.

I very much appreciate you help,
Jibril B. Coulibaly

**Comment by junghans** [comment]
Can you tried this patch:
```diff
--- a/cmake/CMakeLists.txt
+++ b/cmake/CMakeLists.txt
@@ -147,7 +147,7 @@ endif()

 if(BUILD_MPI)
   # We use a non-standard procedure to compile with MPI on windows
-  if (CMAKE_SYSTEM_NAME STREQUAL Windows)
+  if (CMAKE_SYSTEM_NAME STREQUAL Windows AND NOT MPI_FOUND)
     include(MPI4WIN)
     target_link_libraries(lammps PUBLIC MPI::MPI_CXX)
   else()
```

**Comment by jibril-b-coulibaly** [comment]
I have tried it and got the same issue. The `MPI_FOUND` variable was empty, I assume the block of code before does not reach `find_package(MPI)`.

The following addition to that block, on top of the patch you provide, works, but I am not sure how it breaks the cross-compilation and other things you have been working on recently.

```diff
if (CMAKE_SYSTEM_NAME STREQUAL Windows)
  option(BUILD_MPI "Build MPI version" OFF)
+  find_package(MPI QUIET) 
else()
  # do MPI detection after language activation,
  # in case MPI for these languages is required
  set(MPI_CXX_SKIP_MPICXX TRUE)
  find_package(MPI QUIET)
  option(BUILD_MPI "Build MPI version" ${MPI_FOUND})
endif()
```

If we fix it this way, it wouldn't solve the issue for users that do not have MPI already installed, which I understood is the purpose of installing mpi4win automatically. Also, the installation of mpi4win does not come with an executable like `mpirun` or `mpiexec`. Would it remain the user's responsibility to install an MPI implementation, and if so, what is the purpose of the mpi4win updates in the CMakeLists?

**Comment by akohlmey** [comment]
The automatic downloads in the MPI4WIN.cmake script file contain only the files to compile and link binaries. To **run** the resulting binaries, it is required to download and install the MPICH2 v1.4.1 installer package separately.  http://packages.lammps.org/windows.html
This is in part for historical reasons as previously compiled and distributed LAMMPS binaries for windows required that, too, as they were only the binaries, not an installer.

I am surprised that you get a working binary with the Microsoft provided MPI installer, as that one in the past required a Visual C++ installation to work. Currently, neither OpenMPI nor MPICH officially support building MPI from their sources, nor is there a supported thirdparty MPI installer. Also Microsoft has abandoned their efforts to support HPC and MPI on their OS. Thus we are staying with the most portable existing binary MPI distribution package for building LAMMPS for windows (which is done on Linux).

Since you are working on Windows 10, you should consider installing and working under the Windows subsystem for Linux. That will remove a lot of the complications of compiling an application like LAMMPS that is essentially developed only on unix-like machines.

**Comment by akohlmey** [comment]
@jibril-b-coulibaly @junghans I've updated the handling of MPI detection by making this dependent now on cross-compiling and thus no longer assuming that building for Windows means cross-compiling in PR #2023. Hopefully, that will resolve the issue. It works for native Linux compiles and cross-compiling on Fedora.

**Comment by jibril-b-coulibaly** [comment]
Thank you for the precious and informed details, and for making this change.

I forgot how I initially turned to use MS-MPI in my workflow but I recalled having issues with installing MPICH2 or building LAMMPS with it. Running [these downloads](https://www.microsoft.com/en-us/download/details.aspx?id=57467) installs an `mpiexec.exe` executable and the includes and static libraries found by CMake and I never had issues with my LAMMPS binaries so far.

> Currently, neither OpenMPI nor MPICH officially support building MPI from their sources, nor is there a supported thirdparty MPI installer.
Thus we are staying with the most portable existing binary MPI distribution package for building LAMMPS for windows (which is done on Linux).

If I understand correctly: 
1. no version of MPICH later than 1.4.1 (or other implementation such as OpenMPI) has support for Windows?
2. I didn't know about it but after brief searches will definitely turn to Windows Subsystem for Linux, seems like the best option. Are there restrictions for which implementation and version of MPI to use with WSL or is the MPICH 1.4.1 requirement only for pre-compiled LAMMPS binaries, cross-compiled on Linux using MPICH 1.4.1 libraries (if I got that right)?

Thank you very much. I hope WSL will put my Windows issues away.

**Comment by akohlmey** [comment]
> Thank you for the precious and informed details, and for making this change.
> 
> I forgot how I initially turned to use MS-MPI in my workflow but I recalled having issues with installing MPICH2 or building LAMMPS with it. Running [these downloads](https://www.microsoft.com/en-us/download/details.aspx?id=57467) installs an `mpiexec.exe` executable and the includes and static libraries found by CMake and I never had issues with my LAMMPS binaries so far.

The MPICH2-1.4.1 installer has a flaw as it does not update PATH and related settings. For the pre-compiled packages we fix this in the installer script. https://github.com/lammps/lammps-packages/blob/master/mingw-cross/installer/lammps.nsis


> > Currently, neither OpenMPI nor MPICH officially support building MPI from their sources, nor is there a supported thirdparty MPI installer.
> > Thus we are staying with the most portable existing binary MPI distribution package for building LAMMPS for windows (which is done on Linux).
> 
> If I understand correctly:
> 
> 1. no version of MPICH later than 1.4.1 (or other implementation such as OpenMPI) has support for Windows?

That does not really touch the problem. The major issue is not so much compiling MPI, but having `mpiexec` or `mpirun` launch (local and remote) processes on Windows machines. On Linux/Unix machines we have grown so used to `rsh` and later `ssh` which is ubiquitous, that one forgets that that is not how things work on Windows. It is this part of the source code that needs to be maintained and updated and for which there seems to be a lack of interest in developers sufficiently competent in Windows system programming to provide this (and also provide supported installer packages and support for Windows users).

It is the lack of building/maintaining suitable installer packages or instructions sufficient for non-system programmers to build and bundle a full MPI package with their application that makes use continue using the one tried and tested package, despite its age and quirkiness.

> 2. I didn't know about it but after brief searches will definitely turn to Windows Subsystem for Linux, seems like the best option. Are there restrictions for which implementation and version of MPI to use with WSL or is the MPICH 1.4.1 requirement only for pre-compiled LAMMPS binaries, cross-compiled on Linux using MPICH 1.4.1 libraries (if I got that right)?

WSL, especially the latest version, is effectively a Linux container running on windows. By default it contains a Ubuntu Linux and you can install native Linux package from the ubuntu repo (including pre-compiled LAMMPS binaries, BTW). Which also means, that you would build Linux binaries using the corresponding native tools and then run those binaries inside the Linux container.

If you want to build/use Windows binaries, then your current toolchain should work with the changes in PR #2023 and using WSL with a cross-compiler toolchain would be overkill.

> Thank you very much. I hope WSL will put my Windows issues away.

It all boils down to what is the environment you are most comfortable with doing programming and compiling. I use Windows so rarely and Linux so much that I always feel uncomfortable and limited by the restrictions of its standard shell, file systems, and all the things that are different from Linux systems. And I don't care enough to build an environment that I am comfortable with, since I am highly productive on Linux already. I use Windows only to run the few software packages for which no suitable Linux solution exists, a number that gets smaller all the time.

I originally figured out the way to build Windows installer packages with the cross-compiler toolchain, since I needed current LAMMPS Windows binaries for LAMMPS tutorials and I didn't want people to spend much time to build their own or lose too much time having to have to explain how to run and compile LAMMPS on Linux. We have since switched to providing customized Virtual box appliance images with pre-compiled and pre-installed LAMMPS packages and supporting software, but I keep building the Windows installers, since this is now easy to do (it is all scripted), and CMake makes it even easier, as it would now also be possible to use the LAMMPS python module on Windows as well (haven't updated the compilation/installation script for that yet).
