### ISSUE TITLE
[BUG] Working of hybrid/overlay command dependent on ordering of sub-styles

### ISSUE THREAD

**Issue by MatKie** [lammps/lammps#2031]
**Summary**

Hello everyone,

I'm trying to simulate a fluid electrolyte mixture with a mie potential and long range corrections for dispersion and electrostatics. For this I call the hybrid/overlay style with the sub-styles: mie/cut (ps1), coul/cut (ps2) and lj/long/coul/long (ps3) with lj and coul flag long (setting pair_modify compute no for this one). 
This works only if I call the sub-styles in this order: ps1, ps2, ps3 but not if I call coul/cut at the end: ps1, ps3, ps2. (Full extract of the runfile shown below).  The error I get is:
ERROR: Coulomb styles of pair hybrid sub-styles do not match (src/pair_hybrid.cpp:953)

More elaborate explanation for the reason of this setup: 
Ewald stype long range dispersion corrections are currently only supported with the LJ potential. To approximate long range corrections for a Mie potential I use the hybrid/overlay potential. The mie/cut and coul/cut commands compute the pairwise interactions up to a specific cutoff. 
The lj/cut/coul/cut does usually computes LJ and coulomb interactions without cutoffs, by splitting the interactions in a direct (up to a specific cutoff) and long-ranged sum, by setting "compute no" for this pair-style only the long-ranged sum is taken into account. Since I specify the same cutoff for all potentials the long-ranged sum of the lj/long/coul/long should combine with the pairwise interactions of the mie/cut  and coul/cut to give the full potential for this fluid mixture. I was pretty confident about this setup but since I got the error message I'm a little worried if I can split the potential like this. 

**LAMMPS Version and Platform**
LAMMPS (7 Aug 2019) running on a HP workstation, tested with and without gpu. 
I unfortunately do not have the latest LAMMPS installed.

**Expected Behavior**

Simulation should be independent of the ordering of sub-styles and either run or do not run.

**Actual Behavior**

For the order ps1, ps3, ps2 I get the following error:
ERROR: Coulomb styles of pair hybrid sub-styles do not match (src/pair_hybrid.cpp:953)

For the order ps1, ps2, ps3 I do not get an error and the simulation runs. 

I did look into pair_hybrid.cpp at the specific lines of codes and there is a check which involves the coul/cut command, but I don't quite understand if it should or should not be triggered by my input.

**Steps to Reproduce**

I attached three files which reproduce the error by just running INITIAL.in.

[minimal_ex.tar.gz](https://github.com/lammps/lammps/files/4539023/minimal_ex.tar.gz)

**Comment by akohlmey** [comment]
@MatKie I will look into resolving the inconsistent behavior (LAMMPS should consistently refuse your calculation), but your model itself is bogus.

The long-range correction has **two** parts: 1) you have an `erfc()` based damping function in real space, so the interactions are smoothly reduced to zero at the cutoff, 2) you do a lattice sum in reciprocal space, which now also has to compensate for the damping and thus turns a conditionally convergent sum into a more easily converging sum (as fewer fourier components are required to converge smooth charge distributions than for point charges). In your model, you have significant double counting, since coul/cut is non-zero at the cutoff. 
It is not possible to add dispersion correction to the mie potential. The best you can do is to increase the cutoff. Since the potential is much more short ranged than coulomb, it is not as bad an approximation, it just costs some performance. And you can add long-range coulomb with using the overlay with coul/long and a "regular" kspace style like pppm or ewald. This setup should have a **much** smaller error than combining coul/cut with kspace.

**Comment by MatKie** [comment]
Thank you for the detailed answer, I now see where the problem with the model is. 
I guess to get real long range corrections for Mie fluids I would need to adapt the lj/long/coul/long pair style, which I might look into in the future (obviously after learning a lot more about Ewald sums).

**Comment by akohlmey** [comment]
> Thank you for the detailed answer, I now see where the problem with the model is.
> I guess to get real long range corrections for Mie fluids I would need to adapt the lj/long/coul/long pair style, which I might look into in the future (obviously after learning a lot more about Ewald sums).

This would be more effort than you might expect. The LJ long-range correction is implemented only for the r**6 term. For any other power, you would have to implement it all over. Not sure, whether it is worth the effort.  Add to that, that the corresponding pair styles were written by a person with a unique programming style, that makes them hard to read for pretty much everybody else. It has been on the mind of the LAMMPS developers to re-factor those to be more in line with the rest of LAMMPS, but nobody has yet been motivated enough to undertake this effort.

**Comment by akohlmey** [comment]
Commit bc3a1187ae913d75a129306c2a496e5d4edac296 in PR #2023 should now trigger the non-matching coulomb styles error in both cases.
