### ISSUE TITLE
[BUG] Links to a static plumed library when a shared one is available

### ISSUE THREAD

**Issue by yurivict** [lammps/lammps#2067]
OS: FreeBSD 12.1
clang-9

The link line has /usr/local/lib/libplumed.a while ```/usr/local/lib/libplumed.so``` is available.

pkg-config returns a different string:
```
$ pkg-config plumed --libs
-L/usr/local/lib -lplumed 
```
which should by default link to a shared library when it is available.

Linking to static libraries makes it more difficult to track dependencies, and it also causes binaries to be larger due to code duplication.

**Comment by akohlmey** [comment]
The linkage mode of the plumed library is a compile time choice. If you want shared linkage, please set -D PLUMED_MODE=shared. This defaults to static linkage because the typical deployment of LAMMPS is a self-compiled executable of an individual researcher, *NOT* the packaging and system-wide installation.
