### ISSUE TITLE
[BUG] RESPA does not work well with KSPACE

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [lammps/lammps#2145]
**Summary**

I am trying to run a system with RESPA, and I found that the RESPA gives the following error:
`ERROR on proc 17: Out of range atoms - cannot compute PPPM (src/KSPACE/pppm.cpp:1940)`
When trying to run the code in parallel (mpirun). It is fine running with single process. In addition, when I adjust the kspace accuracy, turning lower the accuracy allow me to run more time steps, while higher accuracy gives me fewer timesteps. And I have enabled `neigh_modify delay 0 every 1 check yes`

**LAMMPS Version and Platform**

LAMMPS (2 Jun 2020) with openmpi 3.1

**Expected Behavior**

Parallel and single process should give the same result

**Actual Behavior**

They don't

**Steps to Reproduce**

I would prefer not to share my source code because it is from a project still in development. 

**Further Information, Files, and Links**

I think the problem is that the parallel process assigns the system into multiple cores when calculating KSPACE, and RESPA cause some of the particle to jump from the section of one core to another. Is there any way to optimize it?

**Comment by akohlmey** [comment]
Sorry, but this is not a usable bug report and i am not convinced that there is a bug (on the LAMMPS side) at all.

The probability of the "out of range atoms" error is related to the domain decomposition parallelization in LAMMPS, so it is more likely to happen with more MPI ranks and thus smaller subdomains. and it has nothing to do with using r-RESPA versus Verlet. 

It is particularly rare with serial calculations, because all atoms are present and if an atom moves extremely fast due to very high forces, then it will not get lost and has to cross the entire simulation domain in one time step to become out of range.

All of that hints that there is problems with either your (initial) system geometry, force field parameters, or time step or other simulation settings.

If you are still convinced that there is a bug and LAMMPS fails on valid and meaningful input, you **must** provide a test case demonstrating it. It does not need to be your specific research project, in fact, those are usually far too large and too complex for debugging. Instead you need to construct the smallest and simplest possible input deck that can reproduce the issue where you believe that LAMMPS is at fault.  An effective way of doing this, would be to start from one of the bundled example inputs, so you don't even have to include a data file. The reproducer input has to run fast on a desktop machine and reach the problematic situation quickly.  Without such an input deck it is highly unlikely that somebody will look into this, especially on code that has been used a lot and is - as such - well tested for many, many years, so the chance of a bug is low (although not zero).
