### ISSUE TITLE
Tracking parameters in sweeps

### ISSUE THREAD

**Issue by ssomnath** [lammps/lammps#2222]
Hello,

I am a data scientist working with domain scientists to help manage data generated from several simulations using [DataFed](https://arxiv.org/abs/2004.03710) - an [open source](https://github.com/ORNL/DataFed) scientific data management system. I am told that a simulation will be performed for each combination of a handful of parameters that will be swept over some range. [Here](https://github.com/Jsakkos/NUFEB/blob/add_phototroph/examples/axenic-cyanobacteria/Inputscript-var.lammps) is an example of an input file where a parameter ``s`` is varied (line 64). 

For each simulation, I would like to capture the results data in a tar ball and the associated metadata in a JSON file. The JSON and tar files will form a ``data record`` in DataFed that will be atomic / inseparable. This capture of information for DataFed can be performed after each simulation or after all simulations are complete. 

The challenge I am facing is that after all simulations are complete, the directories created to hold results from different simulations only contain the data. Given that a metadata file (with the singular combination of parameters that resulted in this data without any loops) is (apparently) not being generated for each simulation, knowing the exact metadata associated with a given data folder is challenging. Currently, I am under the impression that I would need to parse the constant parameters from the singular source input file, and then fill in the unique combination of parameters by knowing how this metadata was captured (typically in the nomenclature of the folder). While this is do-able, I thought it would be a sub-optimal solution. 

Ideally, it would be great if LAMMPS wrote out the unique combination of parameters associated with each simulation run along with the data. This way, all I would need to do is point a data ingestion script at the root directory and have it crawl / discover all simulation runs and ingest them into DataFed without needing any knowledge about which parameter was varied and how. Is it possible to do this? If so, how would we go about accomplishing this? Many thanks in advance.

**Comment by ssomnath** [comment]
Not sure how the ``invalid`` label was assigned to this issue. I did not mean to do that and am unable to remove it.

**Comment by akohlmey** [comment]
@ssomnath you have to understand that the best way to describe LAMMPS from your perspective is as a "programming language for simulations". Which means, that every statement, even the order of statements can have an impact, but also multiple combinations of statements can describe the same simulation and that there is a large and constantly growing and changing number of keywords and features.

The corollary of this is that there is no general way of creating metadata to describe the simulation. The **entire** input deck (input file(s), data file(s), potential parameter file(s) etc.) **are** the metadata. Since LAMMPS is a software with origins that date back over 25 years, it pre-dates most modern ways of managing data and scripting. This also means, that there is no simple way to output what it does into a key-value type format like JSON unless you decide to write a wrapper that takes internal data through the library interface (see below) and converts and outputs it accordingly.

The only option I see to do a project as you are describing would be to generate the _project specific_ metadata as part of the input deck. The can be done via specific print statements added to the input deck (which can be captured into a separate file): https://lammps.sandia.gov/doc/print.html

An alternative approach would be to not run the simulation from the LAMMPS executable, but use the library interface. This can be either directly from a custom C or C++ program (we do the latter for testing, where we provide information about how to "drive" tests in YAML files, cf. `unittest/force-styles/`) or with python scripting through the LAMMPS python module (not to be confused with the PYTHON package), which is quite popular for people doing simulation projects that scan parameters. There also are integration of LAMMPS as a simulation engine into more high-level tools like the Atomic Simulation Environment (ASE).

**Comment by ssomnath** [comment]
@akohlmey - thank you for your quick response. I will discuss the possibility of restructuring the way the simulations are performed. The python module sounds like a good fit.
