### ISSUE TITLE
implicit instantiation of undefined template 'ArrayTypes<Kokkos::Serial>'

### ISSUE THREAD

**Issue by ipe-zhangyz** [lammps/lammps#2249]
**Summary**

When building LAMMPS with hip backend kokkos, I got an error:implicit instantiation of undefined template 'ArrayTypes<Kokkos::Serial>', like the following:

[ 10%] Building CXX object CMakeFiles/lammps.dir/home/lammps/src/atom.cpp.o
In file included from /home/lammps/src/atom.cpp:21:
In file included from /home/lammps/build2/styles/style_atom.h:2:
In file included from /home/lammps/src/KOKKOS/atom_vec_angle_kokkos.h:25:
/home/lammps/src/KOKKOS/atom_vec_kokkos.h:131:3: error: implicit instantiation of undefined template 'ArrayTypes<Kokkos::Serial>'
  HAT::t_x_array h_x;
  ^
/home/lammps/src/KOKKOS/kokkos_type.h:499:8: note: template is declared here
struct ArrayTypes;

There are many other mambers of HAT in atom_vec_kokkos.h and in other files such as atom_vec_angle_kokkos.h and atom_vec_atomic_kokkos.h throwing the same error. However, I can build LAMMPS with cuda backend kokkos successfully.

**LAMMPS Version and Platform**

I'm using LAMMPS 21 Jul 2020 on centOS 7.6 with ROCm 3.3, and trying to build it with HIP backend kokkos.

**Steps to Reproduce**

the cmake parameters I'm using:

-C ../cmake/presets/most.cmake -C ../cmake/presets/kokkos-hip.cmake -DLAMMPS_MACHINE=mpi -DBUILD_SHARED_LIBS=yes 
-DBUILD_MPI=yes -DBUILD_TOOLS=yes -DFFT=FFTW3 -DCMAKE_PREFIX_PATH=${FFTW_DOUBLE} -DCMAKE_CXX_COMPILER=hipcc 
and in ../cmake/presets/kokkos-hip.cmake there are:
set(PKG_KOKKOS ON CACHE BOOL "" FORCE)
set(Kokkos_ENABLE_SERIAL ON CACHE BOOL "" FORCE)
set(Kokkos_ENABLE_OPENMP OFF CACHE BOOL "" FORCE)
set(Kokkos_ENABLE_HIP   ON CACHE BOOL "" FORCE)
set(BUILD_OMP OFF CACHE BOOL "" FORCE)

**Comment by akohlmey** [comment]
HIP is currently not listed as a supported platform for LAMMPS with Kokkos. I don't think that HIP support in Kokkos development has reached a point that it is usable for LAMMPS (or usable at all except for a subset of functionality). This is all made more complex with AMD switching things around significantly with their latest release.

The only GPU support option in LAMMPS that has been updated accordingly is the GPU package. That one should compile, but due to the lack of support for current AMD consumer GPU hardware, we are not able to test whether such binaries can work correctly. We have to trust the people who contributed the changes.
