### ISSUE TITLE
Consolidate/extend developer documentation

### ISSUE THREAD

**Issue by eagunn** [lammps/lammps#2257]
**Summary**

The published Developer Guide (http://lammps.sandia.gov/doc/Developer.pdf) contains useful overview information. But other information, equally useful to the same audience, now exists in other files and is not published on the web and is not pointed-to within the Guide. I recommend we move towards consolidating all the related information into one format/location so it is easier for new contributors to find and use.

**LAMMPS Version and Platform**

NA - This is not a version/platform related issue.

**Details**

For example, I was following LAMMPS last summer when @akohlmey executed the Great Header Reorganization. So I knew that a set of guidelines for the order of include statements existed somewhere. But, when I wanted to apply them to a project, I had to use my email history to track down the specific commit for doc/include-file-conventions.md to find those guidelines. Yes, I now know, the file is located in the documentation folder but that’s a case of “simple if known.” I went looking for the information in the documentation on the web and couldn’t find it.

Personally, I like the .md format currently used for the Include File Conventions ((https://github.com/lammps/lammps/blob/master/doc/include-file-conventions.md)) and Development Workflow (https://github.com/lammps/lammps/blob/master/doc/github-development-workflow.md). They are equally readable on the web from GitHub or locally with an IDE. 

It would be great to have additional documentation like the above to explain the error handling and message utility classes and what the current implementation guidelines are. Even before @akohlmey’s recent push to start using format/fmt.h there seemed to be a great variety of error/message logging code. In the absence of forward guidance, one is left to simply copy what’s already in the code you happen to be working on.

I assume these issues have already been discussed, probably multiple times. If a plan for this work already exists, then I would be happy to volunteer time to work toward that plan. 

Meantime, my specific proposal for a minimum set of useful changes is:

- Create a new folder within /doc called forDevelopers
- Move Developer.pdf and the two .md files above into that folder
- Update the first page of Developer.pdf with a note that indicates other useful information may be found in .md files in the forDevelopers folder in the GitHub repository.
- Establish the convention, among core developers who set the development guidelines, that the set of forDevelopers .md files be maintained/expanded as the preferred method of communicating development guidelines to all contributors. 
- But, as long as the information in Developer.pdf is current, I see no particular reason to tear it apart and start over.

**Comment by akohlmey** [comment]
@eagunn thanks for your thoughts and suggestions.

When looking at the LAMMPS distribution and how things are (currently) done and what are (currently) considered to be best practices, there is often a bit of a disconnect. That has mostly historic reasons (this year marks the 25th anniversary of the LAMMPS paper), and while trying to modernize the code, there is also a drive to strike a balance between simplicity, familiarity and historically grown conventions and adapting modern coding techniques and best practices. On top of that, we are restricted by the amount of workforce available and the fact, that there is little credit to be had for code refactoring, however useful it. That said, we are currently in the extremely fortunate situation that Sandia is contracting the Temple team (i.e. mostly me) for just that kind of work and due to working from home directions, I am able tackle more complex refactoring and establishing modern code development processes, since there are fewer distractions. According to my github profile, I have been more than twice as productive in the last 6 months than in previous years. If you look through the development since the last stable release, there have been multiple quite significant internal changes, in part enabled by the decision to update the minimum requirements for LAMMPS to C++11 and CMake 3.10.

Perhaps this is a good spot to list some of the ongoing efforts and give some additional explanations for what is going on.

**Text parsing, string handling, output**

We have agreed to move away from local char buffers and use `std::string` instead. We also want to get rid of the nastiness of macros like BIGINT_FORMAT.  Thanks to requiring C++11, using fmtlib has become a viable option and the fact that it has been included into the C++20 standard makes it an attractive and forward looking choice. Ideally, at some point in the future we would just need to replace the include statement and change the namespace used. That in return prompted to switch API from using `char *` arguments to `const std::string &` and then that allowed to implement convenience functions in the utils namespace that help to reduce code redundancy and create more readable code.

Another issue with strings and local buffers was the use of `strtok()` which is not thread-safe and leads to complex code. Since we always wanted to simplify that part of LAMMPS and also abstract common processes into their own class(es) so that - again - code redundancy is reduced and readability increased.  This has been applied primarily to MANYBODY pair styles but also beyond. There is still much more code that needs to be converted.  A large chunk is related to reading and writing of data files, but that will likely have to wait until the next development cycle, we are too close to the next stable release to tackle such a disruptive change now.

While these changes were implemented, the idea of overloading the `Modify::add_fix()` with a simple string and then have a `utils::split_words()` function to simplify the process of adding fixes internally came up and then was expanded to several other APIs. This is another increase in readability.

**Internal testing**

While working on the text parsing, the need to implementing some form of unit testing came up. Some parts are not strictly unittests, as they actually execute short chunks of simulations, but they turned out to be extremely helpful and could be made more abstract, so that the tests are mostly defined via input files. As we got a better feel for what the selected test library can do in combination with what we need in LAMMPS, testing expanded and some is more like conventional unit testing.  The project of refactoring the implementation of atom styles then prompted several long pending changes and expansion of testing in that area.

That said, testing is still far away from where it could be. Our code coverage in the tests is barely about 25%. On the other hand, the test library has identified a significant number of bugs and helped to improve and complete incomplete implenentations.

**Library interface refactoring and Programmer guide**

Another ongoing project is to improve the documentation for programmers. This is primarily aimed at people that a) want to use LAMMPS as a library (using the C, Python, Fortran or C++ interface) and b) want to add "standard" features and not so much at explaining all inner workings of LAMMPS. For the latter, reading the source code and the embedded comments is still the path as well as asking question about that on lammps-users.  There is already a branch "progguide" where this work is ongoing, unfortunately work on this has been delayed multiple times to address more pressing needs. By now also the corresponding pull request has been closed, since the changes are triggering other changes and they would need to be merged into the master branch in increments.  Part of this effort is to decorate library.h and library.cpp with doxygen style comments and use that in combination with some selected explanations and examples to describe the use of the library interfaces. The upstream manual is quite redundant and has in part outdated information in multiple places. This will start a new "Programmer documentation" section of the manual and the long time goal is to move all code development related documentation there. This will also include to translate and update the Developer.pdf file. Similarly the Python API is documented, but often with references for details to the C library interface which has the details. The plan for the Fortran interface is the same, only that the various existing interfaces are more or less outdated, so a new wrapper based on Fortran 2003 and the best of the existing wrappers is being written. It is supposed to look more like the Python wrapper as it includes the wrapped library function into a custom derived type (similar to the python class). The final step of this process would be to also revise and move the chapter about modifying and extending LAMMPS to that Programmer guide. In lockstep with merging the content from Developer.pdf and the modifying and extending section, some core classes in LAMMPS itself will be decorated with doxygen comments so they can be linked from the library interface documentation or the developer guide or the modify LAMMPS guide.  A core guideline for this process is that, wherever possible, redundancies should be reduced and the effort to keep the programmer documentation should be reduced. E.g. if doxygen style comments are used, then it is sufficient to update them in the source code to have the manual updated as well. Currently any change requires multiple modifications in multiple files to keep things up-to-date and in sync. This often doesn't happen, so there are inconsistencies. For your reference some links. https://github.com/lammps/lammps/pull/1970 https://github.com/lammps/lammps/tree/progguide https://docs.lammps.org/pg_developer.html  The last URL is a link to the documentation as rendered from the progguide branch. You can compare it to the online manual at lammps.sandia.gov to see how (some) things have changed. I try to keep it up-to-date with the changes from upstream.

**Some comments on your suggestions**

While the .md files are convenient, they were started way before we converted to using ReStructuredText and because it was simple to do and easy to point out to people. But they also are mainly aimed at *maintainers*.  Since we are a small group of maintainers, not everything needs to be formalized (it helps though to have it written out to look it up in case of disagreements or when talking to management who thrive on such policy documents) and also details are often in flux and conventions may change. This is doubly true when we have significant changes to the core code like we had since March 2020. There are two ideas floating around how to make things more formal: 1) device a clang-format configuration that can automate enforcing policies with respect to formatting and details like include file ordering, 2) add tests to the integration testing that flag non-compliance. Some tests are currently run but won't be reporting a fail to github and block to merge, but the failures are visible on the LAMMPS Slack channel and developers can see them there.  Depending on the skill level and experience of contributors, we may either ask them to do the changes or do it ourselves.  We don't want people to be overly concerned about violating LAMMPS coding conventions when they write their own code. Often this code never makes it back to upstream and if it does, doing a refactoring step after getting comments from the LAMMPS maintainers is often a very good idea (I tend to tell people that good (scientific) code needs to be written at least 3 times: once to do it at all, once to do it right, and once to do it well). That is often the right place to point out our conventions as those also are helpful to spot issues.

**Summary**

Part of what you suggest is ongoing.  We have settled on .rst as primary documentation format, so we plant to move everything to that format. But some of the content in the .md files is only relevant for maintainers. Some of that also needs to be updated for the next stable release as we have established new conventions for a few things. There is certainly room to contribute to the ongoing work in case you feel like it. When making changes that would enforce rules, however, we have to be mindful of people not very familiar with code development conventions and procedures and also that there are a significant number of people who prefer things "The Old Fashioned Way(tm)".

**Comment by eagunn** [comment]
@akohlmey Thank you for the expansive reply. I have been following, with great interest, all the forward progress you've made in the last year with include file order, fmt+string, etc. It's great you've been able to follow up on the adoption of C++11 with a concerted effort to move the core sources forward. 

I did search the issues, before I filed this one, for any sign of discussion/direction on the developer documentation. It did not occur to me to go looking for a branch dedicated to the effort. Now I know better and your response to this issue nicely documents the current state for anyone else who might be looking.

I would, indeed be interested in contributing, either with refactoring code to move it towards the new conventions or with working on any of the existing developer doc. I actually enjoy refactoring and, where appropriate, simplifying code.

I've been waiting for a code/output review before creating a pull request for the rest of my work on #1109. I'll probably go ahead and create a work-in-progress PR so the work doesn't get stranded in my personal repo if the review is delayed or I get pulled away.

Meantime, if you have work that could efficiently be assigned to a volunteer, I'd be happy to bite off some small chunks. (I do understand that sometimes, especially when you are in the midst of big revision sets, it can be more work to manage help than to be simply left alone to get the work done yourself.)

**Comment by akohlmey** [comment]
> I did search the issues, before I filed this one, for any sign of discussion/direction on the developer documentation. It did not occur to me to go looking for a branch dedicated to the effort. 

It used to be associated with a pull request, but the scope of the work has expanded and thus the pull request has been closed. It wasn't planned like that. Sometimes you have to go where the project leads you.  This all started from the urge to make the library interface documentation more consistent and demonstrate the use of the doxygen integration via the breathe package.
But while working on that, many other, peripheral projects popped up that were somewhat connected.

> Now I know better and your response to this issue nicely documents the current state for anyone else who might be looking.

I also wrote it down for myself. It helps to stay organized when writing down what is going through your mind. We currently have (too?) many balls in the air and it is easy to get lost. Also starting something (small and) new is often more attractive than completing something large and complex. But in some cases also, certain expertise is required or somebody that has (or can make) the time and the knowledge of the tools to complete some work.

> Meantime, if you have work that could efficiently be assigned to a volunteer, I'd be happy to bite off some small chunks. (I do understand that sometimes, especially when you are in the midst of big revision sets, it can be more work to manage help than to be simply left alone to get the work done yourself.)

Ongoing refactoring projects where people can rather easily contribute are currently:

- expansion of the test library (simplest is adding new inputs for pair, bond, angle, kspace styles, but also new test tools for dihedrals and impropers, which would be similar to the existing ones would be welcome, also for some of the (simple) LAMMPS commands are no unit tests yet, or for utility functions and standalone classes. writing tests for computes and fixes would be a more complex task and require significant internal knowledge of the LAMMPS code *and* the physics it implements). however, we just found a volunteer who submitted a handful of new tests already

- changes to get rid of sprintf() and snprintf() into local buffers through using fmtlib. similarly for outputs that require BIGINT_FORMAT or TAGINT_FORMAT and so on. connected to that is replacing redundant code that outputs to the screen and logfile pointer by building the text in a std::string instance and outputting it with utils::logmesg(). these are very incremental changes. the core code and the most commonly used packages should be mostly done by now, but there is still plenty of code to be converted in the packages.

- modernization and simplification of file and string parsing code .  those often use strtok() which is not thread safe. instead one can use alternatives like the tokenizer classes or the (much slower but more suitable for command line-like strings utils::split_words() function). along those lines, it is often needed (and should be done) to replace `char *` arguments with `const char *` or - if it is certain that no NULL pointer is passed `const std::string &). This will often allow to replace code like `if (strcmp(one,two) == 0)` with the more readable `if (one == two)`. Since we are slowly approaching the next stable release date, we don't want to do changes to complex classes, e.g. changes related to reading/parsing in the Input class or the Variable class or related to reading/parsing data file, or thermo or dump output.

- simplification of creation of internal fixes and computes. see commit 41d62b8b8b6bfa66ccc436090628f8b6491fa706 for an example.

- Integration of more contents of  https://github.com/lammps/lammps/blob/progguide/doc/src/Developer/developer.tex into https://github.com/lammps/lammps/blob/progguide/doc/src/pg_developer.rst. Add cross-references and review text to find (and annotate or correct) where it is outdated. Possibly, integrate additional information from the "policy/workflow" files into this document. In the long term the entire section about modifying and extending LAMMPS should be moved to the programmer guide. the developer guide part should give the high-level overview, the modify section could be augmented with more examples and some doxygen decorations imported via doxygen to document functions in LAMMPS that are useful to developers, like the utils:: name space. a few of these decorations already exist in the progguide branch. Please note that all of these changes would have to be done in feature branches branched from the progguide branch and pull requests would have to be submitted for that branch, not master.

Outside of the efforts of @abhiShandy, nothing is currently being done on these. I plan to work on the progguide branch, but on the library interface instead. (in addition of the usual shepherding of pull requests and chasing down bug reports). There is an open pull request on some parsing update, but that may be dropped.

**Comment by akohlmey** [comment]
What is suggested here is mostly implemented. Not yet sure whether the .md files will be integrated into the developer guide or just referenced from it. But that is something to look into after the programmer guide is more complete.
