### ISSUE TITLE
[Feature Request] Overdamped Langevin dynamics / Brownian Dynamics

### ISSUE THREAD

**Issue by XanderDW** [lammps/lammps#2351]
**Summary**

I would like to implement a new fix that simulates Langevin dynamics in the overdamped limit, commonly referred to as Brownian dynamics, so neglecting the inertial second derivative term in the equations of motion.

**Detailed Description**

Langevin dynamics in the overdamped limit, as described here: [Brownian dynamics on Wikipedia](https://en.wikipedia.org/wiki/Brownian_dynamics)

I want to include the translational as well as orientational dynamics (for finite-size particles). I think it can be implemented in a single fix that does the integration of the translational and orientational (quaternion) degrees of freedom. Velocity and angular momentum can be disregarded.

**Comment by akohlmey** [comment]
@XanderDW please clarify: are you announcing that you are starting to program this fix?
or are you looking for a collaborator to implement it?

**Comment by XanderDW** [comment]
@akohlmey Apologies for unclarity: I'm starting development on this fix myself.

**Comment by akohlmey** [comment]
> @akohlmey Apologies for unclarity: I'm starting development on this fix myself.

No problem. I was just asking because some people write *implement* when they really mean *use*.

Thanks for taking the initiative and reporting it here.

**Comment by XanderDW** [comment]
Just finished the implementation and did some sanity checks to confirm that everything seems to work as it should.

I attached the files here. Since this is my first contribution to LAMMPS, perhaps you could check if the code properly adheres to all guidelines and conventions (apart from inclusion of documentation)? 

Specifically I wonder: how should I include 2D support? Do I write a separate fix for the 2D/3D case or should I write my code more generally for d-dimensional spaces or is there another clever trick?

[LAMMPS_fix_brownian.zip](https://github.com/lammps/lammps/files/5208437/LAMMPS_fix_brownian.zip)

**Comment by akohlmey** [comment]
> Just finished the implementation and did some sanity checks to confirm that everything seems to work as it should.
> 
> I attached the files here. Since this is my first contribution to LAMMPS, perhaps someone could check if the code properly adheres to all guidelines and conventions (apart from inclusion of documentation)?

Please create a pull request for your contribution to be integrated. https://lammps.sandia.gov/doc/Howto_github.html
Pull request submissions will trigger some automated testing and thus will give you feedback on what may be needed to do before a LAMMPS developer would get to it. Please add your contribution to the USER-MISC package. If you know that it is not complete (e.g. because the required documentation is missing, submit a draft pull request).

For some general guidelines about contributing to LAMMPS, please see: https://github.com/lammps/lammps/blob/master/.github/CONTRIBUTING.md

For more detailed discussions of some policies and procedures you can check out:
https://github.com/lammps/lammps/blob/master/doc/include-file-conventions.md
and
https://github.com/lammps/lammps/blob/master/doc/github-development-workflow.md

As for 2d simulations. You can check with other styles in LAMMPS, 2d and 3d systems are usually handled with the same code path, with a few exceptions, where a test for the number of dimensions is made and then e.g. constants are adjusted to the number of dimensions, if needed.

**Comment by XanderDW** [comment]
Alright, I'll make a pull request once I finished working on the docs. Thanks!

**Comment by akohlmey** [comment]
@XanderDW please note pull request #2511 which seems to be implementing something similar. This will become a new package for brownian dynamics and self-propelled particles, so you should consider adding your contribution there and compare your implementations.

**Comment by XanderDW** [comment]
@akohlmey Thanks Axel for the heads up! I replied in the thread of that pull request with some details.

**Comment by akohlmey** [comment]
@XanderDW please let us know whether this issue is this still relevant? Or whether it can be closed?

**Comment by XanderDW** [comment]
@akohlmey I think the pull request #2511 basically rendered this thread redundant.

**Comment by jerry77o** [comment]
1
