### ISSUE TITLE
CMake build of external libraries using ExternalProject_Add() cannot take advantage of library config

### ISSUE THREAD

**Issue by ellio167** [lammps/lammps#2365]
**Summary**

The existing design choice to use ExternalProject_Add() for external libraries that are built locally (KIM, VORONOI, etc.) is unable to leverage each library's provided cmake config support.  This requires the lammps cmake code to implement (and maintain) IMPORT targets which effectively reproduces work already performed (and maintained) by the library developers.  Is there an alternative design that could allow lammps to take advantage of a library's provided cmake config features?

**LAMMPS Version and Platform**

LAMMPS w/ CMake build

**Details**

To my understanding an alternative would be to configure/build/install the requested/necessary external libraries at LAMMPS configure time.  (I would guess this was considered during the development of the cmake build support in LAMMPS, so I would be interested in knowing why ExternalProject_Add() was selected instead.)

**Comment by akohlmey** [comment]
@ellio167 I cannot comment on the details. I suspect a lot of the layout and design of the CMake scripts is a leftover from the efforts of trying to be compatible with CMake 2.18. But honestly, this is not a big concern currently. The situation is quite complex as we want to have similar behavior between CMake builds and traditional builds, and we want to support system-wide installation as well as transparent download, where it is doable. The in-place build of large packages like the KIM-API or PLUMED2 is primarily meant for use with (automated) compilation testing and debugging and thus more aimed at developers than users. Since it **does** work, the effort to keep it working is small compared to redoing everything.

**Comment by junghans** [comment]
I would say, lammps' CMake is not a package manager if you want to compile package in custom way just use something like Spack or brew.

**Comment by ellio167** [comment]
Thanks for the replies.  I was really thinking about a way to refactor Package code, say the KIM.cmake file, to eliminate the code that defines the imported targets (since these are already coded up by the library's cmake config files).

**Comment by akohlmey** [comment]
I don't think that is worth the effort.
