### ISSUE TITLE
[Feature Request] neighbor lists and gpu

### ISSUE THREAD

**Issue by matiasf86** [lammps/lammps#2394]
**Summary**
Neighbour list are build in gpu in a way that do not reproduce cpu results (for example the energies), specially when using a system compose by atoms with bonds (diatomic molecules) and that interact through stillinger weber potential, as if special_bond lj  0.0 0.0 0.0 is not taking into account. Could a patch me made to solve this ?.

  **Detailed Description**
I have recently wrote to lammps mailing list about this behaviour when using stillinger Weber potential for atom with bonds, diatomic molecules. 
I copy here my original mail and Axel's answer 

Recently I have been using the SW pair style in a system composed of several pairs of sw atoms joined by explicit bonds, the distance between pairs of atoms is fixed by shake. In other words a system of diatomic molecules.
I know this is not the standard way of using this pair style and that LAMMPS gives a warning about this. Nevertheless this has already been used in several works with good results.
I have no problems running this system on the CPU. Nevertheless when I try to run it on the GPU  I get positive energy.
After inspecting it a little bit I realized that the gpu part was not taking into account the default "special_ bonds lj 0.0 .0.0 0.0", and is considering "special_ bonds lj 1.0 .1.0 1.0". That's because when I put "special_ bonds lj 1.0 .1.0 1.0" and run it in CPU I get the same results as in GPU.
The results in GPU don't change even if i explicitly write "special_ bonds lj 0.0 .0.0 0.0",

This happens with LAMMPS (24 Aug 2020)

Can a patch be made for the gpu to take into account  the special_bonds when running with pair sw ???

I attached a small box with the system and an input script for testing purpose(test_files_gpu.zip)

----------------Axel's answer------------------
whether this can be implemented is a question of whether people familiar with the GPU package have the time.
the situation is more complex than you think, since this is not about the pair style itself, but about the building of the neighbor lists.

you should see that is is not due to the pair style when you would use on the CPU

special_bonds lj/coul 1.0e-100 1.0e-100 1.0e-100

this should result in nearly the same forces and energies than the GPU version, since the special bonds factors are ignored by the CPU version of the pair style as well.
only that the neighbor list build has an additional pass that will remove special neighbors from the neighbor list when all scaling factors are exactly 0.0.

similarly, if you would tell the GPU package not not build the neighbor list on the GPU but use the CPU neighbor list,

e.g. with: package gpu 1 neigh no

you should get the same behavior as on the CPU (just a little bit slower).

Axel.
[test_files_gpu.zip](https://github.com/lammps/lammps/files/5284310/test_files_gpu.zip)

**Comment by akohlmey** [comment]
@matiasf86 just tested your example input deck with the latest LAMMPS version (28 July 2021).
Due to your use of fix shake, the difference in the computed forces due to the lack of exclusions does not result in different trajectories. But as already mentioned on the mailing list, using the neighbor lists built on the CPU reproduces also the energies exactly. Since this is a rather unconventional application and because there is no simple way to add a meaningful warning beyond what is already printed, I think the way forward from the LAMMPS perspective is to stick with the current settings.
It is already documented behavior that custom exclusions do not work with GPU based neighbor lists, this is a very similar case and the solution is the same.
