### ISSUE TITLE
[BUG] -xHost and Intel compilers on AMD

### ISSUE THREAD

**Issue by ocaisa** [lammps/lammps#2457]
**Summary**

Using `-xHost` with (some?) Intel compilers on AMD results in a restriction to SSE2 instruction, i.e., a very slow executable.

**LAMMPS Version and Platform**

LAMMPS 3Mar2020 with Intel 2020.1.217 toolchain on AMD Zen2

**Expected Behavior**

Uses optimum instruction set.

It currently seems like setting `set(CMAKE_TUNE_DEFAULT "")` for this case is the best option.

**Actual Behavior**

SSE2 instruction set used

**Steps to Reproduce**

Build with Intel compilers on AMD 

**Further Information, Files, and Links**

See https://github.com/easybuilders/easybuild-easyconfigs/pull/11577 for details

**Comment by akohlmey** [comment]
I don't think this is something that should be addressed in LAMMPS because a) it is the choice of the Intel compiler to select an inefficient instruction set when you ask it for optimal settings for the compiling host and thus - technically speaking - if this would be a bug, it is a bug in the Intel compiler, and b) this is just a default and if you prefer a different choice, you can override it with `-DCMAKE_TUNE_FLAGS` to whatever setting you prefer.

**Comment by ocaisa** [comment]
Sure, this was as much an FYI as anything else, in case anyone runs into this problem.
