### ISSUE TITLE
LAMMPS_for_Large_SPH_simulations

### ISSUE THREAD

**Issue by Efstathios96979** [lammps/lammps#2490]
I try to simulate  3 dimensional close channel flows with SPH. Although I achieved good results when working on mm, I can not increase the dimensions of my problem (to cm and m). Do you have any suggestions;
I tryied a lot of changes mainly with lattice command,Should I try more; or LAMMPS has  scale limitations?

**Comment by akohlmey** [comment]
- what platform are you running on?
- what hardware are you running on?
- what is the exact command line?
- what settings did you use the compile LAMMPS?
- what are the error messages you get?
- or what other symptoms are prohibiting you from running those simulations?

the size limitations of LAMMPS are documented in the manual: https://docs.lammps.org/Build_settings.html#size
these are upper limits. there may be additional limitations imposed by individual commands.

please also note that even under the most perfect conditions, i.e. linear weak scaling, a 3d simulation that is grown by 3 orders of magnitude in each direction, but otherwise identical settings, will require a billion times the CPU time and thus would need to be run on an extremely large parallel computer.

**Comment by Efstathios96979** [comment]
I run on parralel 16 lmp_mpi on a "decent" computer through command Promt(windows). I do not get any error messages, everything seems normal but the velocity_profile (which i need) is wrong. I use the commands:
pair_style hybrid sph/taitwater/morris
pair_coeff * *    sph/taitwater/morris 1000 0.1 1.0e-3 1.0e-4 6.5e-5

compute            rho_peratom all meso/rho/atom
compute            e_peratom all meso/e/atom
compute            ke_peratom all ke/atom
compute            esph all reduce sum c_e_peratom
compute            ke all ke
variable           etot equal c_ke+c_esph
the lattice i use is fcc  0.0925e-3 (696500 atoms

--> Do I need a larger kernel lenght? (h) or a larger lattice?

**Comment by akohlmey** [comment]
this is an incomplete input and the description provided is contradicting your initial assertion of having problems with different size simulations as you only describe one specific system size. there is also no information about equilibration or how you obtain the velocity profile that you require. moreover this isn't really an issue about the LAMMPS implementation but about usage and thus it is off-topic for the development repository. Please reformulate your question and provide sufficient details (you left out answers to several questions I had asked or provided vague or incomplete information) and post to the lammps-users mailing list instead.
