### ISSUE TITLE
[Feature Request] String vector in fix property/atom (Minor)

### ISSUE THREAD

**Issue by ketankhare** [lammps/lammps#2513]
**Summary**

fix property/atom allows the addition of integer and floating-point per atom vectors. Can this be extended to short strings with no spaces? 

**Detailed Description**

For atomistic simulations, there are some per atom string descriptors that are helpful during analysis and also potentially for use with groups. For example: residue name, force field atom type, or atom name (unique atom name in a given type of molecule). At the moment, I have been maintaining an index file that keeps track of this information indirectly. But it would be convenient to carry these descriptors in the data file itself. This will ensure that if the system were replicated, or multiple data files were read, or some atoms/molecules were deleted, that these descriptors would conveniently port. Also the descriptors could be in the data file, and the group command could be invoked to select all atoms that belong to a given residue (by name). The disadvantage of such a feature would be that any such information would not be computationally relevant (like molecule IDs), and would be a waste of memory, although I do not believe that there should be any meaningful impact on the computational speed.

I have looked at the code for the fix, and I think that it should be possible to add such a feature (and I would be willing to propose the changes). Any advice from the community would be welcome. Are there any major obstacles that I have not anticipated?

**Comment by akohlmey** [comment]
please note that your suggestion has overlap with issue #2002 
on top of that, having strings as per-atom property is tricky unless you would assign a fixed/limited storage per string as it would make communication rather complicated. on top of that, there is the question of the amount of storage required. since those strings would for the most part be highly redundant, so strings would either be restricted to 3 characters (plus terminating 0) or implemented via a (global) hash table and then using the index (a 32-bit int requires the same storage as 4 characters).

**Comment by ketankhare** [comment]
Thanks Axel! You're right about the overlap. I will read the discussion in issue #2002 and see how I can contribute.
