### ISSUE TITLE
Pair Write Issue

### ISSUE THREAD

**Issue by blaufer** [lammps/lammps#2526]
When using the pair_write command, there is an issue. If no atoms are created, the energy curve is smooth and appears correct but when atoms are created, this not true and is much more extreme in some cases. Here is a minimal working example using a potential included with LAMMPS, first without creating atoms then with doing so.

WIthout:

    units metal
    region simbox block 0 1 0 1 0 1 units box
    create_box 2 simbox
    
    pair_style eam/alloy
    pair_coeff * * AlCu.eam.alloy Al Cu
    
    run 0
    
    pair_write 1 1 1000 r 1.0 8.0 AlCu_Al_pair_write.txt Al
    pair_write 2 2 1000 r 1.0 8.0 AlCu_Cu_pair_write.txt Cu

With:

    units metal
    region simbox block 0 10 0 10 0 10
    create_box 2 simbox
    
    lattice fcc 4.0479
    region al block 0 5 0 5 0 5
    create_atoms 1 region al
    lattice fcc 3.6149
    region cu block 0 5 0 5 0 5
    create_atoms 2 region cu
    
    pair_style eam/alloy
    pair_coeff * * AlCu.eam.alloy Al Cu
    
    run 0
    
    pair_write 1 1 1000 r 1.0 8.0 AlCu_Al_pair_write.txt Al
    pair_write 2 2 1000 r 1.0 8.0 AlCu_Cu_pair_write.txt Cu

An extreme case occurs with the tungsten-hydrogen potential from Wang, et al. (J. Phys.: Condens. Matter 29 (2017) 435401). .

**Comment by akohlmey** [comment]
This is not an issue with the pair write comand, but a limitation of the eam pair styles. It doesn't really make sense to use `pair_write` on a manybody potential, but for historical reasons, there is a "hack" implemented that allows to use eam pair styles with `compute group/group` which in turn requires and implementation of the `Pair::single()` function. This is also what `pair_write` uses and there is no way to detect this and cause a selective error.
Whichever way you put it, the output from `pair_write` for eam will be wrong, since the embedding contribution is dependent on atoms of the environment, while `pair_write` is just picking the embedding contribution from the first two atoms (if present, without atoms it is zero hence the difference).

**Comment by blaufer** [comment]
Can something saying not to have some in the system for EAM and other many body potentials so that others don't run into the same issue?

**Comment by akohlmey** [comment]
> Can something saying not to have some in the system for EAM and other many body potentials so that others don't run into the same issue?

If we would start writing down everything that you cannot or should not do with a package as complex and large and flexible as LAMMPS, there would be not end to it. As I already wrote, it makes no sense to write out a pairwise table for a manybody potential in general. There *is* already a note about EAM in the docs for the pair_write command. It looks like it predates the "hack" that allows using the "single()" functionality with compute group/group that I pointed to that is responsible for the behavior change for with/without atoms that you noticed.
