### ISSUE TITLE
Review use of THERMO_ENERGY in Fix::setmask() and methods of computing of the conserved quantity in MD

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2528]
There are some inconsistencies and unusual behavior due to choices made a long time ago, that need to be reviewed and possibly some changes made.  For details, please see the discussion on PR #2515 

Please also note the inconsistency discussed in Issue #2537 

Further discussion results and proposed changes should be documented here.

**Comment by sjplimp** [comment]
Here's what I propose:

(1) leave non thermostat fixes that set THERMO_ENERGY mask alone
(2) look at package fixes that use THERMO_ENERGY in non-standard ways, possibly standardize
(3) for thermostat fixes:
  add fix.h variable ebath that stores cumulative energy
  add fix.h flag ebath_flag, set to 1 by thermostat fixes
  leave ebath as output of compute_scalar()
(4) in thermo style:
  add econserve keyword = ke + pe + (sum of ebath for fixes with ebath_flag set)

**Comment by athomps** [comment]
This seems reasonable.  I would change ebath to ecouple or ereservoir, which is less specific.  For example, barostat fixes will require the same treatment, but they exchange volume with an elastic medium, rather than heat with a bath.  I like the `econserve` idea, because it is very explicit, no confusion about meaning of `etotal`.  Implied by Steve is that THERMO_ENERGY and `fix_modify energy yes` command will be removed for thermostat fixes i.e. restricted to fixes that apply a conservative force.  Since many of those fixes also set `virial_flag = 1` and support `fix_modify virial yes`, it would make sense (if feasible and practical) to replace THERMO_ENERGY with a new member variable `energy_flag = 1`, for those fixes.
