### ISSUE TITLE
[BUG] Setforce 0 0 0 not works in Reax

### ISSUE THREAD

**Issue by mehdifar943** [lammps/lammps#2541]
Dear lammps group
the command ID Group-Id setforce 0 0 0 not works in Reax method and the atoms in this group-id move during simulation after appling this command in lammps-stable 29 Oct 2020.

**Comment by akohlmey** [comment]
a) the function of fix setforce is completely independent of the choice of pair style
b) using fix setforce on its own is insufficient to immobilize atoms. they also have to have no velocity. see Newton's 1st law.
c) without providing a detailed description of how to reproduce the issue and in particular a convincing argument why this happens when using reaxff, there is nothing that can be done.

**Comment by akohlmey** [comment]
see #2543 for a description of a demonstration that fix setforce *does* work with reaxff.
