### ISSUE TITLE
[BUG] lammps python module leaves mpi4py in broken state

### ISSUE THREAD

**Issue by bernstei** [lammps/lammps#2605]
**Summary**

The lammps python module when compiled without MPI still imports `__version__` from mpi4py, but this leaves mpi4py in a state where you cannot actually start mpi.  I haven't yet figured out whether this is really a lammps bug or just lammps triggering an mpi4py bug.  It can apparently be worked around easily by adding `if self.has_mpi_support:` to the code bit that sets `self.has_mpi4py` in core.py:
```
    if self.has_mpi_support:
        try:
          from mpi4py import __version__ as mpi4py_version
          # tested to work with mpi4py versions 2 and 3
          self.has_mpi4py = mpi4py_version.split('.')[0] in ['2','3']
        except:
          pass
```
In my opinion this is better coding practice as a general principle.

As an aside, I discovered this because ASE checks if `'mpi4py'` is in `sys.modules`, and if so, automatically tries to get ready for parallel I/O (and then crashes when it tries to get `mpi4py.MPI.MPI_COMM_WORLD`).  Even when you use a non-MPI lammps library, the python module _does_ leave `'mpi4py'` in `sys.modules`, which then throws off ASE.  I think that this is probably sloppy on the part of ASE, but if there's no need for lammps to import anything from mpi4py, I think it shouldn't.

**LAMMPS Version and Platform**

github master branch 16004e8f454aa, CentOS 7 + gfortran 7.3.1

**Expected Behavior**

start a serial lammps with `lmp = lammps()`, then later do `from mpi4py import MPI` successfully

**Actual Behavior**

`from mpi4py import MPI` after `lmp = lammps()` crashes with an error.

**Steps to Reproduce**

```tin 1002 : python
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lammps import lammps
>>> lmp = lammps(name='tin_serial')
LAMMPS (10 Feb 2021)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (../comm.cpp:94)
  using 1 OpenMP thread(s) per MPI task
>>> from mpi4py import MPI
*** The MPI_Comm_set_errhandler() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[tin.nrl.navy.mil:08611] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

**Comment by akohlmey** [comment]
@bernstei thanks for the report. This is a valid concern, but it looks to me, that - at least on my machine - changing the LAMMPS python module is not sufficient. There is another issue causing problems and that is having to shared libraries with MPI functions, the LAMMPS library, and the real MPI library. Thus avoiding the loading of mpi4py in the LAMMPS python module will only postpone the problem, since either some of the MPI calls from mpi4py are then diverted to the corresponding functions from the STUBS library included in LAMMPS or the other way around calls to the STUBS library forwarded to the real MPI library. So either MPI refuses to run because `MPI_Init()` is taken from STUBS and then it complains when some function that is not part of STUBS is called about not calling `MPI_init()`, or the MPI library crashes when the data structures passed by MPI calls in LAMMPS itself are those of STUBS  but are passed to calls from the real MPI library and then cause segfaults or inconsistent behavior.

**Comment by akohlmey** [comment]
We will have to think of a way to "mask" the MPI STUBS symbols in a way so that they will not be visible under their original name in the LAMMPS shared library.
@rbberger @sjplimp any ideas?
could we rename all MPI functions in src/STUBS/mpi.h from MPI_XXX to MPI_STUBS_XXX and then use preprocessor defines so we can use them as MPI_XXX in the code?

**Comment by bernstei** [comment]
Indeed, but see also #2606 .  There's a workaround for the symbol issue there, namely passing `os.RTLD_DEEPBIND` to the `CDLL()` calls.  I do agree that giving the fake MPI library symbols different names and then using a preprocessor would also solve that problem completely.  I don't have a strong feeling as to which solution is better.

**Comment by akohlmey** [comment]
> Indeed, but see also #2606 . There's a workaround for the symbol issue there, namely passing `os.RTLD_DEEPBIND` to the `CDLL()` calls. I do agree that giving the fake MPI library symbols different names and then using a preprocessor would also solve that problem completely. I don't have a strong feeling as to which solution is better.

The real issue is that both LAMMPS and mpi4py are using ctypes to import symbols and that bypasses any use of "weak symbols" in the shared libraries. If this was a compiled executable, the names of the MPI_XXX functions are weak aliases to PMPI_XXX functions and thus the symbol lookup will work (if the link order is correct), since when loading the symbols in the executable from the shared library, the compiled code will only look for PMPI_XXX and thus does not conflict with the STUBS library.
With LAMMPS stubs we have the benefit of linking STUBS as "static" library to the shared LAMMPS library, so preprocessor defines can work since the MPI symbols are never needed outside of LAMMPS.

**Comment by akohlmey** [comment]
Here are some proposed changes to the LAMMPS python module. 
https://github.com/lammps/lammps/compare/master...akohlmey:collected-small-changes

**Comment by bernstei** [comment]
Looks good to me.  If no one else does, I may try to investigate why the previous behavior left mpi4py in a broken state, and report that to those developers.

**Comment by akohlmey** [comment]
> Looks good to me. If no one else does, I may try to investigate why the previous behavior left mpi4py in a broken state, and report that to those developers.

I suspect it is the shared library symbol thing behind both #2606 and this issue. It just manifests itself differently. When the STUBS MPI_Init() is called, OpenMPI will complain that MPI was used before initialization.

What LAMMPS was doing by importing selectively `__version___` does not really cause problems, because that is just importing a constant and thus does not trigger any actions inside of mpi4py. But still, it can be avoided due to the recently added introspection, which was not present, when this part of the python module was originally written.

**Comment by akohlmey** [comment]
> We will have to think of a way to "mask" the MPI STUBS symbols in a way so that they will not be visible under their original name in the LAMMPS shared library.
> @rbberger @sjplimp any ideas?
> could we rename all MPI functions in src/STUBS/mpi.h from MPI_XXX to MPI_STUBS_XXX and then use preprocessor defines so we can use them as MPI_XXX in the code?

An even simpler workaround would be to return to compiling STUBS with C++ instead of C. That would change the symbols in the library to have the C++ encoding and thus make them "invisible" to C, but then we just have to make certain that STUBS/mpi.h has a test, so that it will fail when being compiled in C, and nothing in LAMMPS may assume the MPI calls follow C calling conventions (unlike for a real MPI library).

**Comment by bernstei** [comment]
On Feb 16, 2021, at 6:29 PM, Axel Kohlmeyer <notifications@github.com<mailto:notifications@github.com>> wrote:

An even simpler workaround would be to return to compiling STUBS with C++ instead of C. That would change the symbols in the library to have the C++ encoding and thus make them "invisible" to C, but then we just have to make certain that STUBS/mpi.h has a test, so that it will fail when being compiled in C, and nothing in LAMMPS may assume the MPI calls follow C calling conventions (unlike for a real MPI library).

Not that it's my call, but I think this is an ugly hack.  It does have the advantage over actually renaming the stubs routines that it's less work.

**Comment by akohlmey** [comment]
> Not that it's my call, but I think this is an ugly hack. It does have the advantage over actually renaming the stubs routines that it's less work.

It also has the advantage that (a long time ago) the STUBS code used to be compiled as C++, so we know that it will work and not cause any breakage for the common use cases. Any symbol renaming gimmick would be something new and since it would require some "preprocessor magic", it would be rather hackish as well.

In the end, these kind of decisions are the privilege of @sjplimp, being the fearless leader of our clan.

**Comment by akohlmey** [comment]
@bernstei we went the C++ABI way. and #2606 should be resolved in the master branch now. It clears my tests with both OpenMPI and MPICH on top of a serial LAMMPS library and with loading mpi4py before and after LAMMPS.

**Comment by bernstei** [comment]
On Feb 17, 2021, at 6:06 PM, Axel Kohlmeyer <notifications@github.com<mailto:notifications@github.com>> wrote:

@bernstei<https://github.com/bernstei> we went the C++ABI way. and #2606<https://github.com/lammps/lammps/issues/2606> should be resolved in the master branch now. It clears my tests with both OpenMPI and MPICH on top of a serial LAMMPS library and with loading mpi4py before and after LAMMPS.

Thanks.  I'll check it out.

Noam
