### ISSUE TITLE
Issues on initializing lammps multiple times with gpu package in python.

### ISSUE THREAD

**Issue by zilu19** [lammps/lammps#2619]
**Summary**

I found an issue when I initial lammps twice in python with gpu package being used.

**LAMMPS Version and Platform**

Lammps (29 Oct 2020) on CentOS 7.4, compiled with openmpi 2.1.1, on node with four GTX 1080 Ti

**Details**

I want to initiate two lammps instances in python and run two simulation alternatively. I use gpu package to accelarate the simulations. The first lammps system works no problem. However, when the second system start, it gives cuda error below:

> Cuda driver error 1 in call at file 'geryon/nvd_kernel.h' in line 364.

It looks like when the second lammps instance started, it triggered a gpu conflict. 

I then changed the second simulation without package gpu accelaration. It just works without problem.

I guess once the first lammps object was initiated, the gpu resources are somehow locked and the gpu cannot be used for other object within the scope of the python code.

Is there any method to run two lammps object with gpu accelaration in python?

Below is the test code that can reproduce the issue.

test.py:
#================#
from mpi4py import MPI
comm = MPI.COMM_WORLD
me = comm.Get_rank()
nprocs = comm.Get_size()
from lammps import lammps
lmp0 = lammps()
lmp1 = lammps()
D=30
P=1.0
lmp0.command("package gpu 4")
lmp0.command("units lj")
lmp0.command("atom_style full")
lmp0.command("pair_style lj/cut/gpu 2.5")
lmp0.command("region box block -%f %f -%f %f -%f %f units box"%(D,D,D,D,D,D))
lmp0.command("create_box 2 box")
lmp0.command("lattice sc 1.0")
lmp0.command("create_atoms 1 region box units box")
lmp0.command("mass * 1.0")
lmp0.command("velocity all create 1.0 1234")
lmp0.command("pair_coeff * * 1.0 1.0 1.12246")
lmp0.command("neighbor 1 bin")
lmp0.command("fix 1 all nve")
lmp0.command("fix 2 all langevin 1 1 1.0 1234")
lmp0.command("thermo 100")
lmp0.command("min_style cg")
lmp0.command("minimize 1.0e-4 1.0e-6 100 1000")
lmp0.command("timestep 0.001")
lmp0.command("reset_atom_ids")
lmp0.command("run 1000")

lmp1.command("package gpu 4")
lmp1.command("units lj")
lmp1.command("atom_style full")
lmp1.command("pair_style lj/cut/gpu 2.5")
lmp1.command("region box block -%f %f -%f %f -%f %f units box"%(D,D,D,D,D,D))
lmp1.command("create_box 2 box")
lmp1.command("lattice sc 1.0")
lmp1.command("create_atoms 1 region box units box")
lmp1.command("mass * 1.0")
lmp1.command("velocity all create 1.0 1234")
lmp1.command("pair_coeff * * 1.0 1.0 1.12246")
lmp1.command("neighbor 1 bin")
lmp1.command("fix 1 all nve")
lmp1.command("fix 2 all langevin 1 1 1.0 1234")
lmp1.command("thermo 100")
lmp1.command("min_style cg")
lmp1.command("minimize 1.0e-4 1.0e-6 100 1000")
lmp1.command("timestep 0.001")
lmp1.command("reset_atom_ids")
lmp1.command("run 1000")`

#====================#

Command line:

mpirun -np 24 -mca btl vader,openib,self -hostfile hostfile python test.py

hostfile:
gpu-node0 slots=24

Thanks.

Zilu

UNC - chapel hill.

**Comment by stanmoore1** [comment]
I think this is similar to the issue in https://github.com/lammps/lammps/pull/2470. It would be nice to make this all consistent for multiple packages.

**Comment by akohlmey** [comment]
@zilu19 As you have observed, you cannot have two LAMMPS instances at the same time open **and** access the GPU.
There have been some improvements to the GPU package recently that are now available in the master branch on GitHub, but even then it will not fail but stall. What does work is if you call `lmp0.close()` before you start with the GPU on the second instance, but that also means you will have to create a new LAMMPS in lmp0. I.e. you can initialize LAMMPS multiple times, but have to delete the LAMMPS instance using the GPU before you can use another one.

The only way that I can think of so that you can keep the LAMMPS instances open and alternate between them is by splitting the MPI communicator and then run each LAMMPS instance on part of the processes (they can still share the same GPU(s)) with something like the following:
```
from mpi4py import MPI
world = MPI.COMM_WORLD
me = world.Get_rank()
color = me % 2
part = world.Split(color,0)

from lammps import lammps

if color == 0:
    lmp0 = lammps(comm=part)
else:
    lmp1 = lammps(comm=part)

D=30
P=1.0

if color == 0:
    lmp0.command("package gpu 0")
    lmp0.command("units lj")
    lmp0.command("atom_style full")
    lmp0.command("pair_style lj/cut/gpu 2.5")
    lmp0.command("region box block -%f %f -%f %f -%f %f units box"%(D,D,D,D,D,D))
    lmp0.command("create_box 2 box")
    lmp0.command("lattice sc 1.0")
    lmp0.command("create_atoms 1 region box units box")
    lmp0.command("mass * 1.0")
    lmp0.command("velocity all create 1.0 1234")
    lmp0.command("pair_coeff * * 1.0 1.0 1.12246")
    lmp0.command("neighbor 1 bin")
    lmp0.command("fix 1 all nve")
    lmp0.command("fix 2 all langevin 1 1 1.0 1234")
    lmp0.command("thermo 100")
    lmp0.command("min_style cg")
    lmp0.command("minimize 1.0e-4 1.0e-6 100 1000")
    lmp0.command("timestep 0.001")
    lmp0.command("reset_atom_ids")
    lmp0.command("run 1000")
    world.Barrier()
else:
    world.Barrier()
    lmp1.command("package gpu 0")
    lmp1.command("units lj")
    lmp1.command("atom_style full")
    lmp1.command("pair_style lj/cut/gpu 2.5")
    lmp1.command("region box block -%f %f -%f %f -%f %f units box"%(D,D,D,D,D,D))
    lmp1.command("create_box 2 box")
    lmp1.command("lattice sc 1.0")
    lmp1.command("create_atoms 1 region box units box")
    lmp1.command("mass * 1.0")
    lmp1.command("velocity all create 1.0 1234")
    lmp1.command("pair_coeff * * 1.0 1.0 1.12246")
    lmp1.command("neighbor 1 bin")
    lmp1.command("fix 1 all nve")
    lmp1.command("fix 2 all langevin 1 1 1.0 1234")
    lmp1.command("thermo 100")
    lmp1.command("min_style cg")
    lmp1.command("minimize 1.0e-4 1.0e-6 100 1000")
    lmp1.command("timestep 0.001")
    lmp1.command("reset_atom_ids")
    lmp1.command("run 1000")

#====================#
world.Barrier()
```

**Comment by zilu19** [comment]
Thank you, Axel. I did try this split method before. It works. However, the problem is my simulation is actually running alternatively. My algorithm requires that one simulation must get some information from another one before starting. If the split method is being used, then I probably have to waste 50% of the computational power of the node. This is the reason why I want to stack two simulations and running on same node.

I also tried to change the partitioning of the gpu resources via "package gpu 2 gpuID 0 1" and "package gpu 2 gpuID 2 3". It doesn't work. 

Using lmp0.close() after each simulation will solve the problem but the time for re-initializing is somehow taking more time than the simulation itself.

Anyway. I will use the slower method. Hope it could be improved in later version.

Zilu

**Comment by akohlmey** [comment]
> Thank you, Axel. I did try this split method before. It works. However, the problem is my simulation is actually running alternatively. My algorithm requires that one simulation must get some information from another one before starting. If the split method is being used, then I probably have to waste 50% of the computational power of the node. This is the reason why I want to stack two simulations and running on same node.

You are not paying attention. The example I provided **does** alternate between the two instances. Check out the MPI barriers!
Your logic also is flawed. With splitting the MPI communicator you split the CPUs but **not** the GPUs. It looks like you have 24 CPU cores and 4 GPUs. That means you are - when using all MPI ranks - oversubscribing each GPU six (6!) times, so with a split communicator you are "only" oversubscribing three times. For as long as the bulk of your performance comes from the GPU acceleration, there is not much of a loss and **definitely** not a 50% waste. The only downside of using a split communicator is that will have to do extra communication to send the results from one partition to the other, since those are now on different processes. But that cannot be too difficult. In the simplest case you can just do a broadcast on the world communicator from the (global) rank that is the same as the color.
 
> I also tried to change the partitioning of the gpu resources via "package gpu 2 gpuID 0 1" and "package gpu 2 gpuID 2 3". It doesn't work.

That does not make sense. The problem is the "GPU driver context" and the "GPU kernel instances" those are held statically and thus you cannot keep those active and mix between LAMMPS instances. Actually using only a subset of the GPU would incur the 50% performance penalty that you were mentioning before. So there really is no point to it.

> Using lmp0.close() after each simulation will solve the problem but the time for re-initializing is somehow taking more time than the simulation itself.


> 
> Anyway. I will use the slower method. Hope it could be improved in later version.
> 
> Zilu

**Comment by zilu19** [comment]
Thank you Axel. You are right, the major computation are done via gpu not cpu. The split method will have the minimal performance penalty. I didn't do it in the right way. I will correct my code. Thanks for you detailed explanation.

Zilu

**Comment by akohlmey** [comment]
> I think this is similar to the issue in #2470. It would be nice to make this all consistent for multiple packages.

I don't think so. The GPU package can be initialized multiple times from multiple LAMMPS instances, it just cannot have two GPU contexts open on the same process at the same time since those are not stored in a per-LAMMPS instance storage.
