### ISSUE TITLE
Futile request for memory(double) with MyPage

### ISSUE THREAD

**Issue by tuoping** [lammps/lammps#2660]
Hello, I am trying to write a new pair style and stumbled upon a issue. 
When I requested memory by "dpage = new MyPage<double>[nmypage]", it simply doesn't work. No address is stacked or allocated or anything.
Did I do anything wrong?
Thank you so much in advance.

**Comment by akohlmey** [comment]
> Hello, I am trying to write a new pair style and stumbled upon a issue.
> When I requested memory by "dpage = new MyPage[nmypage]", it simply doesn't work. No address is stacked or allocated or anything.
> Did I do anything wrong?

probably. most likely you should not be using this facility in the first place. also the syntax you quote is incorrect.
but since you provide no other tangible information or explain why you cannot use the "normal" C++ memory allocation or the create/grow/destroy mechanism from the Memory class, it is impossible to give any advice.

> Thank you so much in advance.

**Comment by akohlmey** [comment]
No followup was posted.

**Comment by tuoping** [comment]
Sorry didn't feed back sooner. Thank you for your reply.
