### ISSUE TITLE
[BUG] _make intel_cpu_intelmpi with an errror_

### ISSUE THREAD

**Issue by sailangyf** [lammps/lammps#2734]
**Summary**

When I compiled lmp_intel_cpu_intelmpi with the command " make intel_cpu_intelmpi", there was an error : ld : not found -lqmmm ld : not found -lmesont ld : not found -lcolvars ld : not found -lpoems.

**LAMMPS Version and Platform**

Stable release 29 October 2020

**Expected Behavior**

With the command " make intel_cpu_intelmpi " , it will be successfully compiled.

**Actual Behavior**

Error! 

**Steps to Reproduce**

step1 
cd src
step2 
make ps
step3
 make yes-all
step4 
make no-USER-QUIP
         make no-user-h5md
         make no-user-plumed
         make no-mscg
         make no-message
         make no-latte
         make no-kim
         make no-gpu
         make no-user-smd
         make no-python
         make no-user-vtk
         make no-USER-ADIOS
         make no-USER-SCAFACOS
         make no-voronoi
         make no-USER-AWPMD
         make no-USER-ATC
step5 
make -j 4 intel_cpu_intelmpi
!NOTICE： Maybe when you run step5, it will tell you " Makefile.lammps is not found", that's ok, I just found the file Makefile.lammps is the same as the file Makefile.lammps.empty, so you just copy Makefile.lammps.empty and change the name to Makefile.lammps ,it will go on, and finally reach mu problem.
**Further Information, Files, and Links**

I am really need your help. Thank you and I really appreciate with you.

**Comment by akohlmey** [comment]
This is **not** a bug. this is due to a user error. you didn't follow the installation instructions in the manual properly. when compiling with the traditional make build procedure, you **first** have to compile the missing libraries in the subfolder of the lib folder and copy over or edit the suitable Makefile.lammps. you **must** **NOT** do any "make yes/no" commands in the src folder until all of these steps are correctly done. otherwise the "make yes/no" steps will not correctly integrate the settings to link to the libraries that are provided in the lib folder. in general, it is a good idea to first start a compilation with *NO* packages installed. and then add packages (best without lib first) in steps and verify at ever step that you can still compile successfully.

if this is all to complex and complicated for you, I suggest to try instead compiling with the CMake procedure, which will autodetect many settings. it *also* requires to carefully follow the instructions in the documentation, but it can do more things automatically.

**Comment by sailangyf** [comment]
> This is **not** a bug. this is due to a user error. you didn't follow the installation instructions in the manual properly. when compiling with the traditional make build procedure, you **first** have to compile the missing libraries in the subfolder of the lib folder and copy over or edit the suitable Makefile.lammps. you **must** **NOT** do any "make yes/no" commands in the src folder until all of these steps are correctly done. otherwise the "make yes/no" steps will not correctly integrate the settings to link to the libraries that are provided in the lib folder. in general, it is a good idea to first start a compilation with _NO_ packages installed. and then add packages (best without lib first) in steps and verify at ever step that you can still compile successfully.
> 
> if this is all to complex and complicated for you, I suggest to try instead compiling with the CMake procedure, which will autodetect many settings. it _also_ requires to carefully follow the instructions in the documentation, but it can do more things automatically.

Thank you! I really appreciate with your help!
