### ISSUE TITLE
fmt headers not installed alongside lammps

### ISSUE THREAD

**Issue by snikolov3** [lammps/lammps#2751]
**Summary**

The fmt headers are currently not installed alongside with lammps. This can create issues when using lammps as an external library in other projects (missing fmt headers).

**LAMMPS Version and Platform**

LAMMPS version: 8 Apr 2021
Tested on Power8 node with openmpi/3.1.0/gcc/7.2.0

**Comment by akohlmey** [comment]
The "install" target is currently not officially sanctioned by the LAMMPS developers and was an ad hoc addition done at some point by a contributor that went in mostly unnoticed and unreviewed.

The only sanctioned library interface currently is the `library.h` file and that should work without fmtlib and - in fact - without C++ or MPI even. For the rest the assumption (still) is that one will build applications using LAMMPS as a (C++) library based on the source code distribution. There are some plans to have a suitable and reasonably portable/abstracted "exported" C++ library interface in the future, but there is no timeline on it.

**Comment by akohlmey** [comment]
> I'm having this issue when trying to create a plugin for lammps, to be loaded with the PLUGIN package. Since my plugin defines a new pair style, it needs to include `pair.h`, which includes `pointers.h`, which includes `fmt/format.h` and fails the compilation.
> 
> I can find a workaround by writing more cmake code & linking to a non `make install`ed version of LAMMPS.

as already discussed in this (closed!) issue. The "make install" target is not officially sanctioned. What is there was added to comply with some packaging requirements for some Linux distributions, but it was not reviewed. There are plans to have an "official" LAMMPS API, but for that some significant changes first need to be made to the organization of the LAMMPS header files. those changes are made rather complex by the need to support two different build systems and it is not a high priority item currently.

> As a related question, what is the currently recommended way to write a new pair style for future inclusion in LAMMPS? The possibilities I see are

> * write the code outside of LAMMPS & compile as a plugin

this is likely the easiest approach. You can use the content of the examples/plugins folder as a template for how to set it up.
there are some comments in the CMakeLists.txt file for how you can adapt it. CMake should be given a
 -DLAMMPS_HEADER_DIR=<...> with the path to the LAMMPS source folder.

> * write the code outside of LAMMPS & copy/paste the files inside `lammps/src`. Unfortunately, this does not integrate well with cmake, which I would really prefer to use (my pair style depends on the C++ torch library, which would be a nightmare to integrate without cmake)

since you will need to compile/link an external library, there are some complications.
- your code *must* be a new package. it sounds like a machine learning derived pair style, so it would be a package with a name that starts with ML-
- it must be set up to support both the CMake and the conventional make build system for compiling LAMMPS. there are multiple examples for how to do that. support libraries may be either bundled in a lib subfolder to transparently downloaded during configuration/compilation
- when bundling add-on libraries, the licensing conditions must be carefully observed.

> * write the code inside a custom fork of LAMMPS & force users to use this fork. This might be the best way to do it, but feels a bit heavy

this is up to you. there are advantages and shortcomings to each variant. the plugin package was added to make providing external add-ons easier. but we are in a process of refactoring some of the internal APIs and mechanisms, so you may need to figure out a way to keep up-to-date and support different LAMMPS versions. Having a bundled package or a fork avoids that.

**Comment by Luthaf** [comment]
Ok, thanks a lot for the detailed answer!
