### ISSUE TITLE
[BUG] Segfault when using hybrid pair style and compute group/group

### ISSUE THREAD

**Issue by hmcezar** [lammps/lammps#2752]
**Summary**

When using hybrid pair style with AIREBO and an LJ + Coulomb potential, I get a segmentation fault when computing an interaction energy with compute group/group.

**LAMMPS Version and Platform**

LAMMPS (29 Oct 2020), running in a Core i7 7th gen laptop.
Compilation was performed with the following additional packages:
```
        -DPKG_MANYBODY=yes \
        -DPKG_GRANULAR=yes \
        -DPKG_MOLECULE=yes \
        -DPKG_KSPACE=yes \
        -DPKG_RIGID=yes \
        -DPKG_MC=yes \
        -DPKG_USER-REAXC=yes \
```

**Expected Behavior**

Minimize the energy printing c_pairint.

**Actual Behavior**

Segmentation fault if the "compute group/group" line is uncommented in the attached input.

**Steps to Reproduce**

Make sure the compute group/group lline is uncommented and run LAMMPS.

**Further Information, Files, and Links**

[segfault.zip](https://github.com/lammps/lammps/files/6423877/segfault.zip)

**Comment by rbberger** [comment]
Confirmed on current master

**Comment by rbberger** [comment]
@sjplimp I've narrowed this down a bit for you. `compute group/group` asks for its own neighbor list. The script works when you replace `pair airebo` with `lj/cut`. The problematic issue seems to be that `pair airebo` asks for a list with `ghost=1` and there is another request by someone else that doesn't. 

The segfault happens when `pair airebo` accesses its neighbor list. At that moment, the neighbor list for compute `group/group` has been requested, but not yet constructed (`neighbor->build_one()` was not called yet)

```
#0  LAMMPS_NS::PairAIREBO::REBO_neigh (this=0x7ffff06cb010) at /home/richard/GitHub/lammps/lammps/src/MANYBODY/pair_airebo.cpp:394
#1  0x00007ffff69250ea in LAMMPS_NS::PairAIREBO::compute (this=0x7ffff06cb010, eflag=1, vflag=0)
    at /home/richard/GitHub/lammps/lammps/src/MANYBODY/pair_airebo.cpp:113
#2  0x00007ffff659e5ce in LAMMPS_NS::PairHybrid::compute (this=0x555555825200, eflag=1, vflag=2)
    at /home/richard/GitHub/lammps/lammps/src/pair_hybrid.cpp:133
#3  0x00007ffff64c89de in LAMMPS_NS::Min::setup (this=0x5555555d3ab0, flag=1) at /home/richard/GitHub/lammps/lammps/src/min.cpp:304
#4  0x00007ffff64e3584 in LAMMPS_NS::Minimize::command (this=0x555555825860, narg=4, arg=0x55555582fe60)
    at /home/richard/GitHub/lammps/lammps/src/minimize.cpp:59
#5  0x00007ffff644ed7b in LAMMPS_NS::Input::execute_command (this=0x55555559a9a0) at /home/richard/GitHub/lammps/lammps/src/input.cpp:794
#6  0x00007ffff644bfd8 in LAMMPS_NS::Input::file (this=0x55555559a9a0) at /home/richard/GitHub/lammps/lammps/src/input.cpp:272
#7  0x0000555555555269 in main (argc=3, argv=0x7fffffffdb18) at /home/richard/GitHub/lammps/lammps/src/main.cpp:53
```


If I set `ghost=0` in `pair airebo`, the segfault disappears. In comparison, if I add `ghost=1` to `compute group/group` instead we error out with `Cannot request an occasional binned neighbor list with ghost info`. 

My best guess is something in the neighbor build gets confused by what `pair airebo` asks for if there is another request that doesn't ask for ghosts.

``` 
 (1) pair airebo, perpetual, skip from (4)
      attributes: full, newton on, ghost
      pair build: skip/ghost
      stencil: none
      bin: none
  (2) pair lj/cut/coul/long, perpetual, skip from (5)
      attributes: half, newton on
      pair build: skip
      stencil: none
      bin: none
  (3) compute group/group, occasional, copy from (5)
      attributes: half, newton on
      pair build: copy
      stencil: none
      bin: none
  (4) neighbor class addition, perpetual
      attributes: full, newton on, ghost
      pair build: full/bin/ghost
      stencil: full/ghost/bin/3d
      bin: standard
  (5) neighbor class addition, perpetual
      attributes: half, newton on
      pair build: half/bin/newton
      stencil: half/bin/3d/newton
      bin: standard
```

**Comment by sjplimp** [comment]
Thanks @hmcezar for the test problem.  And thanks @rbberger for the initial analysis.  Just submitted a PR which should fix this issue.
