### ISSUE TITLE
[BUG] in rare cases roundoff makes neighbor list fail to find pairs

### ISSUE THREAD

**Issue by bernstei** [lammps/lammps#2759]
**Summary**

If atom initial positions are outside the [0..1] scaled coordinate range, LAMMPS's wrapping can break the symmetry between local and ghost atom pairs, and that makes the neighbor lists's spatial ordering reject both times it checks the pair of atoms that should be neighbors.  See also more detailed discussion at [this matsci.org thread](https://matsci.org/t/apparently-inconsistent-forces-before-after-dump/36305/28).

**LAMMPS Version and Platform**

`LAMMPS (8 Apr 2021)`

CentOS 7 on an Intel CPU, gcc 10.3.0, compiled with -O0 or -O1.  It also appears to be the same for gcc 7.3.

**Expected Behavior**

When running attached input script, a neighbor list containing one pair of atoms (i.e. output contains `Total # of neighbors = 1`)

**Actual Behavior**

output contains `Total # of neighbors = 0`

**Steps to Reproduce**

`lmp_serial -in two_atoms.in | grep 'Total # of neigh'`

**Further Information, Files, and Links**

[two_atoms.in.gz](https://github.com/lammps/lammps/files/6444471/two_atoms.in.gz)

**Comment by sjplimp** [comment]
@bernstei Can you explain the geometry for where these 2 atoms are wrt the prism box?  I'm not clear on why there are 14 ghost atoms when I run on one proc.  Is each of the in-the-box atoms a neighbor of the other in a ghost sense?  I think the problem is that the neigh alg for triclinic relies on the (inbox 1, ghost 2) pair having consistent coords with the (inbox 2, ghost 1) pair.  In the sense of one atom being above/below the other in some dim.  And the box coords --> lamda coords transformation can mess that up by epsilon due the complexity of the math and the fact that all 3 coord dims are coupled together.  Unlike for orthogonal boxes.

**Comment by bernstei** [comment]
I think you're right about the problem.  As for where they are, I'd have to pop them in in some visualizer.  They are interacting across some periodic boundary, yes.  Do you really have 14 ghost atoms?  I recall one ending up with 8 images, and the other with 4, so a total of 12 local+ghost.  But I'm not sure of this - I'll have to check.

**Comment by sjplimp** [comment]
~7 images/atom is fine.  I was just surprised b/c the cutoff was so short and the tilt does not seem extreme.  Mabye this is b/c each atoms are in one of the corners of the prism?

**Comment by bernstei** [comment]
Here is a view (approximately) along y, with z pointing up. Both atoms are on the close face which is approximately in the x-z plane.  The bond halves point across the PBCs.
![lammps_neigh_list](https://user-images.githubusercontent.com/1202357/118489317-b201d880-b6ea-11eb-860f-e0b71a85f646.png)

**Comment by bernstei** [comment]
@sjplimp Any ideas on how to fix this issue?

**Comment by sjplimp** [comment]
Sorry @bernstei - haven't picked this up again, and am now busy for the LAMMPS workshop.  Will try to look at it again afterwards.

**Comment by bernstei** [comment]
Thanks.  By the way, one observation that might make things more complicated (or less) is that I created a test for this issue in ASE's lammpslib, to see if the workaround I implemented there is still working, and on a different (although very similar architecture) machine running their CI tests the workaround behaves differently [(here)](https://gitlab.com/ase/ase/-/merge_requests/2463#note_632532820).  I'm pretty sure that on this new test machine the workaround does not work, i.e, the issue is _more_ robust than expected.  I have no easy way to figure out why (we'd have to add debugging info to the lammps copy they use in the CI docker image), but it suggests that there may be more hardware architecture dependence than I expected, even though in this case it's making the bug appear more easily.

**Comment by DallasTrinkle** [comment]
Has there been any movement on this? We just encountered this pretty severely when running a primitive FCC supercell generated through ASE, where we could make a supercell with differences of 10^-15 in the box dimensions, and would get energy errors of ~0.2eV, along with several atoms experiencing different forces. The box was larger than the cutoffs as well. By periodically repeating it into an orthogonal "simple cubic" supercell, we could verify which energy was correct, but this is a very surprising result, and rather unexpected bug. We can provide additional test cases if it will help, but this is very much still "in the wild." Thanks

**Comment by sjplimp** [comment]
@DallasTrinkle when you say FCC supercell do you mean a triclinic box in LAMMPS? My 5/14/2021 comment was my best guess as to what is causing the problem, i.e. a neighbor pair I,J gone missing in the triclinic neighbor build due to round-off issues in the conversion to triclinic coords.  Does that explanation match the problem you are reporting now?  If you have a simple example(s) that illustrate the problem, that could be helpful.  My hazy recollection is that the example of @bernstei was subtle and hard to reproduce, as he indicated, e.g. different behavior on different machines.

**Comment by bernstei** [comment]
Any problem that has to do with roundoff is going to be compiler/optimization dependent (and possibly machine, although hardware level ops are pretty consistent now).

**Comment by DallasTrinkle** [comment]
Yes, this regards a triclinic box for an FCC primitive cell (this is the same type of cell that @bernstei is using). My student used ASE to generate the datafile to be read into LAMMPS, and it's a rotated cell with original vectors 8 a0[0,1/2,1/2] x 8 a0[1/2,0,1/2] x 8 a0 [1/2,1/2,0]. This requires the tilts to be just at 1/2 of the X and Y lengths. This is for a vacancy in a high entropy alloy. He recently reran the ASE generation code with a later version of numpy, and in generated a "new" version with a slightly different box, differing at the 10^-15 level:

```
511 	 atoms 
5  atom types
0.0      20.336391026925106  xlo xhi
0.0      17.611831250611051  ylo yhi
0.0      16.604593741893638  zlo zhi
     10.168195513462551      10.168195513462551      5.8706104168703526  xy xz yz
```
vs.
```
511 	 atoms 
5  atom types
0.0       20.33639102692511  xlo xhi
0.0      17.611831250611047  ylo yhi
0.0      16.604593741893638  zlo zhi
     10.168195513462551      10.168195513462551      5.8706104168703437  xy xz yz
```
This small difference appears to come from ASE's linear algebra routine to rotate the supercell to fit LAMMPS convention. 
The atomic positions were also different at the 10^-15 level. All of that said, I would expect the energies (and forces) for these two cells to differ by not much more than 10^-12 eV or so. When we run these two cells, we get different energies at the ~0.25eV level, and several atoms have different forces between the two cells, at the up to ~30 meV/A level; the atoms with different energies are clustered in a particular section of the supercell.

We've tried replacing all of the atomic coordinates, so that the only difference between the two files really is the supercell descriptions, and the errors persist. I took the cells and made 4x larger orthorhombic supercells, and confirmed that the energy from the second one is correct; I get this whether I use the first set of lattice vectors and positions or the second to construct the orthorhombic cells. It's reproducible across at least two machines we've tried, so you can introduce this roundoff sensitivity artificially by adding in small differences in the periodic box; I think this is where the "compiler sensitivity" and ASE came from.

I realize this is not yet a smallest reproducible example. The cutoff for the MEAM potential we're using is 6.5A, and for this triclinic cell, the shortest distance between planes would be 20.3364*sqrt(2/3) = 16.6 A, which is above 2 Rcut.

**Comment by DallasTrinkle** [comment]
I just confirmed that you can take @bernstei's example above, and if you decrease the XHI, YHI, and ZHI values by 1e-12, then LAMMPS will find the NN pair.

**Comment by bernstei** [comment]
The matsci.org thread explains in quite some detail what goes wrong, I thought.

**Comment by DallasTrinkle** [comment]
I agree with your very thorough analysis @bernstei; it would be good to get this fixed, as it is still happening in the current stable release candidate. As your thread showed, it doesn't require atoms to initially be outside of the original supercell (as we found as well).

**Comment by sjplimp** [comment]
@DallasTrinkle @bernstei Can you check if setting "newton off" in your LAMMPS script makes this problem go away?  That is not the default, but it does use a different neighbor-finding method which doesn't depend on consistent atom coords during the triclinic <-> orthogonal transformations (I think).  Hence it would be helpful in debugging the "newton on" problem.  And it would be a work-around for you until the bug is fixed.  I will look into it.

**Comment by sjplimp** [comment]
Also I think "neighbor skin nsq" should work (instead of bin) for newton on or off.   So long as the cutoff is smaller than the box size.

**Comment by DallasTrinkle** [comment]
@sjplimp The `newton off` option makes this go away for the LJ example. For my own example, I can't use it, as I'm using MEAM and I get an error that newton on is required. If I used `neighbor 2.0 nsq`, that also makes this go away for the LJ example but doesn't change my MEAM calculation... rather odd.

**Comment by sjplimp** [comment]
Thanks for the info.  For Nsq and MEAM can you post the "Neighbor list info:" from the logfile? I want to see which
pair build and stencil options are used.  Or if you have them, post your LAMMPS-only input/output files - I don't see them in this issue?

**Comment by sjplimp** [comment]
@bernstei @DallasTrinkle Please see PR #3846 which is my initial attempt to fix this issue.  It would be helpful if you could run your failing tests in 5 modes:

1-2) newton on and off with a binned neighbor list
3-4) newton on and off with a Nsq neighbor list
5) also all of these variants in serial and parallel, even for small systems

If there are still energy/force discrepancies, then also look at the end of the logfile output which gives counts of the number
of neighbor list pairs.  Hopefully any simulation that is "wrong" will have a different count.

You can report the results in that PR and we can iterate there.  Thanks for your help!

**Comment by sjplimp** [comment]
Note that it is normal for newton on versus off simulations to have different neighbor counts.

**Comment by DallasTrinkle** [comment]
I have some results, but they're a bit strange. I'll do my best to summarize:
1. The PR fixes the two-atom example given by @bernstei , out of the box. It works with newton on and off and NSQ as well.
2. It does *not* fix my MEAM FCC 8 x 8 x 8 example, with or without NSQ. I can't switch newton off for MEAM. But the forces and energies are the same with or without NSQ, and they still disagree between two slightly different periodic cells.
3. I decided to rerun the FCC 8 x 8 x 8 supercell treating everything as a single species with LJ, and the same cutoff range for the NN search (6.5A), and the PR still shows different forces between the two cells. However, once I use either NSQ or switch off newton, those agree, but they now they *disagree* with what I get using binning.

This is all serial, in g++, on my intel MacBook pro. I can make tarballs of the runs, including the log.lammps files, if that will be useful.

**Comment by sjplimp** [comment]
@DallasTrinkle thanks for doing these tests.  Yes, please post tarballs for the 3 cases.

**Comment by sjplimp** [comment]
For case #3 does the neighbor count agree for binned (incorrect?) vs NSQ (correct?) ?  Also, I am unclear on what you mean by 2 slightly different periodic cells.

**Comment by DallasTrinkle** [comment]
Here is a tarball for the FCC MEAM case; it has all of the inputs as well as the four log files. The lattice vectors for the two data files are identical; the only difference is in the positions, which differ at the 10^-14 - 10^-15 level. I'll separately put together the tarball for the LJ case.

For the MEAM case, the neighbor counts are:
```
log.lammps-found-bin:Neighs:          21930 ave       21930 max       21930 min
log.lammps-found-nsq:Neighs:          21930 ave       21930 max       21930 min
log.lammps-missing-bin:Neighs:          21929 ave       21929 max       21929 min
log.lammps-missing-nsq:Neighs:          21929 ave       21929 max       21929 min
```

[PBC-MEAM.tar.gz](https://github.com/lammps/lammps/files/11987067/PBC-MEAM.tar.gz)

**Comment by DallasTrinkle** [comment]
Here is the LJ case. The neighbor counts are:
```
log.lammps-found-bin:Neighs:          13943 ave       13943 max       13943 min
log.lammps-found-nsq:Neighs:          21930 ave       21930 max       21930 min
log.lammps-missing-bin:Neighs:          13903 ave       13903 max       13903 min
log.lammps-missing-nsq:Neighs:          21930 ave       21930 max       21930 min
```
All of these are `newton on`. The Epair values are also different:
```
log.lammps-found-bin:    -2058.2077
log.lammps-found-nsq:    -2603.741    
log.lammps-missing-bin:  -2056.3062      
log.lammps-missing-nsq:  -2603.741  
```

[PBC-LJ.tar.gz](https://github.com/lammps/lammps/files/11987075/PBC-LJ.tar.gz)

**Comment by sjplimp** [comment]
ok - @DallasTrinkle @bernstei I think the current version of the PR runs all 3 of your examples correctly.
This is the 2-atom LJ (Noam), and the 511-atom MEAM and 511-atom LJ with 2 sets of coords for each (Dallas).  
I tested on a single proc for bin/nsq and newton on/off.  They all give the same answers now modulo machine-precision round-offs.

If you want to verify this with your own runs/macines or any other test cases you have, that would be great.
Thanks for providing all the test cases - they were very helpful, since the bug was subtle and rare (I think).

**Comment by DallasTrinkle** [comment]
Thanks so much for this--I just reran my test cases, and they are all working correctly now. I really appreciate your help getting this fixed.
