### ISSUE TITLE
[BUG]  LAMMPS fix wall/gran command wall damping is not as expected.

### ISSUE THREAD

**Issue by vikaskok** [lammps/lammps#2812]
**Summary**

Using the pair_style granular damping mass velocity command in conjunction with fix wall gran command is not giving expected results.
Please see attached pdf for elaborate description.

**LAMMPS Version and Platform**
LAMMPS (14 May 2021)
MacOS 11.4

**Expected Behavior**
Using damping coefficient gamma corresponding to a certain coefficient of restitution is not resulting in appropriate/expected damping behaviour.

**Actual Behavior**
Coefficient of restitution can be obtained from simulation via a grain which bounces off the walls. This is not in line with what is expected from the wall damping coefficient.

**Steps to Reproduce**
Attached input script replicates the issue.
The accompanying pdf document contains further details.
Create 'dumppositions' directory before running the script so that dump files are generated in this directory.

**Further Information, Files, and Links**
Granular flow down an inclined plane: Bagnold scaling and rheology
Leonardo E. Silbert, Deniz Ertas¸, Gary S. Grest, Thomas C. Halsey, Dov Levine,
[inputfile.txt](https://github.com/lammps/lammps/files/6721852/inputfile.txt)
[fix_wall_gran_issue_pairstyle.pdf](https://github.com/lammps/lammps/files/6721857/fix_wall_gran_issue_pairstyle.pdf)
 and Steven J. Plimpton
PRE(2001)

**Comment by dsbolin** [comment]
@vikaskok Thanks for the detailed description. However, I'm not sure there is a bug here. I believe the expression relating damping coefficient to coefficient of restitution that you cite (from Silbert et al) is only meant to apply to particle-particle collisions, when `m_i` and `m_j` are both finite. I don't think you can simply apply the same expression to particle-wall collisions by setting e.g. `m_j --> \infty`. I think you'll have to work through the damped harmonic oscillator solution to see where the issue is, and what the correct relation between damping coefficient and restitution coefficient is for particle-wall collisions. I couldn't find it from a quick literature search, but I'm sure it's published somewhere, and can be fairly easily worked out from the damped harmonic oscillator solution. I'm interested in what you find, let me know if I can be of any help.

**Comment by vikaskok** [comment]
@dsbolin 

Thank you for looking into the issue and for your kind suggestion to rework the $\gamma$ expression for wall.
I will definitely do that.

I have investigated the issue further and the following are my findings:
To construct the walls, instead of the pair_style granular contact model, if we use the old gran hooke model, we will see expected behaviour.
I am attaching a slightly updated input script. The bottom wall is constructed in two ways - using new pair_style granular command and old gran hooke command. Both of them use same kn,gamma values. 

In the attached input script, you can comment/uncomment one of the bottom walls to investigate.

For the case of walls constructed with old gran hooke command:
A ball dropped with |v|=1 on the wall bounces back with expected velocity (v_rebound = coeff_resti_wall * initial_velocity). And this can be checked for various gamma (i.e. coeff_resti_wall) values. 

This behaviour is not replicated by new pair_style granular (hooke, damping mass_velocity). 

Hence I believe that the way I calculate 'gamma' using meff=mass of colliding particle should not be an issue since old gran/hooke is giving expected results for the gamma value calculated in this manner.

I have also realised that I did not attach the file read by the read_data command last time. My apologies for that. I am attaching it here.

Thank you.

[grains.txt](https://github.com/lammps/lammps/files/6795545/grains.txt)
[in.wallcheck.txt](https://github.com/lammps/lammps/files/6795546/in.wallcheck.txt)

**Comment by dsbolin** [comment]
@vikaskok Thanks for the additional details, I suspect you are correct that there is a bug, the granular pair style with hooke option should give the same results as gran/hooke. I am currently on vacation, but will plan to look at this in the next week or so.

**Comment by dsbolin** [comment]
@vikaskok  I tried your input script, and I'm actually getting identical result with hooke (old style) and granular + hooke option (new style). See attached input script, slightly modified to output particle velocities to the log file for convenience. I ran this with LAMMPS version 10-Mar-21, also attaching log files for two options, showing identical velocities. Can you test and let me know if somehow you are seeing different log file outputs for the two wall style options?
[in.wallcheck.txt](https://github.com/lammps/lammps/files/6849995/in.wallcheck.txt)
[new_style.log](https://github.com/lammps/lammps/files/6849996/new_style.log)
[old_style.log](https://github.com/lammps/lammps/files/6849997/old_style.log)

Thanks!

**Comment by vikaskok** [comment]
@dsbolin 

Thank you for checking and for the updated, more convenient input file.

I have tested with LAMMPS version 14-May-21 and LAMMPS version 10-Mar-21.
As observed by you,  using LAMMPS version 10-Mar-21 wall behaviour is correct/as expected with hooke (old style) as well as granular + hooke option (new style).

However, LAMMPS version 14-May-21 wall behaviour for granular + hooke option (new style) seems erroneous. 

I am attaching 4 log files.
LAMMPS version 10-Mar-21.: old style wall 
LAMMPS version 10-Mar-21.: new granular style wall
LAMMPS version 14-May-21.: old style wall 
LAMMPS version 14-May-21.: new granular style wall -- <bug here>

Thank you.

[log_new_granular_style_LAMMPS_10march2021.log](https://github.com/lammps/lammps/files/6850317/log_new_granular_style_LAMMPS_10march2021.log)
[log_new_granular_style_LAMMPS_14may2021.log](https://github.com/lammps/lammps/files/6850319/log_new_granular_style_LAMMPS_14may2021.log)
[log_oldwallgran_LAMMPS_10march2021.log](https://github.com/lammps/lammps/files/6850320/log_oldwallgran_LAMMPS_10march2021.log)
[log_oldwallgran_LAMMPS_14may2021.log](https://github.com/lammps/lammps/files/6850321/log_oldwallgran_LAMMPS_14may2021.log)

**Comment by dsbolin** [comment]
@vikaskok Thanks for your patience and help tracking this down! There is indeed a bug, disregard my earlier comments. The issue is that this line:
https://github.com/lammps/lammps/blob/b7334fc688bdfee93af40e5b8ae045a81c742e4a/src/GRANULAR/fix_wall_gran.cpp#L1196
Should read:
`if (normal_model != NORMAL_HOOKE) {`

With the current code, the effect is that  `granular + hooke` effectively behaves like `granular + hertz` within `fix wall/gran`

@akohlmey Would it be easiest for me to email you a patch for this, or create a PR?

**Comment by akohlmey** [comment]
@dsbolin I can easily add this one liner to an existing branch of mine.
