### ISSUE TITLE
[BUG] LAMMPS with zstd support does not compile on some Linux distributions with default libraries and traditional make

### ISSUE THREAD

**Issue by mkanski** [lammps/lammps#2820]
**Summary**

Compiling LAMMPS with zstd compression support fails, because the library bundled with some Linux distributions is too old.

**LAMMPS Version and Platform**

Current master, Linux Mint 19.3 (Tricia)

**Expected Behavior**

The minimal version of the zstd library should be mentioned in the manual or source files.

**Actual Behavior**

Compilation fails, because functions in `src/COMPRESS/zstd_file_writer.cpp` use features not available in the library bundled with Linux.

**Steps to Reproduce**

1. Install zstd library: `sudo apt install libzstd-dev`
2. Modify a makefile by including `-DLAMMPS_ZSTD`
3. Try to compile LAMMPS.

**Further Information, Files, and Links**

EDIT: I tried compiling with cmake instead of make and there is a version requirement, so this issue only exists for traditional make.

**Comment by akohlmey** [comment]
since the traditional make procedure cannot not auto-detect compatible versions, it is the responsibility of the user compiling LAMMPS to make certain that a compatible version of the zstd library is used. However, the documentation did not state the minimum requirement (version 1.4) and a "protection" in the source code could check for a version number and provide a suitable error message early during compilation. I have added those to PR #2826

**Comment by junghans** [comment]
We could do the v1.4 detection with `pkg-config` in the Makefile, similar to what we do in `lib/kim/Makefile.lammps`.
