### ISSUE TITLE
[Feature Request] Request extension of the ScaFaCoS package to simulations involving charged molecules

### ISSUE THREAD

**Issue by nf-vthakore** [lammps/lammps#2884]
**Extension of the ScaFaCoS package to simulations involving charged molecules**

**Detailed Description**

Currently in LAMMPS, the only option for Coulombic interactions between charged molecules for fully non-periodic or mixed periodic boundary conditions is the Multilevel Summation Method (MSM) while Particle-Particle Particle-Mesh (PPPM) allows for non-periodicity in one dimension only. The MSM algorithm is painfully slow and therefore there exists a need to include, develop or extend faster Coulombic solvers for modeling charged molecular molecular systems with fully non-periodic and mixed periodic boundary conditions. The ScaFaCoS package in LAMMPS with its options for various fast Coulombic solvers can fill/bridge this gap if extended to modeling of charged molecular systems. This would spur modeling and simulation of a whole host of nanoscale sensors and actuator devices that make use of charged interactions between molecules, ions and surfaces.

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
Given the fact that the scafacos kspace style wants to process **all** coulomb interactions while most LAMMPS pair styles are set up to do the real-space part of the full coulomb and then only do the reciprocal space contribution in the kspace style, it is a tall order to ask for integrating support for molecular systems. People would have to process all data about exclusions and forward it from LAMMPS to the ScaFaCoS library assuming that a facility for this kind of processing already exists. Otherwise that would have to be implemented as well.

What would probably be easier to implement, and what would not require any changes to the SCFACOS package (except for augmenting the checks for molecular systems) would be to implement a coul/exclude pair style that would *only* compute coulomb interactions for excluded pairs (according to the scale factor) and then **subtract** instead of add either the full or partially excluded force and energy contributions. Then this could be used via pair style hybrid/overlay in combination with a LJ-only pair style for the LJ part of the force field. One could start with pair style coul/cut and then more-or-less invert the logic of how exclusions are handled vs. the non-bonded coulomb pairs.

**Comment by stanmoore1** [comment]
The SCFACOS package in LAMMPS includes the Fast Multipole Method (FMM) and Particle-Particle NFFT (PN2FFT) methods which support both non-periodic and partially-periodic BCs. Since SCFACOS also handles the short-range calculations, @akohlmey has a good suggestion on adding a new pair style to subtract out the excluded interactions, which should be short-ranged and fast.

**Comment by akohlmey** [comment]
A proof-of-concept [implementation](https://github.com/lammps/lammps/compare/master...akohlmey:pair-coul-exclude) can be found in this branch https://github.com/akohlmey/lammps/tree/pair-coul-exclude

**Comment by nf-vthakore** [comment]
Many thanks to Axel and everyone else involved for incorporating this feature request into LAMMPS with such amazing speed. 

Now that this is out in the latest patch release, I will check it out in the coming days and months and let you know how it performs and any other issues, if I encounter any. 

This is a feature that is bound to be of great interest to  the LAMMPS User Community at large as well.

Ever grateful,
Vaibhav.
