### ISSUE TITLE
[BUG] wonky hybrid/scaled energies with coul/cut/global

### ISSUE THREAD

**Issue by GarrettTow** [lammps/lammps#2901]
**Summary**

When using hybrid/scaled with coul/cut/global to attempt to subtract off the real space electrostatics from lj/cut/coul/long the reported ecoul energy is different than the expected value.

**LAMMPS Version and Platform**

LAMMPS version 30Jul2021
Compilation: Intel oneAPI 2021.1.1 and cray-mpich 8.1.5
SUSE Linux Enterprise Server 15 SP2 Release 15.2
CPU: AMD Epyc 7H12

**Expected Behavior**

I expect for the real space Coulombic energy to be zero when using full strength lj/cut/coul/long and using coul/cut/global with a -1.0 scale factor via hybrid/scaled.

**Actual Behavior**

The magnitude of the real space Coulombic energy is 9.6 times larger instead of being zero, when compared to the real space Coulombic energy from using the standard lj/cut/coul/long pair style by itself.

**Steps to Reproduce**

Basic input file that generates charged LJ particles and cycles through different pair style combinations with run 0 commands to see how the printed energy terms are affected:

****************************************
units real
atom_style charge
lattice bcc 4.0
region unitcell block 0 1 0 1 0 1
create_box 2 unitcell
create_atoms 1 box
set atom 2 type 2
set type 1 charge -1.0
set type 2 charge 1.0
mass * 30.0
replicate 8 8 8
pair_style hybrid/scaled 1.0 lj/cut/coul/long 15.0 15.0 -1.0 lj/cut/coul/long 15.0 15.0
kspace_style pppm 1.0e-5
pair_coeff * * lj/cut/coul/long 1 0.1 3.5
pair_coeff * * lj/cut/coul/long 2 0.1 3.5
thermo_style custom step pe evdwl ecoul elong
run 0

pair_style hybrid/scaled 1.0 lj/cut/coul/long 15.0 15.0 -1.0 coul/long 15.0
kspace_style pppm 1.0e-5
pair_coeff * * lj/cut/coul/long 0.1 3.5
pair_coeff * * coul/long
run 0

pair_style hybrid/scaled 1.0 lj/cut/coul/long 15.0 15.0 -1.0 coul/cut/global 15.0
kspace_style pppm 1.0e-5
pair_coeff * * lj/cut/coul/long 0.1 3.5
pair_coeff * * coul/cut/global
run 0

pair_style lj/cut/coul/long 15.0 15.0
kspace_style pppm 1.0e-5
pair_coeff * * 0.1 3.5
run 0
****************************************

The output of the four different pair style combinations:
| Pair | PotEng     | E_vdwl     | E_coul     | E_long     |
|------|------------|------------|------------|------------|
| (1)  | -39705.875 | 0          | 0          | -39705.875 |
| (2)  | -40249.025 | -543.14929 | 0          | -39705.875 |
| (3)  | -489538.35 | -543.14929 | -449289.33 | -39705.875 |
| (4)  | -87049.531 | -543.14929 | -46800.507 | -39705.875 |

(1) pair_style hybrid/scaled 1.0 lj/cut/coul/long 15.0 15.0 -1.0 lj/cut/coul/long 15.0 15.0
(2) pair_style hybrid/scaled 1.0 lj/cut/coul/long 15.0 15.0 -1.0 coul/long 15.0
(3) pair_style hybrid/scaled 1.0 lj/cut/coul/long 15.0 15.0 -1.0 coul/cut/global 15.0
(4) pair_style lj/cut/coul/long 15.0 15.0

Looking at E_coul of pair_style (3), the magnitude of the value is 9.6 times larger than the E_coul value for pair_style (4).

**Further Information, Files, and Links**

This issue was previously discussed here: https://sourceforge.net/p/lammps/mailman/lammps-users/thread/CADTmJ6ELjiaUbvv8dCENyHPFv%3DLX2-YqMb0XoMscZ594amUwuA%40mail.gmail.com/#msg37259219

**Comment by akohlmey** [comment]
First off, for `coul/long` one always has to look at the sum of ecoul and elong. The real space part is damped with an erfc() function and thus missing interactions that are included in elong. For a cutoff coulomb, however, contributions are counted in **full** and only in realspace. If you reduce the damping, i.e. increase the cutoff, the coulomb contribution in coul/long should become more similar to that of coul/cut. However, due to the 1/r nature of the coulomb potential, you have to go to insanely large cutoffs to get to values where coul/cut and coul/long should become very similar.

There is a second property of coulomb interactions that make this comparison difficult. The coulomb energy is a "conditionally convergent" sum. If you have somewhat ordered system with alternating charges (e.g. a bulk water system or a crystal) then the sum of the coulomb energy will oscillate by a large amount and not converge well. This is because if you increase the cutoff you will at some point  include a whole bunch of charges that are either predominantly negative or positive. This will be repetitive once the cutoff becomes larger than the replicated unit cell. Since the "surface" of the cutoff sphere grows quadratically with the cutoff the amount of charge difference will not easily die down as you have many more charges in each oscillation while the interaction will decrease linearly as 1/r.  So if you look at the value of ecoul+elong for different cutoffs it should oscillate by some margin around zero and but persist for very long cutoff radii.

So I don't see a reason why this would result in a zero value for ecoul. I just did some tests and the behavior I see looks reasonable and what I expect.

The easiest way to debug if there was some issue with the scaling factors would be to just use the same pair style twice or use pair style table with a proper table created with pair write (it is a bit tricky for coulomb but not too much, if you read the docs carefully) or compare with pair style python (to be certain that you have different implementations). with pair styles table or python you could also negate the interaction in the table or python code and then compare the results with pair style hybrid/overlay instead of hybrid/scaled.

**Comment by GarrettTow** [comment]
Hi Axel,

Thank you for the crystal clear explanation. I ran additional tests with only the real space electrostatic pair styles:
| Pair | PotEng    | E_vdwl | E_coul    | E_long |
|------|-----------|--------|-----------|--------|
| (5)  | 402488.82 | 0      | 402488.82 | 0      |
| (6)  | 0         | 0      | 0         | 0      |

(5) pair_style coul/cut 15.0
(6) pair_style hybrid/scaled 1.0 coul/cut 15.0 -1.0 coul/cut/global 15.0

I see that it is working as intended. When I first saw such a large potential energy difference for pair style (3) in the original post, I assumed something was wrong. Your explanation is clear on why this large energy difference is possible.
