### ISSUE TITLE
Unable to execute

### ISSUE THREAD

**Issue by debanjansen48** [lammps/lammps#2945]
after installation in the Linuxmint 19.3  it returns

(base) debanjan@debanjan:~/.local/bin$ whereis lmp
lmp: /home/debanjan/.local/bin/lmp
(base) debanjan@debanjan:~/.local/bin$ lmp
lmp: error while loading shared libraries: libhdf5.so.103: cannot open shared object file: No such file or directory

**Comment by akohlmey** [comment]
This is not a LAMMPS issue, but a user error. You have apparently compiled LAMMPS with features using the HDF5 libraries (e.g. by installing the NETCDF or H5MD or both) but now do not have the corresponding runtime libraries available (e.g. by setting LD_LIBRARY_PATH accordingly or loading the corresponding environment module). You have to refer to the corresponding documentation or consult with people more experienced on using/managing the kind of Linux system you have in order to learn how to properly resolve this. There is nothing on the LAMMPS side that is wrong.

**Comment by debanjansen48** [comment]
ohh..ok

Thanks..issue resolved
