### ISSUE TITLE
[BUG] LATTE.cmake yielding undefined reference... when building with MKL

### ISSUE THREAD

**Issue by yoonbo** [lammps/lammps#2964]
**Summary**

When building LAMMPS with LATTE and MKL, the build command gives "undefined reference to `mkl_...'" error messages during the linking LATTE.

In the cmake options for LATTE in
  `lammps/cmake/Modules/Packages/LATTE.cmake`
LAMMPS passes the BLAS and LAPACK libraries to LATTE as following
  `-DBLAS_LIBRARIES=${BLAS_LIBRARIES} -DLAPACK_LIBRARIES=${LAPACK_LIBRARIES}`
where ${BLAS_LIBRARIES} and ${LAPACK_LIBRARIES} are lists of multiple ".so" files and link options such as -lm, separated by spaces.
During the LATTE link procedure, the linker takes only the first element in the list as the relevant library.
For example, if
  `-DBLAS_LIBRARIES=libmkl_intel_lp64.so libmkl_intel_thread.so libmkl_core.so libiomp5.so -lm -ldl -lm -ldl`
LATTE links only with "libmkl_intel_lp64.so".
As a result, it gives "undefined reference" errors for the functions defined in other libraries, such as libmkl_core.so.

**LAMMPS Version and Platform**

The current master branch of LAMMPS. 

**Expected Behavior**

Build completion without error.

**Actual Behavior**

Build failure with the following error messages:
```
libmkl_intel_lp64.so: undefined reference to `mkl_lapack_zgemlqt'
libmkl_intel_lp64.so: undefined reference to `mkl_spblas_lp64_mkl_zcsrcsc'
libmkl_intel_lp64.so: undefined reference to `mkl_graph_descriptor_destroy_internal'
libmkl_intel_lp64.so: undefined reference to `mkl_spblas_lp64_mkl_scscsm'
...
```

**Steps to Reproduce**

I tested the build only on LANL Kodiak cluster.

```
git clone https://github.com/lammps/lammps.git
mkdir build
cd build

module purge
module load cmake python intel/19.1.3 intel-mpi/2019.9.304 mkl/2020.0.4

CC=mpiicc CXX=mpiicpc \
cmake ../lammps/cmake \
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
  -DBUILD_MPI=ON \
  -DBUILD_OMP=ON \
  -DPKG_LATTE=ON
```

**Further Information, Files, and Links**

Attached are the cmake and make logs.

[make.log](https://github.com/lammps/lammps/files/7247093/make.log)
[cmake.log](https://github.com/lammps/lammps/files/7247094/cmake.log)

**Comment by akohlmey** [comment]
@yoonbo This is exposing a known flaw in CMake for which I have not yet seen a satisfactory solution. The passing of flags like the BLAS library currently only works for a single argument. There is nothing that we can currently do about it without significantly changing how LATTE is built as part of LAMMPS (which may be required for other reasons). Not sure when this will happen.

The suggestion for your specific case would be to download and compile/install LATTE separately and then point LAMMPS to the location of that installation instead of having LATTE being download and built as part of LAMMPS.

**Comment by akohlmey** [comment]
@yoonbo I am adding an explicit error message to the CMake scripts to signal when this limitation is reached. That is all we can do for now. But those tests will serve as a reminder to revisit this issue at a later point, probably when the changes in PR #2940 are going to be propagated to all packages, if possible, to support "multi-config" build systems.

**Comment by junghans** [comment]
Now as I look at this more closely, I think the problem are the spaces, handing over a list should be ok. I think we could call `separate_arguments(BLAS_LIBRARIES)` to turn `BLAS_LIBRARIES` from a string into a list.

**Comment by akohlmey** [comment]
> Now as I look at this more closely, I think the problem are the spaces, handing over a list should be ok. I think we could call `separate_arguments(BLAS_LIBRARIES)` to turn `BLAS_LIBRARIES` from a string into a list.

ExternalProgram_add() **does** that kind of conversion and that is the problem. I have tried many things and could not find a solution outside of what is done in PR #2940. We will need to do this anyway, since there also is no way to pass the selected configuration to the external project in a multi-config build system.

**Comment by junghans** [comment]
Thanks. Yeah, that is unfortunate, ultimately we might should just use spack or something.

**Comment by junghans** [comment]
@yoonbo actually
```bash
spack install lammps+latte
```
should actually do it.
