### ISSUE TITLE
[BUG] some tests fail on armv7hl

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#2978]
When packaging lammps patch_29Sep2021 on Fedora, the following test fails on armv7hl

```
The following tests FAILED:
        104 - MolPairStyle:hybrid-scaled (Failed)
        204 - AtomicPairStyle:buck_coul_cut_qeq_point (Failed)
        205 - AtomicPairStyle:buck_coul_cut_qeq_shielded (Failed)
        222 - AtomicPairStyle:edip (Failed)
        231 - AtomicPairStyle:meam_sw_spline (Failed)
        234 - AtomicPairStyle:reaxff (Failed)
        235 - AtomicPairStyle:reaxff_lgvdw (Failed)
        236 - AtomicPairStyle:reaxff_noqeq (Failed)
        237 - AtomicPairStyle:reaxff_tabulate (Failed)
```

Build log [build_armv7.txt.zip](https://github.com/lammps/lammps/files/7270409/build_armv7.txt.zip)

https://koji.fedoraproject.org/koji/taskinfo?taskID=76577424

**Comment by junghans** [comment]
Similar on s390x
```
The following tests FAILED:
	 74 - MolPairStyle:buck_table_coul_off (Failed)
	173 - MolPairStyle:lj_table_coul_off (Failed)
	189 - MolPairStyle:soft (Failed)
	204 - AtomicPairStyle:buck_coul_cut_qeq_point (Failed)
	205 - AtomicPairStyle:buck_coul_cut_qeq_shielded (Failed)
	222 - AtomicPairStyle:edip (Failed)
	227 - AtomicPairStyle:kim_lj (Failed)
	231 - AtomicPairStyle:meam_sw_spline (Failed)
	234 - AtomicPairStyle:reaxff (Failed)
	235 - AtomicPairStyle:reaxff_lgvdw (Failed)
	236 - AtomicPairStyle:reaxff_noqeq (Failed)
	237 - AtomicPairStyle:reaxff_tabulate (Failed)
	248 - ManybodyPairStyle:bop_save (Failed)
	251 - ManybodyPairStyle:drip (Failed)
	252 - ManybodyPairStyle:drip_real (Failed)
	257 - ManybodyPairStyle:ilp-graphene-hbn (Failed)
	258 - ManybodyPairStyle:ilp-graphene-hbn_notaper (Failed)
	259 - ManybodyPairStyle:kolmogorov_crespi_full (Failed)
	263 - ManybodyPairStyle:lebedeva_z (Failed)
	264 - ManybodyPairStyle:meam (Failed)
	269 - ManybodyPairStyle:mliap_so3 (Failed)
	276 - ManybodyPairStyle:rann (Failed)
	385 - FixTimestep:momentum (Failed)
	457 - DihedralStyle:quadratic (Failed)
	459 - DihedralStyle:table_cut_linear (Failed)
	461 - DihedralStyle:table_linear (Failed)
Errors while running CTest
```

https://koji.fedoraproject.org/koji/taskinfo?taskID=76577429

[build_s390x.txt.zip](https://github.com/lammps/lammps/files/7270452/build_s390x.txt.zip)

**Comment by junghans** [comment]
And on ppc64le:
```
The following tests FAILED:
	104 - MolPairStyle:hybrid-scaled (Failed)
	145 - MolPairStyle:lj_cut_tip4p_cut (Failed)
	204 - AtomicPairStyle:buck_coul_cut_qeq_point (Failed)
	205 - AtomicPairStyle:buck_coul_cut_qeq_shielded (Failed)
	222 - AtomicPairStyle:edip (Failed)
	227 - AtomicPairStyle:kim_lj (Failed)
	231 - AtomicPairStyle:meam_sw_spline (Failed)
	234 - AtomicPairStyle:reaxff (Failed)
	235 - AtomicPairStyle:reaxff_lgvdw (Failed)
	236 - AtomicPairStyle:reaxff_noqeq (Failed)
	237 - AtomicPairStyle:reaxff_tabulate (Failed)
	248 - ManybodyPairStyle:bop_save (Failed)
	251 - ManybodyPairStyle:drip (Failed)
	252 - ManybodyPairStyle:drip_real (Failed)
	257 - ManybodyPairStyle:ilp-graphene-hbn (Failed)
	258 - ManybodyPairStyle:ilp-graphene-hbn_notaper (Failed)
	259 - ManybodyPairStyle:kolmogorov_crespi_full (Failed)
	263 - ManybodyPairStyle:lebedeva_z (Failed)
	269 - ManybodyPairStyle:mliap_so3 (Failed)
	276 - ManybodyPairStyle:rann (Failed)
	385 - FixTimestep:momentum (Failed)
	457 - DihedralStyle:quadratic (Failed)
	459 - DihedralStyle:table_cut_linear (Failed)
	461 - DihedralStyle:table_linear (Failed)
Errors while running CTest
```

https://koji.fedoraproject.org/koji/taskinfo?taskID=76577428

[build_ppc64le.txt.zip](https://github.com/lammps/lammps/files/7270696/build_ppc64le.txt.zip)

**Comment by junghans** [comment]
And on aarch64:
```
The following tests FAILED:
	104 - MolPairStyle:hybrid-scaled (Failed)
	204 - AtomicPairStyle:buck_coul_cut_qeq_point (Failed)
	205 - AtomicPairStyle:buck_coul_cut_qeq_shielded (Failed)
	222 - AtomicPairStyle:edip (Failed)
	227 - AtomicPairStyle:kim_lj (Failed)
	231 - AtomicPairStyle:meam_sw_spline (Failed)
	234 - AtomicPairStyle:reaxff (Failed)
	235 - AtomicPairStyle:reaxff_lgvdw (Failed)
	236 - AtomicPairStyle:reaxff_noqeq (Failed)
	237 - AtomicPairStyle:reaxff_tabulate (Failed)
	248 - ManybodyPairStyle:bop_save (Failed)
	251 - ManybodyPairStyle:drip (Failed)
	252 - ManybodyPairStyle:drip_real (Failed)
	257 - ManybodyPairStyle:ilp-graphene-hbn (Failed)
	258 - ManybodyPairStyle:ilp-graphene-hbn_notaper (Failed)
	259 - ManybodyPairStyle:kolmogorov_crespi_full (Failed)
	263 - ManybodyPairStyle:lebedeva_z (Failed)
	269 - ManybodyPairStyle:mliap_so3 (Failed)
	276 - ManybodyPairStyle:rann (Failed)
	385 - FixTimestep:momentum (Failed)
	414 - FixTimestep:rigid_nph_small (Failed)
	457 - DihedralStyle:quadratic (Failed)
	459 - DihedralStyle:table_cut_linear (Failed)
	461 - DihedralStyle:table_linear (Failed)
Errors while running CTest
```

https://koji.fedoraproject.org/koji/taskinfo?taskID=76577427

[build_aarch64.txt.zip](https://github.com/lammps/lammps/files/7271526/build_aarch64.txt.zip)

**Comment by akohlmey** [comment]
Noted, but there are no plans currently to resolve any issues that are just numerical differences. As documented, those "force" tests are very sensitive to small differences because they look at relative differences and for some potentials (using QEq or interlayer potentials, or spline tables, or "hard" cutoffs resulting in "noisy" forces) even very small changes (e.g. compiling for a different C++ standard) can result in significant deviation.

**Comment by junghans** [comment]
Ok, what are we doing about the packages now?

I think we have the following options:
- exclude numerical-only test -Is there a ctest label for that? Or maybe a regex like `(AtomicPairStyle|DihedralStyle)`? I just don't feel informed enough to make that call.
- exclude all failing archs - that might be ok for obscure archs like `arm7hl` or `s390x`, but consider that many new exascale machines are arm or power-based, we should at least look into `ppc64le` and `aarch64`.

Some of the numerical differences on e.g. ppc64le are actually pretty big:
```
        Start 237: AtomicPairStyle:reaxff_tabulate
237/476 Test #237: AtomicPairStyle:reaxff_tabulate ....................***Failed    2.31 sec
[==========] Running 7 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 7 tests from PairStyle
[ RUN      ] PairStyle.plain
/builddir/build/BUILD/lammps-patch_29Sep2021/unittest/force-styles/test_pair_style.cpp:371: Failure
Expected: (err) <= (epsilon)
  Actual: 2.193968766019462 vs 9.9999999999999998e-13
/builddir/build/BUILD/lammps-patch_29Sep2021/unittest/force-styles/test_pair_style.cpp:372: Failure
Expected: (err) <= (epsilon)
```
and that might hint at a real problem.

**Comment by akohlmey** [comment]
> and that might hint at a real problem.

Not really. ReaxFF uses QEq and small numerical differences can quickly "explode" because of closely missing a convergence threshold and then one platform does one more iteration and then because of using relative differences those are even more emphasized for any "small" reference values. Add to that the complexity of the ReaxFF potentials. The same holds true for any pair style that uses spline interpolation (there you have "critical points" if you are left of right of a specific point in the spline table which can also depend on the tiniest differences). For the kind of confirmation that you are looking for, you have to design different tests. However, those can - by construction - not be sensitive enough than the ones that are failing for you to detect the issues they are meant to detect.

Thus a large difference does not automatically mean, that the calculation is incorrect.  It just manifests the difference between architectures and their compiler implementations and math libraries and even C++ standard semantics. When you compile with high optimization and use -Ofast or  add -ffast-math and -funroll-loops to the existing optimization on x86 you'll get the same kind of differences as well or worse. Even adding -std=c++20 can make a difference from some tests.

This all looks to me that you are trying to use those tests for something that they are not meant for. "unit test" is not really a good descriptor for anything in the "unittest/force-styles" folder. Those are near impossible to implement for a code like LAMMPS at this level. Those are better understood as a "consistency" check for the specific architectures that we do automatic testing on.

I have now very strong feeling of "deja vu". Didn't we go over this before?

**Comment by junghans** [comment]
> I have now very strong feeling of "deja vu". Didn't we go over this before?

I think we had a similar discussion in #2300, but back then only one test failed on one arch and we were able to patch this out. And then later the issue actually got solved, so we could drop the patch. Patching seems a bit unfeasible right now.

> This all looks to me that you are trying to use those tests for something that they are not meant for. "unit test" is not really a good descriptor for anything in the "unittest/force-styles" folder. Those are near impossible to implement for a code like LAMMPS at this level. Those are better understood as a "consistency" check for the specific architectures that we do automatic testing on.

As I said before this breaks a bit with `make`, `make test` standard to build and check code.
I will propose a PR to label those for easier exclusion.

**Comment by akohlmey** [comment]
This is really a packaging issue and not something that matters for the "normal" LAMMPS user. So if you want to change the behavior of LAMMPS, you should do that in the package but not in the distribution.

**Comment by junghans** [comment]
> This is really a packaging issue and not something that matters for the "normal" LAMMPS user. So if you want to change the behavior of LAMMPS, you should do that in the package but not in the distribution.

It might be also useful for any HPC admin that wants to test their installation. And ultimately test label could be useful in other cases, too. Like distinguishing long from short tests.

**Comment by akohlmey** [comment]
I repeat, those tests are not meant to be a pass/fail test for **any** executable with optimization enabled. So failures are expected and their magnitude at best a measure for how sensitive certain parts are to give different numeric results due to different architectures and compilers and optimizations. Unless we rewrite LAMMPS to do fixed point math, this will always be an issue. That is also explained in the manual. If you absolutely want to continue this discussion, please do it via personal email.
