### ISSUE TITLE
Incorrect outputs of "Fix setforce" for a new improper style

### ISSUE THREAD

**Issue by tengzhang48** [lammps/lammps#2995]
**Summary**

I implemented a lattice model for neo-Hookean solids to LAMMPS. It contains harmonic bonds and energy associated with area change in 2D. I borrow the improper style to implement the energy and forces associated with the area changes. The code works and can match the benchmark with the finite element method (FEM). But strange results are observed when I use "Fix setforce" to freeze the particles or maintain their initial speed. The deformation is still correct. However, the output force from the "Fix setforce" is much smaller than the expected value. 

Furthermore, I release the fix after running the simulations for a number of steps and output the force of each particle. A finite force is indeed there for those frozen by the command "Fix setforce". Therefore, the "Fix setforce" works as expected, but just does not output the correct summation of the totally removed forces.

**LAMMPS Version and Platform**

The LAMMPS version is "LAMMPS (28 Jul 2021)". We also tried the version " lammps 19Mar2020" and got similar results. 

**Details**

You can find the simulation input file and some output files in the following folder https://drive.google.com/drive/folders/1LzH5KPIfvla1U69b1Ax9VWoIAghRb6QH?usp=sharing. To run the simulations, you need to add the source codes "improper_neohookean.cpp and improper_neohookean.h" to the /src folder to compile. I also included the original paper for the lattice model in the folder. Although it is not necessary to read the paper to understand the code.

Thanks.

Best,
Teng

**Comment by akohlmey** [comment]
You are not paying attention. If this issue is independent from your custom style, then you can construct an input *without* any customizations and as few explicit, non-default settings and fixes/computes as possible. Ideally with just an lj/cut pair style and a small number of atoms. You are asking people to do extra work for something that is not supposed to be relevant. That is not going to happen. Instead of spending time arguing and trying to show that using your custom style has no impact you should rather construct a more convincing and easier to reproduce test case.
