### ISSUE TITLE
[Feature Request] GRANULAR package (pair_style granular): Polydisperse system simulations using Linear Spring Dashpot (LSD) model.

### ISSUE THREAD

**Issue by vikaskok** [lammps/lammps#3025]
**Summary**

pair_style granular cannot simulate poly-disperse system of particles with Linear Spring Dashpot (LSD) model  (with 'damping velocity' and 'damping mass_velocity')

**Detailed Description**
In 'pair_style granular', we have 4 types of damping: velocity, mass_velocity, viscoelastic, tsuji. (https://docs.lammps.org/pair_granular.html)  
I will concentrate on the first two (velocity, mass_velocity) in this query.  As per documentation, we (the user) has to specify $\eta_{n0}$. In case of damping velocity, $\eta_{n0}$ specified by the user should be in terms of mass/time units, and damping force is evaluated as: $F_{damp} = \eta_{n0} \times v$  (v=normal or tangential velocity, as the case may be.)  In case of damping mass_velocity, $\eta_{n0}$ specified by the user should be in terms of 1/time units, and damping force is evaluated as: $F_{damp} = \eta_{n0} \times meff \times v $ where meff = effective mass of colliding particles meff=(mi*mj/(mi+mj))

Evaluation of $\eta_{n0}$ in both of the above cases is as follows:

Following Silbert(2001), 
if we are to use damping velocity, then  
$\eta_{n0}=\frac{2 \ln(e_n) \sqrt{m_{eff}k}}{\sqrt{\pi^2 + \ln^2(e_n)}}$ (units: mass/time) [Eqn. 1]
and, 
if we are using damping mass_velocity, then 
$\eta_{n0}=\frac{2 \ln(e_n) \sqrt{k/m_{eff}}}{\sqrt{\pi^2 + \ln^2(e_n)}}$ (units: 1/time) [Eqn. 2]

(Some more details about [Eqn. 1, 2] are given towards the end in the footnote.) 

With the above expressions of $\eta_{n0}$, we shall have $\eta_{n0}$ in appropriate units required/expected by LAMMPS as given in the documentation.
(see also: https://github.com/lammps/lammps/issues/3016)

My concern is that the term meff appears in the expression used to evaluate $\eta_{n0}$.
Hence, we have an issue that these damping styles will work only for a mono-disperse system.

In a poly-disperse system (For eg. 10000 particle system whose dia is uniformly distributed in a range, say 0.8 to 1.2), the meff of the colliding particles is not known apriori before the simulation starts.

Particles of any two sizes can possibly collide. In such a scenario, we do not know meff of colliding particles and as a consequence, corresponding $\eta_{n0}$ cannot be evaluated and specified in the input script by the user.

Kindly confirm if I am correct so far.
Please correct me if I am missing something in here. I'd be very grateful.

If my understanding detailed above is indeed correct, the code needs to be modified to take care of poly-disperse collisions.

This can be achieved in the following manner:
1. meff term should be pulled out of $\eta_{n0}$ in 'damping velocity' and/or 'damping mass_velocity'.
In such a case
$F_{damp} = \eta_{n0} \times sqrt(meff) \times v$
where, user specified $\eta_{n0} = \frac{2 \ln(e_n) \sqrt{k}}{\sqrt{\pi^2 + \ln^2(e_n)}}$
(units: mass^0.5/time)

Or an entirely new damping can be included if we wish to ensure that the old input scripts of other users are not affected by these changes in newer versions of LAMMPS.
If that is the case, we can in fact go one step further and ask the user to just specify normal(and tangential) coefficient of restitution ($e_n$ and $e_t$) since this is more physical.
Then, $F_{damp}$ can be internally calculated as
$F_{damp} = \frac{2 \ln(e_n) \sqrt{m_{eff}k}}{\sqrt{\pi^2 + \ln^2(e_n)}} \times v$

We have to ensure that the above changes are made for:
1. both the normal and tangential damping cases for the case of particle-particle collision. (src/GRANULAR/pair_granular.cpp file)
2. both the normal and tangential damping cases for the case of particle-wall collision. (src/GRANULAR/fix_wall_gran.cpp)

Footnote:
Q: How to check for correctness of expressions for $\eta_{n0}$ i.e., [Eqn. 1,2].
A: I have obtained this by solving the (linear spring,damper,mass) system (Silbert. 2001).

Furthermore, I have checked and confirmed LAMMPS behaviour by running a few test simulations. I have considered the case of two particle collision in which one particle is initially at rest ($v=0$) and other impacts it with velocity ($v=1$). We can obtain final velocities of the particles and evaluate $e=(v2-v1)_{final}/(v2-v1)_{initial} = (v2-v1)_{final}/1 = v2-v1$

Case 1: Damping mass velocity.
Choose any kn value.
Choose any e value.
Choose dia of the colliding particles
Choose density of the particles. 
Calculate the masses of two particles and meff.
Calculate $\eta_{n0}$ value as per [Eqn. 1]
Specify this $\eta_{n0}$ value in the input script.
Run the simulation.
Obtain final velocities of the particles.
Calculate $e=(v2-v1)_{final}$. This should be the same as that of our chosen $e$, thus confirming the correctness of [Eqn. 1] to evaluate $\eta_{n0}$ for damping velocity.

The same can be carried out with damping mass velocity.
Comment/uncomment appropriate line in the input script.
Use [Eqn. 2] to evaluate $\eta_{n0}$ for this case.

**Further Information, Files, and Links**
I am uploading three files: 
1. in.dampingcheck.txt: input file
2. grains.txt : read_data file
3. etan0_calculator.py.txt to calculate \{eta_n0} value.
(change extension of this file to .py to run this python script. I have put a .txt extension since Github is not allowing me to attach/upload .py script with this post.)
This will help in replicating the issue on your end.
[grains.txt](https://github.com/lammps/lammps/files/7537922/grains.txt)
[in.dampingcheck.txt](https://github.com/lammps/lammps/files/7537923/in.dampingcheck.txt)
[etan0_calculator.py.txt](https://github.com/lammps/lammps/files/7537924/etan0_calculator.py.txt)

**Comment by dsbolin** [comment]
@vikaskok Thanks for the detailed report. You are correct, and this has come up in the past. Note that this behavior mirrors that of the older existing `pair gran/*` styles, so it is not particular to `pair granular`.

In short, I agree that what you suggest would be a useful feature. My only minor concern is that the equations you mention are derived for a linear spring (Hooke) normal contact model, and would not apply for other options (particularly Hertz). For polydisperse systems, the correct elastic treatment is Hertz, so it's a bit of an odd choice as far as physical models to use Hooke (constant stiffness regardless of size), but then worry about correcting the damping term to account for polydispersity. But, there are precedents for it (e.g. Luding 2008, Granular Matter v.10, p235), hence I agree it would be a useful option.

My inclination is to have a new damping option (maybe `linear`?), where the user specifies the coefficient of restitution, and the calculations you describe are performed internally. This is similar to the current `tsuji` option. The documentation can state that this option is physically justified only for Hooke as a choice of normal contact model, but still allow its use for other contact models ('buyer beware'; and anyway, Hooke isn't really a physically justified contact model to begin with..).

As far as tangential damping - generally those models are very empirical anyway, and mostly used for numerical stability rather than to reproduce any mechanically rigorous treatment, so I'm not too worried either way. With the way things are currently set up, I think simply using a scaling factor of 1 for the tangential damping would get you the desired behavior once the new damping option is available.

I can probably get to this later this week or next week and make a pull request, but if you have interest/time, feel free to make the changes, I'm happy to review code. Let me know.

**Comment by UitachiM** [comment]
May the atoms in the grians.txt correspond to the atom ID, type, diameter, density, and coordinate axis X, Y, Z?

**Comment by UitachiM** [comment]
@vikaskok May the atoms in the grians.txt correspond to the atom ID, type, diameter, density, and coordinate axis X, Y, Z?

**Comment by jtclemm** [comment]
Addressed by https://github.com/lammps/lammps/pull/4068
