### ISSUE TITLE
[BUG]  Missing KSPACE package in builds

### ISSUE THREAD

**Issue by SamTov** [lammps/lammps#3036]
**Summary**

I have tried to install the current LAMMPS branch using make and cmake with the KSPACE package however when I run simulations after a successful install I always receive the:

```bash
ERROR: Pair style requires a KSpace style (src/KSPACE/pair_born_coul_long.cpp:380)
```
error.

When I use make I always run the make ps to check that KSPACE is enabled which it is. If I use cmake I often use the most cmake file and check that it is included in the compiler flags. I have no errors in my compile and the executable runs okay. It just does not seem to include KSPACE.

**LAMMPS Version and Platform**

Using the develop or master branch. Running on Ubuntu 18.

**Expected Behavior**

I have installed lammps in the past using the old `cmake.basic` files and everything worked well. Now it seems that it does not find packages.

**Actual Behavior**

Does not find the KSPACE package.

**Comment by akohlmey** [comment]
This error message is not about *compiling* with the KSPACE package. In fact, it would be impossible to get this error *without* having installed the KSPACE package because the pair style causing the error is part of it. This error message is about not *using* a KSpace style. You can easily confirm yourself that the KSPACE package is available in your executable by using the `-h` flag when running it.
