### ISSUE TITLE
[Feature Request] Local averages

### ISSUE THREAD

**Issue by GenieTim** [lammps/lammps#3039]
## Summary

I would like to implement a way to collect time averages for properties computed by `compute bond/local`, `compute pair/local` or `compute property/local` (please correct me if there already is a way to do so).
In analogy to `fix ave/atom`, I would propose to implement a `fix ave/bond` or `fix ave/local`. 

## Detailed Description

What the feature provides, for example: being able to take time averages of bond properties *per bond*. This allows new mathematical results, e.g. taking the square of the time average before taking the ensemble average.

The reason this is currently not possible (for more than the group limit) is adressed in the documentation of [`compute bond/local`](https://docs.lammps.org/compute_bond_local.html), for example: 

> Note that as atoms migrate from processor to processor, there will be no consistent ordering of the entries within the local vector or array from one timestep to the next. The only consistency that is guaranteed is that the ordering on a particular timestep will be the same for local vectors or arrays generated by other compute commands. 

In analogy to `fix ave/atom`, I would propose to implement a `fix ave/bond` or `fix ave/local`. The difficulty which I fear I will encounter (in addition to understanding existing code) is the one that is probably the reason why it does not exist yet: the *ordered* communication between the processors. 
If you have any recommendations on what to look for, I would be happy to hear them.

I prefer `fix ave/bond` over `fix ave/local` as the resulting vector would by objective not be local anymore.

## Other Possibilities to Achieve the Same Result

In theory, I could think of a variety of different possible implementations; more abstract ones would e.g. include the possiblity to index computes by arrays, which would enable commands like this:

```
(...)
compute 1 crosslinkers property/local bid
compute 2 crosslinkers bond/local dist
fix 1 all ave/time 1 100 100 c_2[c_1[*]]
```

to have them ordered, or a fix that sorts the values in one vector by another, e.g. 

```
(...)
compute 1 crosslinkers property/local bid
compute 2 crosslinkers bond/local dist
fix 1 all sort/local/global c_2 c_1
fix 2 all ave/time 1 100 100 f_1[*]
```

I prefer a `fix ave/bond` over these possibilities as I think its implementation as well as the resulting command is more intuitive.

**Comment by akohlmey** [comment]
@GenieTim 
I don't think that this can work for local pairs at all, because the number of pairs can change (as the number of neighbors changes) so you would need to find a way to generate unique "pair IDs".

The problem with sorting is that it requires additional communication and buffering. You can look at the sorting of per-atom dumps. But in this case you have the additional complication of having to either collect all data to become global memory blocks (and thus be difficult to apply for large systems without running out of memory) or having the data distributed in a completely arbitrary way or include an infrastructure that migrates the data as the local property assignments is migrating (but still requiring a global sorting for consistent output).

Wanting to use those results for LAMMPS scripting makes this even more complex and difficult to implement without making the collected "local" data global (with the aforementioned limitation).

Thus I suggest before starting any implementation you think hard about what all those complexities will buy you over just doing the whole thing in post-processing, which is infinitely simpler.

As a point of reference, there is one alternate approach implemented by the REAXFF computes. They include blockwise averaging of the data, but that requires disallowing any neighborlist updates between output of the averaged data. Also, there is no attempt to make the data available for further processing in LAMMPS input scripting.

**Comment by GenieTim** [comment]
Thank you for your response, dear @akohlmey. You are right, I might have proposed a too general solution for my problem, bringing with it too many additional difficulties. I will try to restrict myself in the following to just describing _my_ goal, and why I think I need an integration into LAMMPS for this. 

What I want to compute: the time averages of the [dx and dy](https://github.com/lammps/lammps/pull/3032) components of the distance of every bond separately. If I want to do this using post-processing, I have to output the dx and dy components plus some identifier for this data (the bond id) for every bond for every time-step. This will result in _very_ large output files and presumably connected long post-processing times. That's why I would like to have the corresponding capability in LAMMPS directly.

Limiting myself to bonds would resolve the two concerns in your first paragraph (at least partially): the identifier is the bond id, the nr. of bonds is known too for every timestep (assuming bond breakage & creation are handled).
The communication and buffering will still be a problem to keep in mind.

**Comment by akohlmey** [comment]
@GenieTim
There is a big difference between implementing something with a rather general functionality (like some averaging fix) or something that suits your personal needs only. In the first case, the solution should be sufficiently general to be usable for a large variety of possible applications, so the barrier to create an implementation for general use in LAMMPS has to be rather high.  One has to factor in that, once some facility exists, people will come up with creative ways of using it that by far exceed what was originally envisioned as the intended use. In the second case, however, there is more room for flexibility.

Having too large files for post-processing is a legitimate problem. However, my usual suggestion would be to look into using the LAMMPS python module as a way to figure out a way to do post-processing on-the-fly, e.g. using fix python/invoke.  Since the application you describe could be a good example to showcase the application of using the python module for such purposes, I'd be willing to try writing a prototype example (e.g. computing average bond length and standard deviation), that could be added to the manual and then you could customize it for your needs. Since MD data is highly correlated, you would not need to collect and average data from every time step and that could make the python processing, even if only working on global data acceptable.

**Comment by GenieTim** [comment]
Thank you for your response, dear @akohlmey. Exactly, this difference between implementing something generel or something that suits my personal needs is why I opened this feature request as is. I would love to contribute back something bigger than just some documentation typos or minor increase in output options, and as this averaging fix would have suit my personal needs as well as offered the possibility to be useful to others, I proposed it here. 

I understand now that due to various uncertainties an `ave/local` fix would be too complex and too general to match what I can and should do. On the other hand, the `ave/bond` is a bit too close already to the personal needs to be generally useful, while still posing some problems to be overcome. 

I did look into the python/invoke fix, and I would think my problem could be solved like this (NOTE: untested):

```
python end_of_step_callback here """
import numpy as np

bondDxData = {}
bondDyData = {}
bondDzData = {}
def end_of_step_callback(lammps_ptr):
    lmp = lammps(ptr=lammps_ptr)
    xlinkdist = lmp.extract_compute("xlinkdist", LMP_STYLE_LOCAL, LMP_TYPE_ARRAY)
    bondIds = lmp.extract_compute("localid", LMP_STYLE_LOCAL, LMP_TYPE_VECTOR)
    for i, bondId in enumerate(bondIds):
      if (bondId not in bondDxData):
        bondDxData[bondId] = []
        bondDyData[bondId] = []
        bondDzData[bondId] = []
      bondDxData[bondId].append(xlinkdist[i][1])
      bondDxData[bondId].append(xlinkdist[i][2])
      bondDxData[bondId].append(xlinkdist[i][3])
    
    # output & reset average after every 1000th step
    if (lmp.get_thermo("Step") % 1000 == 0):
        with open("out-dx.txt", "a") as f:
            print("; ".join([np.mean(bondDxData[key]) for key in sorted(bondDxData)]), file=f)
        with open("out-dy.txt", "a") as f:
            print("; ".join([np.mean(bondDyData[key]) for key in sorted(bondDyData)]), file=f)
        with open("out-dz.txt", "a") as f:
            print("; ".join([np.mean(bondDzData[key]) for key in sorted(bondDzData)]), file=f)
        bondDxData = {}
        bondDyData = {}
        bondDzData = {}
"""

compute localid crosslinkers property/local bid
compute xlinkdist crosslinkers bond/local dist dx dy dz

fix eos all python/invoke 50 end_of_step end_of_step_callback
```

I do think though that the associated overhead of Python might be worth it for me to either still try to do an `ave/bond` implementation, or to pipe the lammps output into another program that does the averaging, but I might be a bit too much speculating here.

**Comment by akohlmey** [comment]
If you can call the python function only every 50 or 100 time steps, the overhead of the python module doesn't matter much. Specifically since you are using mostly compiled functionality and not doing much memory management or math in python.

**Comment by GenieTim** [comment]
Ideally I would call it every step, but I suppose you are right, that is an additional surface to accept a tradeoff. 
I will therefore close this issue for now and open a Pull Request if I implemented an `ave/bond` at some point.
