### ISSUE TITLE
Error in docs - 3.7.2. GPU package (missing mpi file)

### ISSUE THREAD

**Issue by gullbrekken** [lammps/lammps#3067]
**Summary**

3.7.2. GPU package refers to Makefile.mpi in lib/gpu which it seems does not exist any longer.

**LAMMPS Version and Platform**

Release version 09 Nov 2021.

**Details**

Example command under "Traditional make" refer to Makefile.mpi which it seems does not exist any longer in lib/gpu. Has it been replaced with Makefile.linux?

Command: make lib-gpu args="-m mpi -a sm_60 -p mixed -b" # build GPU library with mixed precision and P100 using other settings in Makefile.mpi

The paragraph below the command also refers to "machine makefiles for “mpi” and “serial” are provided ... ".

**Comment by ndtrung81** [comment]
@gullbrekken thank you for reporting this issue. Makefile.mpi is added to lib/gpu in the PR #3068.
@akohlmey I think the simplest way is to add a Makefile.mpi, instead of making changes to the documentation. The added Makefile.mpi is based on Makefile.linux, so that it is consistent with the command make lib-gpu args="-m mpi -a sm_60 -p mixed -b". I have also updated several Makefiles with comments, and removed Makefile.turing.
