### ISSUE TITLE
[BUG] _Restarting rRESPA calculations_

### ISSUE THREAD

**Issue by schreiner1** [lammps/lammps#3078]
**Summary**

Restarting from a restart file written during a respa NVE run fails

**LAMMPS Version and Platform**

LAMMPS (29 Sep 2021 - Update 1)
Red Hat Enterprise Linux Workstation 7.9
Intel® Xeon(R) Gold 6136 CPU @ 3.00GHz × 8 

**Expected Behavior**

Restarting from a restart file written during a respa run is expected to work like a restart from a Verlet run without any remap uporn reading the restart. All the energies and calculated properties immediately after reading the restart using the remap flag are expected to be identical to those reported upon writing the restart file.

**Actual Behavior**

When trying to restart from a restart file written during a respa run, LAMMPS reads fewer atoms than are present in the system and throws the error message:

ERROR: Did not assign all restart atoms correctly (…/read_restart.cpp:471)

Observations and additional tests:

The error happens even if one uses a restart file generated after just 1 integration step or using a small time step (1 fs). Interestingly, the number of atoms read from the restart in these two cases is also different. The error does not occur, if 1-level respa is used.

The classical explanation I found is that atom coordinates may be outside the bounds of the non-periodic box, actually, my box is periodic. Using the “remap” flag fixes the issue, though, suggesting atom coordinates may be indeed outside the bounds of the box.

I am wondering, though, why the error happens only in multilevel respa, even if the time step is half as large as in the one-level case.

After using remap, all energies in the first energy output of the new run a are identical to the last step from the previous run, as it should be.

However, the pressure is not.

**Steps to Reproduce**

In the attached archive, the file run_test.sh specifies all the operations necessary to reproduce the reported behavior. Note, please adapt the variable lammps_exe prior to executing the script. All the tests take less than a minute.
[respa_restart.tar.gz](https://github.com/lammps/lammps/files/7823437/respa_restart.tar.gz)

**Further Information, Files, and Links**

all the relevant inputs and outputs are contained in the attached tar.gz. The errors are reported in the output files
rgyr_restart_respa.out 
and
rgyr_restart_respa_smallt.out
To see the reported difference in pressure, please use
grep 100001 rgyr_respa.out
grep 100001 rgyr_restart_respa_remap.out
and compare the 11th column.

**Comment by schreiner1** [comment]
an additional comment: I realized that shake is being used in the posted inputs. However, I just verified, the error is identical if the shake fix is omitted, i.e. the error seems to have nothing to do with the use of shake,

**Comment by sjplimp** [comment]
@schreiner1 Thanks for posting this issue with a detailed example.
(a) The reason for lost atoms in a RESPA restart is that both Verlet and RESPA attempt to prevent this by forcing a reneighbor on the step when a restart file be written.  A reneighboring also enforces PBC (moves atoms back inside the box).  That works for Verlet b/c the neighbor build comes after atom coords have been updated.  But for RESPA I now see it doesn't work b/c the recursive nature of RESPA (2 levels or more) means atom coords are updated (in the same step) after the neighbor list is rebuilt.  So short answer is you have to use the remap option when reading a RESPA restart file.  We didn't realize this when we made it an option instead of the default behavior of read_restart.  Axel and I are now discussing if we should just make "remap" the default again.
(b) The pressure difference is a SHAKE issue.  You won't see it if you turn off SHAKE.  It has to do with how SHAKE adds constraint forces (which are a contribution to the virial in the pressure) at the start of a new restarted run versus the last step of a continuing run.  In the restart case, it is doing that before timestepping w/out a hierarchical timestep, on just the current snapshot
of the system.  So I don't know if it is possible to do it the same to match the final hierarchical step of the previous run.  Will need to think about that.
