### ISSUE TITLE
Dump of current atomic configuration from pair style PairXXX::compute method

### ISSUE THREAD

**Issue by yury-lysogorskiy** [lammps/lammps#3085]
Dear LAMMPS dev community,
I need to  dump to file the current atomic configuration  if certain criteria (i.e. extrapolation grade) are met inside PairXXX::compute(int eflag, int vflag) method.
Are there any direct possibility in LAMMPS codebase (some methods/functions to call), especially in MPI mode ?

**Comment by akohlmey** [comment]
Dumps are created by instances of a class derived from the Dump class and then calling their methods. They expect to be run by the Output class at the end of a timestep or in between runs. See functions `Output::write()` in output.cpp and `WriteDump::command()` in write_dump.cpp. It is usually necessary to know at the beginning of a timestep whether a dump will be performed so that all  dependent on-demand calculations (collection of energies and virials or execution of computes) can be triggered (some of them cannot be triggered after the fact) so that there are no errors.

**Comment by akohlmey** [comment]
Please note this kind of general inquiry is best done in the LAMMPS forum (there is a development sub category) or the lammps-users mailing list. Thus I am closing this issue here now. Thanks in advance for your cooperation.
