### ISSUE TITLE
delete_atoms porosity complains: "Could not find delete_atoms region ID"

### ISSUE THREAD

**Issue by jfikar** [lammps/lammps#3114]
I'm trying to remove some atoms with `delete_atoms porosity`, but I'm always getting an error:

```
ERROR: Could not find delete_atoms region ID (src/delete_atoms.cpp:428)
Last command: delete_atoms porosity mygroup NULL 0.1 12345678
```

For some reason the region is not found. I tried to specify a region or to write NULL instead (as finally I don't need the region at all), result is the same. This is my sample script:

```
units           metal
atom_style      atomic
boundary p p p
variable a0 equal 4.04999918095267
lattice         fcc ${a0}
region          box block -7 7 -4 4 -3 3
create_box      1 box
create_atoms    1 box
mass            1  26.981539 #Al

variable        myvar atom "x > 0"
group           mygroup variable myvar

#delete_atoms porosity mygroup box 0.1 12345678
delete_atoms porosity mygroup NULL 0.1 12345678
#delete_atoms group mygroup
#delete_atoms region box
```

First two commands `delete_atoms porosity` don't work. The other two `delete_atoms group` and `delete_atoms region` work, so it seems the region and the group are both correct and there is actually a problem with `delete_atoms porosity`.

I have tried versions LAMMPS (29 Sep 2021 - Update 2) and LAMMPS (20 Nov 2019). They behave the same.

**Comment by akohlmey** [comment]
There is no problem. This is the expected behavior. This feature you are looking to use was added **after** any of the two LAMMPS versions you are referring to were released. https://github.com/lammps/lammps/releases/tag/patch_14Dec2021

When comparing with the documentation you **must** compare to the documentation matching your LAMMPS version. The (default) online version will always represent the latest patch release. If you look at the online version of the manual for the stable version, you will see that the feature is not available and thus the error correct: https://docs.lammps.org/stable/delete_atoms.html

**Comment by jfikar** [comment]
Thanks Axel, indeed in version LAMMPS (7 Jan 2022) it works as expected.
