### ISSUE TITLE
Setting Inlining Threshold for Kokkos/SYCL Backend

### ISSUE THREAD

**Issue by joeatodd** [lammps/lammps#3183]
**Summary**

When working with LAMMPS -> Kokkos -> SYCL, we've found significant performance gains from passing the `-fgpu-inline-threshold=100000` option to DPC++ in `-DCMAKE_CXX_FLAGS` in our build scripts. It'd be nice to be able to set this as a default, but as far as I'm aware, the LAMMPS build system is unaware of SYCL. Is there a neat solution to this?

**Details**

We build LAMMPS with:

`-DCMAKE_CXX_FLAGS="-fgpu-inline-threshold=100000 ..."` and this gave us several % performance improvement.

I had hoped that it might be possible to include this in the LAMMPS cmake somewhere, but I don't see that it's currently possible. The interaction between the build systems of Kokkos & LAMMPS is a little beyond my understanding, so I'm raising this issue to see if anyone can suggest a solution. I suppose it'd be possible to specialize the LAMMPS cmake further to detect DPC++, but it'd be nice if this could be avoided.

**Comment by akohlmey** [comment]
The interaction between KOKKOS and LAMMPS when using CMake is indeed a bit complex since KOKKOS' CMake scripting has different expectations and assumptions than the LAMMPS scripts.

I would suggest to create a 'kokkos_sycl.cmake' file in the cmake/presets folder. That would allow you to have default compiler and other settings applied. For the specific compiler option, I would recommend to set CMAKE_TUNE_FLAGS inside the preset script. That is the variable intended for such settings (if it works).

For the GNU make build you can simply provide a custom makefile in src/MAKE/OPTIONS/

In both cases, there are some existing files for KOKKOS that may serve as inspiration. Please ask here or in the developer slack, if you have further questions.

**Comment by joeatodd** [comment]
Thanks for the suggestions @akohlmey, i'll give it a go!

**Comment by akohlmey** [comment]
@joeatodd the CMake preset PR has been merged. Is there any additional action item to resolve this issue?

**Comment by joeatodd** [comment]
@akohlmey Nope, thanks :+1:  I'll close this.
