### ISSUE TITLE
Move replicated constants and enumerators to header files

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#325]
LAMMPS has several constants that need to be kept in sync across multiple files. They are usually not included in headers because of their generic names. However, in the interest of code maintainability, the current practice should be abandoned in favor of adding those constants to suitable header files and either to base class definitions (example `Timer`) or to separate namespaces (example `FixConst`).

**Comment by ibaned** [comment]
Allow me to offer some points of consideration:

1. It is very easy for a programmer to accidentally modify one of the definitions in the `.cpp` files and not change the others. If those two classes communicate and expect consistent values, the code will fail in hard-to-debug ways. This applies to all forms of copy-paste programming, other forms of which I've already had to fix (see timattox/lammps_USER-DPD#5 and #324, PairTable had new code that those two were not using).

2. There is already at least one conflict in LAMMPS, which is silently "resolved" by the compiler:
https://github.com/ibaned/lammps/blob/435421301b0b851f1b73c04885f63e2f09c20475/src/KOKKOS/neigh_list_kokkos.h#L23
https://github.com/ibaned/lammps/blob/435421301b0b851f1b73c04885f63e2f09c20475/src/KOKKOS/pair_table_kokkos.cpp#L37
The way the compiler picks between those two definitions to resolve a reference like this:
https://github.com/ibaned/lammps/blob/435421301b0b851f1b73c04885f63e2f09c20475/src/KOKKOS/pair_table_kokkos.cpp#L125
Is quite unintuitive: it sees the code is inside the class which is inside the LAMMPS_NS namespace, so the LAMMPS_NS definition wins. That means the one in the global namespace in the `.cpp` file gets totally and silently ignored, so it does nothing.

3. If one ensures that all enums are in the same namespace (either LAMMPS_NS) or the global namespace, then the compiler will emit an error for all conflicting definitions, guaranteed. A good automated check is better than relying on people following some rule.

I personally recommend having a single definition of each enum, no matter what.

As for namespaces, there is a tradeoff here. Placing things deep in namespaces is good precisely because it enables two separate classes to define the same enum with different meanings, which is good encapsulation. The down side is this also opens up the possibility of conflicts up and down the hierarchy as seen above. Because the compiler is so strangely silent about those specific conflicts, it may give more peace of mind to put all enums in only one namespace, with prefixed value names as necessary (NEIGH_FULL vs FULL), where the compiler checks them. However, the same risk of conflicts is true in the case of virtual functions: they override each other in ways that only the compiler knows and people have to be careful, and LAMMPS seems to take full advantage of this feature and accept the risks.

**Comment by stanmoore1** [comment]
I think this is a good change. However, there are a LOT of enums in LAMMPS, and I think any change here should be done as a whole and not incrementally, which could be a significant amount of work.
