### ISSUE TITLE
Reduce warnings when compiling LAMMPS

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#3253]
**Summary**

Try to reduce warnings when compiling LAMMPS

**Detailed Description**

Here are some warnings I see with GCC 8.3.1, CUDA 11.6.0

```
../fmt/format.h:2450:90: warning: declaration ‘class std::system_error’ does not declare anything
 FMT_API auto vsystem_error(int error_code, string_view format_str,
```

```
In file included from ../style_kspace.h:12,
                 from ../lammps.cpp:27:
../pppm_disp.h:30: warning: "LMP_FFT_LIB" redefined
 #define LMP_FFT_LIB "KISS FFT"
 
In file included from ../style_kspace.h:8,
                 from ../lammps.cpp:27:
../pppm.h:30: note: this is the location of the previous definition
 #define LMP_FFT_LIB "cuFFT"
```

**Comment by akohlmey** [comment]
> ```
> ../fmt/format.h:2450:90: warning: declaration ‘class std::system_error’ does not declare anything
>  FMT_API auto vsystem_error(int error_code, string_view format_str,
> ```

I don't know how to "fix" this one (I had already tried before).
This is one of the cases where "header" libraries are at a loss due to the confusing way how the CUDA compiler works, since it is a kind of chimera that runs both the CUDA compiler and the host compiler on the same files which makes detecting available features and adapting to the compiler a massive challenge. This is not a fmt library problem, but also for STL and libraries like Eigen. :-1: 

> ```
> In file included from ../style_kspace.h:12,
>                  from ../lammps.cpp:27:
> ../pppm_disp.h:30: warning: "LMP_FFT_LIB" redefined
>  #define LMP_FFT_LIB "KISS FFT"
>  
> In file included from ../style_kspace.h:8,
>                  from ../lammps.cpp:27:
> ../pppm.h:30: note: this is the location of the previous definition
>  #define LMP_FFT_LIB "cuFFT"
> ```

I think it is now time to consolidate all this FFT related settings, defines and typedefs into a single canonical header file.
I've tried this in commit aae44892c0efc01eebf0af2570eff2c1bbd8f21a

**Comment by akohlmey** [comment]
> ../fmt/format.h:2450:90: warning: declaration ‘class std::system_error’ does not declare anything
>  FMT_API auto vsystem_error(int error_code, string_view format_str,

I have carefully checked the fmt/format.h and found that it does the right thing (`#include <system_error>`) so the real problem is with the version of STL that is bundled with the host compiler. I doubt that there is a workaround to shut this up.

**Comment by stanmoore1** [comment]
OK thanks for the info and looking into this

**Comment by stanmoore1** [comment]
I fixed most of the Kokkos warnings in 6ec169f.

I can't seem to get rid of this warning:
```
../npair_ssa_kokkos.cpp(467): warning #20011-D: calling a __host__ function("LAMMPS_NS::NPairSSAKokkosExecute< ::Kokkos::Cuda> ::~NPairSSAKokkosExecute()") from a __host__ __device__ function("LAMMPS_NS::NPairSSAKokkos< ::Kokkos::Cuda> ::build( ::LAMMPS_NS::NeighList *)::[lambda(int) (instance 1)]::~[lambda(int) (instance 1)]") is not allowed
```
It is calling the destructor from device code but I'd have to mark even the base non-Kokkos classes as `KOKKOS_INLINE_FUNCTION`

**Comment by akohlmey** [comment]
> I can't seem to get rid of this warning:

Certain warnings cannot be avoided. Sometimes compilers just get it wrong and sometimes the code would have to be rewritten from scratch. Both are beyond our options to correct, so we have to accept them. But at least we can try to reduce everything else, so that it will be easier to spot real issues.

**Comment by stanmoore1** [comment]
@akohlmey I agree, thanks
