### ISSUE TITLE
[BUG] cmake install of lammps with ML-PACE fails to install libyaml-cpp-pace.so

### ISSUE THREAD

**Issue by bernstei** [lammps/lammps#3265]
**Summary**

Following the web site instructions for cmake-based installation of the python package for LAMMPS with ML-PACE active, the module cannot be loaded because it cannot find libyaml-cpp-pace.so

**LAMMPS Version and Platform**

CentOS 7, Intel 64 bit CPU, git latest 04537c9f22b

**Expected Behavior**

`python -c "import lammps; lammps.lammps()"` runs without error

**Actual Behavior**

```
tin 1525 : env LD_LIBRARY_PATH=$HOME/.local/lib64:$LD_LIBRARY_PATH python -c "import lammps; lammps.lammps()"
libpath liblammps.so
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cluster2/bernstei/.local/lib/python3.8/site-packages/lammps/core.py", line 151, in __init__
    self.lib = CDLL(libpath,RTLD_GLOBAL)
  File "/home/Software/python/anaconda3/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libyaml-cpp-pace.so.0.6: cannot open shared object file: No such file or directory
```

**Steps to Reproduce**

compile lammps with "-D BUILD_SHARED_LIBS=ON  -D PKG_ML-PACE=ON -D LAMMPS_EXCEPTIONS=ON -D PKG_PYTHON=ON", build, then install with `cmake --install .` without root permission so it writes into ~/.local.
Run one liner above.

**Comment by akohlmey** [comment]
@bernstei This is not a LAMMPS issue but due to the PACE source code which we don't maintain. A possible workaround would be to configure and install the PACE library as a standalone (shared) library and then don't use the automatic download through LAMMPS' CMake build.
@yury-lysogorskiy This is an issue of the CMake scripting that is part of the PACE library. To avoid complications with having to install many dependent shared libraries, we build them *always* as STATIC but with CMAKE_POSITION_INDEPENDENT_CODE active so that those static libs are compatible with building a shared  LAMMPS library. The support libraries are then included directly in liblammps.so (as is the PACE library) and problems like this won't show.

**Comment by akohlmey** [comment]
@bernstei After looking at the pace library CMake code for yaml-cpp, there may be an easier workaround.
Please try configuring with -DYAML_BUILD_SHARED_LIBS=off
Then you should get a static yaml-cpp library and don't need to have it installed

**Comment by bernstei** [comment]
Thanks @akohlmey - your simple workaround does fix the problem.
