### ISSUE TITLE
[BUG] dump xtc format is broken

### ISSUE THREAD

**Issue by liuyujie714** [lammps/lammps#3292]
**Summary**

dump xtc format is broken

**LAMMPS Version and Platform**

Should be 2021/2022 major, I compiled lammps source by Visual Studio. Pre-compiled latest Windows version is also broken 

**Expected Behavior**

work correct

**Actual Behavior**

dump xtc format trajectory can not be open by vmd, etc.

**Steps to Reproduce**

`dump  myxtc all xtc 100  dump.xtc`

**Solution**

We must fopen xtc in binary mode to write

https://github.com/lammps/lammps/blob/develop/src/EXTRA-DUMP/dump_xtc.cpp#L436, **wb+** or **rb**  is needed

**Comment by akohlmey** [comment]
@liuyujie714 thanks for your report. Many thanks also for compiling and testing LAMMPS on Windows. This is a great help.
I can confirm the bug and it must have been in LAMMPS since support for the xtc dump style was added.
The (indeed obvious) bugfix will be added soon and should be available in the next LAMMPS release.
