### ISSUE TITLE
[Feature Request] GPU acceleration for EFF module

### ISSUE THREAD

**Issue by Chivier** [lammps/lammps#3325]
**Summary**

EFF module's performance is limited. Can I use GPU to accelerate the program?

**Detailed Description**

I tried to build a GPU version EFF module on previous version. I made something like 'EFF_GPU' with cuda codes inside. However, when the input file is larger, I meet a bug like this:

![image](https://user-images.githubusercontent.com/41494877/176705428-bbcb7fa6-4282-4fd0-ad9e-b78ed0d4b59f.png)

I searched the solution on Nvidia forum: [cuda with lammps](https://forums.developer.nvidia.com/t/cuda-with-lammps-cuda-driver-error-4-in-call-at-file-geryon-nvd-device-h-in-line-135/111116)

So, I am wondering whether I have to use lib/gpu for further development. Or, is there any possible method to run EFF module on GPU?

**Comment by akohlmey** [comment]
LAMMPS has two ways to add GPU acceleration. 1. the GPU package, 2. the KOKKOS package. Adding GPU accelerated modules to either is not a trivial process. That is doubly true for an entire package. Both packages have established conventions and requirements that need to be (mostly) learned from reading the existing source code and looking for similar code. In the case of the EFF package, the latter is not likely to find, since it is rather unique in its application.

I cannot comment on code that we cannot see and didn't write.

**Comment by Chivier** [comment]
Thanks a lot. EFF package defines atom_vec_electron, which provides AtomStyle(electron,AtomVecElectron). I cannot find anything similar to this in GPU/KOKKOS package. It is a little difficult for me to build a completely new one by myself.

By the way, is there any project can do the same job with EFF package?

**Comment by akohlmey** [comment]
> By the way, is there any project can do the same job with EFF package?

I don't know, you have to contact the EFF package author about it.

**Comment by Chivier** [comment]
Good idea, thanks for help!

**Comment by 296897546** [comment]
Hi, have you  solved the problem? I also want to use gpu to accelerate eff.
