### ISSUE TITLE
Set explicit `python` with `-D Python_EXECUTABLE=path`

### ISSUE THREAD

**Issue by ocaisa** [lammps/lammps#3354]
**Summary**

Typo in the docs at  https://docs.lammps.org/Build_extras.html#python to set an explicit `python`

**LAMMPS Version and Platform**

Version: 23Jun2022
Platform: AMD Zen2 with NVIDIA V100 GPU, Rocky Linux 8, EasyBuild recipe for LAMMPS

**Details**

The current docs say you can use
```
-D PYTHON_EXECUTABLE=path
```
to explicitly set the `python` to be used. This setting seems to be ignored though, when I used CMake 3.20.1 the correct setting was
```
-D Python_EXECUTABLE=path
```

**Comment by akohlmey** [comment]
@ocaisa thanks for your report. This is a bit of tricky business since our set goal is to support CMake 3.10 (as shipped with Ubuntu 18.04 LTS) as the oldest CMake version, and Python interpreter detection changed massively in CMake 3.12.
It will need some thinking and testing with Ubuntu 18.04LTS about how to best address this (with an old version and a new version).
