### ISSUE TITLE
[Feature Request] Support arbitary momentum/velocity setting in "fix momentum" command

### ISSUE THREAD

**Issue by jiehou93** [lammps/lammps#3356]
**Summary**

Modify "fix momentum" command to allow customized momentum/velocity setting, rather than simply zeroing out the momentum.

**Detailed Description**

The current "fix momentum" command zeros the linear and/or angular momentum of the group of atoms every N timesteps. It would be useful if users can have some control over the final momentum (or velocity). 

An application for the above function is to apply constant velocity displacement to a group of atoms (like surface layers) while keep their relative movements. Currently I can only apply such displacements to a rigid group of atoms (e.g., via velocity command and setforce to zero).

**Further Information, Files, and Links**
I made some modification myself and it seems to work out fine. The main modification involves lines 147-149 in fix_momentum.cpp.
Here's the original version:
        if (xflag) v[i][0] -= vcm[0];
        if (yflag) v[i][1] -= vcm[1];
        if (zflag) v[i][2] -= vcm[2];
and here's my modification
        if (xflag) v[i][0] -= vcm[0]-vel_x;
        if (yflag) v[i][1] -= vcm[1]-vel_y;
        if (zflag) v[i][2] -= vcm[2]-vel_z;
where vel_x, vel_y, vel_z is the final velocity components I inputed.

**Comment by akohlmey** [comment]
@jiehou93 this kind of bias is usually applied using fix addforce. Granted, this is more indirect, since you have to choose a suitable force to achieve a desired net velocity though reaching a steady state. But you have to be careful to not induce a global center of mass drift that would invalidate all thermostatting anyway.

Another option is to apply fix move to a (regular or random) subset of the atoms in question which will then drag the remaining atoms in that group along. I have posted two example movies on YouTube showing how you can use fix move to drive some atoms that can move freely along with fix move (in this case for rotation, but that can be applied to any kind of motion that can be defined for fix move).
https://youtu.be/-JpgiXyc8o8
https://youtu.be/3cWXG7gBgME

**Comment by jiehou93** [comment]
@akohlmey many thanks for your comment and vedio links.

Fix addforce is certainly a good way to apply displacement while keep relative movements of atoms. But it's essentially a stress control method, that means we can control the stress applied by adjusting the force added, but the strain/displacement/net velocity cannot be directly controled. 

Though the stress control is very useful, it would be nice to also have the alternative option of strain control, as it's often a more direct comparison to experiments.

For the fix move command, my concern is it freezes out the relative movement of atoms in the fix group. For instance, if we try to simulate plastic deformation by appling displacement on top and bottom surface layers of a bulk metal, then the fix move command would freeze these surface layers, which blocks dislocations and prevents dislocation annhiliation at surfaces. AN I think applying fix move on a random subset of atoms (as showed in the youtube vedio) would not resolve this issue.

**Comment by akohlmey** [comment]
> But it's essentially a stress control method, that means we can control the stress applied by adjusting the force added, but the strain/displacement/net velocity cannot be directly controled.

Whether you add a uniform force or add a uniform velocity to a group of atoms of the same kind is essentially the same thing.

**Comment by jiehou93** [comment]
> Whether you add a uniform force or add a uniform velocity to a group of atoms of the same kind is essentially the same thing.

No these two method can be quite different. Let's say I want to run a simulation of tensile deformation. With the add velocity method, I can simply assign +v and -v  to top and bottom layers of the material, then it will continuous to deform with a constant strain rate, straight and simple.
 
But if I choose to apply the add force method, the materials will first show a finite deformation, then reach an equilibrium state (assuming the force is not enough to fracture the material), because the force I added will eventually be counter balanced by the elastic force from the deformation. That means I need to keep increasing the force in order to mantain continiuous deformation. Also, I have no direct control over the strain rate of deformation, because it will depends on elastic and plastic properties of the material.

**Comment by akohlmey** [comment]
When you instead add a velocity as you propose you give atoms in the designated group a "klck" (and repeatedly so at a fixed frequency and in the same direction) and thus run into the similar problems as with fix temp/rescale or the much maligned Berendsen thermostat. I consider this something you should not be doing during a production run.

**Comment by jiehou93** [comment]
Can you elaborate a bit on the problem assiciated with temp/rescale and Berendsen thermostats? I haven't really used these two commands so I'm not sure what you are referring to.

**Comment by akohlmey** [comment]
I have referred to the disastrous effect of using temp/rescale many times on the LAMMPS mailing list. Yours is worse because you want to give your system a kick in a specific direction not just scale all velocities. The unphysical behavior of the Berendsen thermostat (which manipulates velocities) versus the Nose-Hoover thermostat (which manipulates forces) is a topic often discussed on many MD codes and for which publications exist.

**Comment by jiehou93** [comment]
Thanks for the clarification. If I understand this correctively, velocity manipulation (either temp/rescale or the velocity control discussed above) should not normally be applied to atoms that also have their temperature controlled by another fix (e.g., fix nvt).
But I think this can be resolved by using nvt and nve separately, with nve + velocity control applied only to surface layer, and nvt to other bulk atoms.

**Comment by akohlmey** [comment]
No you don't understand me. The problem is both in the abruptness of the velocity change and the fact that it is periodic with a fixed direction. The issue you mention is very minor in comparison and not a big concern here.

In your proposed modification the effect is similar than applying a sledgehammer to those atoms where how hard it hits depends on the velocity difference. It only would be of no consequence, if those were the only atoms in the system, but then the change would be pointless, since such a system would be invariant to translation and setting a net momentum is meaningless in that case. When you have other atoms in the system, there will be negative and undesired effects.

**Comment by jiehou93** [comment]
My apologies, I can understand this is similar to applying a sledge hammer to selected atom, but I still don't see the problem here.

I mean, kicking these atoms to force defromation is actually the purpose here, and I imagine it would not be so different to rigid displace methods (such as fix move, or assiging initial velocity + setforce to zero).

**Comment by akohlmey** [comment]
It is different because it is periodic and thus can induce phonons and resonances. It is different from the other methods you mention because, once started they are smooth and continuous.

**Comment by jiehou93** [comment]
OK I get your points now. I actually did some test run recently with the modification mentioned above to apply shear to an iron lattice, but the simulation just evolves as I expected, no abormal fluctuations in temperature/pressure was noticed. I checked that the velocited I manually added is about 3 orders of magnitudes lower than the thermal velocity at room temperature, probably small enough to avoid any resonances. So I thinks it might be still useful to consider this method in certain conditions.

**Comment by akohlmey** [comment]
> So I thinks it might be still useful to consider this method in certain conditions.

Properties that rely on auto-correlation can be quite sensitive even to small contributions.

You are - of course - free to change the LAMMPS source code any which way you like and use that for your studies, but I don't think this should become a general feature in LAMMPS. There is just too high a risk that somebody would taint their work unintentionally.

**Comment by jiehou93** [comment]
I understand your concern here. Thank you for your discussion and comments anyway, it helped a lot!
