### ISSUE TITLE
Extending Compute centroid/stress/atom for pairstyle lj/cut/coul/long and models with k_space style

### ISSUE THREAD

**Issue by Bagbodek** [lammps/lammps#3362]
**Summary**

An Extension of the compute 'centroid/stress/atom' to handle models with long range coulombic forces (requiring k_space style command) and pair style lj/cut/coul/long.

**Detailed Description**

Hello LAMMPS developers,

I wanted to find out if anyone plans to work on extending the compute centroid/stress/atom (used for calculating per atom virial stresses which in turn are used for computing heat fluxes) to FFs involving long-range dispersion/coulombic interactions. I am interested in using it for the lj/cut/coul/long pairstyle in particular. My model also requires the use of the k_space style command.

I am currently working on a project to decompose heat fluxes into molecular contributions and for now I am stuck with the compute stress/atom which when used to compute heat flux, has been reported to give inaccurate results for the heat flux contributions from angles and dihedrals when compared to using the compute centroid/stress/atom.

Extending the compute centroid/stress/atom in this regard will have the impact of increased use of LAMMPS for detailed heat flux decomposition for systems with complex FFs, which in turn is useful for molecular design of materials for thermal applications.

I will appreciate any information on this.

**Further Information, Files, and Links**

Boone, P.; Babaei, H.; Wilmer, C. E. Heat Flux for Many-Body Interactions: Corrections to LAMMPS. J. Chem. Theory Comput. 2019, 15 (10), 5579–5587. https://doi.org/10.1021/acs.jctc.9b00252

**Comment by athomps** [comment]
I am not qualified to comment on whether this is feasible and/or useful.  I defer to @donatas-surblys

**Comment by donatas-surblys** [comment]
Sorry, just noticed this now.

The topic was discussed at the end of #1705, but the gist is that the centroid approach can’t really do anything different from the original implementation of heat flux via stress/atom regarding kspace, but is disabled because using it for local control volumes not spanning the entire system is a bit questionable. Although the same can be said about the original stress/atom too. In principle, you can use stress/atom for the kspace contribution and centroid/stress/atom for the rest. It is quite cumbersome though, and I’ve been thinking about enabling kspace in centroid/stress/atom, but haven’t found time to do a pull request. Since LAMMPS code has gone under some changes, you can no longer use instructions in #1705. 

For the time being, with more recent LAMMPS versions, the following changes in **kspace.cpp** should enable it:
`centroidstressflag = CENTROID_NOTAVAIL;`
↓
`centroidstressflag = CENTROID_SAME;`


` vflag_atom = vflag & VIRIAL_ATOM;`
↓
`vflag_atom = vflag & (VIRIAL_ATOM | VIRIAL_CENTROID);`

**Comment by akohlmey** [comment]
This has been sitting for over a month now without any followup or other reaction. Since it doesn't look like it won't make much of a difference anyway, I am closing this now and wait for a possible pull request.
