### ISSUE TITLE
[BUG] Atom mass in PyLammps: index out of bounds

### ISSUE THREAD

**Issue by MBartkowiakSTFC** [lammps/lammps#3376]
**Summary**

We have a simulation running via PyLammps, with 1000 Ar atoms. The code crashes when we try to read out the masses of the atoms.

n_atoms = 1000
self.lmp is a PyLammps object.

```
        atoms = np.zeros([n_atoms, 5])
        for i in range(n_atoms):
            atom = self.lmp.atoms[i]
            atoms[atom.id-1, :] = (list(atom.position) + [atom.mass, atom.charge])
```

The last line fails:
  File "lammps/pylammps.py", line 177, in mass
    return self.get("mass", self.index)
  File "lammps/pylammps.py", line 140, in get
    return prop[index]
IndexError: index 2 is out of bounds for axis 0 with size 2

It seems that the ‘mass’ property only has 2 elements, [0 39.948], and not 1000 elements as expected.

**LAMMPS Version and Platform**

This happens both in the last stable release (23 June 2022) and in the code I cloned from GitHub today.
This code still worked with the 29 Sep 2021 release of LAMMPS.

**Expected Behavior**

Normally, we should get the correct atom mass for every single atom. In our example above it should be 1000 elements , 39.948 each.

**Actual Behavior**

The simulation crashes when the loop tries to get the mass of the 3rd atom, since there are only two numbers in the corresponding array. Also, the first mass is 0.0.

**Steps to Reproduce**

I attached a simple Python script which triggers the problem.

**Further Information, Files, and Links**

[testPyLammps.py.zip](https://github.com/lammps/lammps/files/9251772/testPyLammps.py.zip)

**Comment by akohlmey** [comment]
This is not a bug but incorrect usage. The "mass" property is a per-atom-type property and not a per-atom property. This is due to the internal dimensions of the corresponding arrays. You can find a [table of those](https://docs.lammps.org/Classes_atom.html#_CPPv4N9LAMMPS_NS4Atom7extractEPKc) in the documentation.

**Comment by MBartkowiakSTFC** [comment]
Just as a comment, the previous stable release of LAMMPS did produce a mass value for every atom exactly this way, and my example script produced the following output:
LAMMPS (29 Sep 2021 - Update 3)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
LAMMPS output is captured by PyLammps wrapper
We expect 3 atoms, PyLammps has got  3
Atom number  1  has mass= 42.0
Atom number  2  has mass= 42.0
Atom number  3  has mass= 42.0

**Comment by akohlmey** [comment]
> stable release of LAMMPS did produce a mass value for every atom exactly this way

This is because previously PyLAMMPS would use a very inefficient way to obtain the mass information that does not access the mass array in the Atom class directly. If I recall correctly, this old implementation would not allow you to *set* the mass.
Please see commit 41da32d7de8ba19529b10e1d13af98b3a88a0334

In general, we do not recommend using PyLAMMPS for anything but demonstrations. It is *very* inefficient and fragile due to the way it obtains and stores the information about the system. You will be much better off using the regular lammps python module. There also, the calls are more explicit and it much more closely follows the C library interface which is the ultimate standard.

**Comment by MBartkowiakSTFC** [comment]
Thank you for looking into this, and for the comments!
