### ISSUE TITLE
[BUG] dump output (dump_modify) of timesteps not as expected

### ISSUE THREAD

**Issue by hoba87** [lammps/lammps#3424]
**Summary**

The dump_modify command works not as expected, because requested timesteps are not printed to dump file.

```
fix fixNVT1 all nvt temp 1000 1000 0.0010000000000000002
dump_modify customDump every 50
run 50
unfix fixNVT1

fix fixNVE all nve
dump_modify customDump every 10
run 10
unfix fixNVE

fix fixNVT2 all nvt temp 1000 300 0.0010000000000000002
dump_modify customDump every 10
run 10
unfix fixNVT2
```

**LAMMPS Version and Platform**

LAMMPS (23 Jun 2022) on CentOS 8.5

**Expected Behavior**

I get for the given fix runs and dump_modify commands output to dump at timesteps of 0, 50, 60 and 70. If the nve fix is deleted (the 5 lines in the middle) I would expect timesteps at 0, 50 and 60.

**Actual Behavior**

However I only get timesteps at 0 and 50, despite Lammps is running fine without error.

**Steps to reproduce**
Or for the input files given in the zip file, I get timesteps at 0, 50 and 100 instead of 0, 50, 60 and 110.
[lammps.zip](https://github.com/lammps/lammps/files/9452460/lammps.zip)
replace the respective lines in the in.lammps file to reproduce exactly the case described above.

**Comment by mkanski** [comment]
First things first - `fix nve` and other time-integrating fixes don't affect dump frequency at all.

Second, I cannot confirm this behaviour (with the current develop version - patch_3Aug2022-284-g2f8c370645, or the version I had on my PC - patch_23Jun2022-501-g9061be98c2) for the first input, i.e. LAMMPS correctly writes dump at 0, 50, 60, and 70th timestep.

As for the original input from the zip file, LAMMPS indeed writes output at 0, 50, and 100th timestep. This is explained in the manual for a case when argument of `dump_modify every` is a variable:

> In this case [when a variable is used for dump_modify every], the variable is evaluated at the beginning of a run to determine the next timestep at which a dump snapshot will be written out. On that timestep the variable will be evaluated again to determine the next timestep, etc. 

The same happens when a static value is used, i.e. LAMMPS determines at 0th timestep that the next dump will be at the 50th. At the 50th timestep, the next dump is planned for the 100th timestep. Using `dump_modify every` command does not reevaluate the timestep at which dump will be written. Only later the new value will be used, so after 100th the next dump would be written at the 160th timestep.

You can force your expected behaviour by using `undump` command after each run and then immediately define your dump again (and add `append yes` to your `dump_modify` commands).

**Comment by hoba87** [comment]
Ok if I compare it for example with LAMMPS (7 Aug 2019), LAMMPS (29 Oct 2020) or LAMMPS (29 Sep 2021 - Update 1) I get for the given files the expected output of timesteps at 0, 50, 60, 110. That is changed now for the current stable version as you have checked also. LAMMPS (17 Feb 2022) also shows the "new" behaviour.

The behaviour of the older versions is also what I would expect for the cited manual paragraph:
> the variable is evaluated at **the beginning of a run** to determine the next timestep at which a dump snapshot will be written out

If this change is intended, this should be massively emphasized in the manual, but I would prefer a change back to the old behaviour, because that is much more intuitive.

**Comment by mkanski** [comment]
Well, what's intuitive depends on what you are used to. ;)
For me, the "new" behaviour is more intuitive as the manual also states that:
> The every keyword [...] specifies that the interval between dump snapshots will be set in timesteps. [...] The every keyword also sets the interval value, which overrides the [dump](https://docs.lammps.org/dump.html) frequency originally specified by the dump command.

It wasn't the case with the "old" behaviour as the interval between snapshots is 10 instead of 60 (in your example, after the first use of `dump_modify`). 
There is also an issue when using output from `ave/atom` in dumps. The values weren't correct with the old behaviour. If you use the input script below (with your `data.lammps` file), you will see that the values for `fix ave/atom` in the dump at the 50th and the 60th step are exactly the same, while in reality they shouldn't be. Actually, LAMMPS should error out saying `Dump custom and fix not computed at compatible times`.

Input script:

```
units metal  # energy: eV, time: ps, distance: A

processors * * 1

boundary p p p
atom_style charge
read_data data.lammps

mass 1 15.9994 # O
mass 2 47.867 # Ti
pair_style born/coul/wolf 0.1 8 12
pair_coeff 2 2 31120.428713 0.154 0 5.246913 0
pair_coeff 1 2 16957.65617 0.194 0 12.59259 0
pair_coeff 1 1 11782.84663 0.234 0 30.22222 0

fix ave all ave/atom 1 5 50 vx

dump customDump all custom 50 dump.lammpstrj id type element x y z vx vy vz f_ave
dump_modify customDump element O Ti
dump_modify customDump sort id

timestep 0.0001
fix fixNVT all nvt temp 100000 100000 0.0010000000000000002
run 50
unfix fixNVT

timestep 0.0001
fix fixNVT all nvt temp 100000 3000 0.0010000000000000002
dump_modify customDump every 60
run 10
unfix fixNVT

timestep 0.001
fix fixNVT all nvt temp 3000 300 0.01
dump_modify customDump every 110
run 50
unfix fixNVT
```

**Comment by hoba87** [comment]
Ah ok, I agree that it is more intuitive to define the frequency instead of the total number of timesteps, however with the changed frequency as followed, still I get the 0, 50 and 100 timestep, so I am not able to change it with the dump_modify command. That's what is really unintuitive ;), so yeah, either allow (and fix) it or forbid it by throwing an error.

```
timestep 0.0001
fix fixNVT all nvt temp 100000 100000 0.0010000000000000002
dump_modify customDump every 50
run 50
unfix fixNVT

timestep 0.0001
fix fixNVT all nvt temp 100000 3000 0.0010000000000000002
dump_modify customDump every 10
run 10
unfix fixNVT

timestep 0.001
fix fixNVT all nvt temp 3000 300 0.01
dump_modify customDump every 50
run 50
unfix fixNVT
```

The case with the ave/atom is of course a bug.

**Comment by akohlmey** [comment]
@sjplimp we need your final word here.

My take on this is the following: When the `dump_modify every` command is issued the next step of the dump should become the current step plus the every value and *not* based on the current step when the dump command was issued. For me "dump_modify every 10" would mean "output every 10 steps *from here on*".

A sequence of:
```
dump dumpCustom all custom 50 ...
run 50
dump_modify customDump every 60
run 10
dump_modify customDump every 110
run 50
```
Should output on timesteps 0 and 50 only
A sequence of:
```
dump dumpCustom all custom 50 ...
run 50
dump_modify customDump every 10
run 10
dump_modify customDump every 50
run 50
```
Should output on timesteps 0, 50, 60, and 110.

**Comment by sjplimp** [comment]
The intent of the setting for N in both the dump and dump_modify every commands is the same.
It means: output on every timestep that is a multiple of N
It does not mean: output once every N steps starting from the current step.

The dump doc page is more clear on this (in the text) than than the dump_modify doc page.
But I think both doc pages could be made more clear, especially at the top - I see the confusion.

Thus the first example from Axel above should produce a dump shapshot on steps 0, 50, 60, 110.
The second example on steps 0, 50, 60, 100.

Current LAMMPS doesn't do this for either example.
But the Aug 2020 version from 2 years ago does.

I think this means that we introduced a bug with some refactoring we did a year or so ago to allow dumps to occur on multiples
of "time" (not timestep) for models with variable-size timesteps.  It looks to me that when N changes, the code is
not re-setting the next timestep for output correctly.  Possibly it's waiting until the next dump output (computed prior)
to do that.

**Comment by akohlmey** [comment]
BTW: unrelated to the behavior of the dump_modify command. If the intent is to simply output a single trajectory frame after a run is completed, this would be more conveniently done using the "write_dump" command.

**Comment by akohlmey** [comment]
> It looks to me that when N changes, the code is
> not re-setting the next timestep for output correctly. Possibly it's waiting until the next dump output (computed prior)
> to do that.

That is the case. Commit 673eeff58170e87765ff723e849b473773eaa6ad in PR #3422 restores the described behavior.
