### ISSUE TITLE
[BUG] Variable style format gives false positive in format string conversion check

### ISSUE THREAD

**Issue by hammondkd** [lammps/lammps#3464]
**Summary**
I was playing around with variable style "format" today, which I've never used, and I encountered the error message,
```
ERROR: Incorrect conversion in format string (src/variable.cpp:400)
```
Minimal working example is
```
variable x equal exp(3.2)
variable str format x %f
```

variable.cpp, line 399 looks like
```
    if (!utils::strmatch(arg[3],"%[0-9 ]*\\.[0-9]+[efgEFG]"))
```
This regular expression has the side effect of refusing to use something as benign as "%f" or "%g" as a format string (which seems like it should be allowed). One simple fix is to replace that line with
```
    if (!utils::strmatch(arg[3],"%[0-9 ]*\\.*[0-9]*[efgEFG]"))
```
which makes the decimal point and numbers optional.

I also ran into the following, which I'm less certain of how to fix: if I accidentally print a variable that's not in use (or, as I did earlier today, compile with exceptions on and cause LAMMPS to plow right through the error message from the above issue and then try to print the now not-defined variable), I get this error message:
```
ERROR on proc 0: Substitution for illegal variable undefined (src/input.cpp:650)
Last command: undefined is ${undefined
```
The actual "print" command is missing, and the closing brace is missing in the output). The entire input file to reproduce this is
```
print "undefined is ${undefined}"
```

**LAMMPS Version and Platform**

This is with LAMMPS (15 Sep 2022), though I'm compiling with the "develop" branch (minus 38 commits posted in the last day or two). It happens with 23Jun2022 and 29Sep2021 as well.

Platform: Fedora 36 GNU/Linux with g++ 12.2.1.

**Expected Behavior**

%g, %e, and %f as well as variants such as %8g and so forth should work without problems in the first issue, and the full command including "print" and the trailing "}" character should be present in the second issue.

**Comment by akohlmey** [comment]
> which makes the decimal point and numbers optional.

There are a few more issues at hand and adding a '*' is too liberal, a '?' would be more correct.
I have tracked this down by adding an explicit unittest section on format style variables and found a bunch of issues.
- the regular expression also needs to handle left justified formats (start with '%-') and needs to start with '^' and end with '$' to avoid partial matches on otherwise incorrect format strings
- the format style variable can only operate on equal style or compatible variable types (like python style). the old code would just return a null pointer in case of failure which causes the unexpected "Substitution for illegal variable" errors
- it was not possible to replace the format with a different format by redefining the variable. Code for has has been added
- I've added checks and errors when defining the format style variable and when evaluating them for the connected variable existing and being compatible. this should avoid the substitution error.

**Comment by akohlmey** [comment]
> The actual "print" command is missing, and the closing brace is missing in the output). The entire input file to reproduce this is

This is currently impossible to fix because of how the variable code parses the input. It is segmented by inserting null characters and thus printing the entire string is not possible. While a general rewrite of all string handling to use copies and the `std::string` class is a long-term goal, the variable code was skipped this far because of its complexity.
