### ISSUE TITLE
[Feature Request] Requesting a new bond_style quartic/cut

### ISSUE THREAD

**Issue by TerrySuun** [lammps/lammps#3467]
**Summary**

A new bond_style quartic/cut

**Detailed Description**

In our modeling, to improve an existing molecule model, we need a bond type which behaves similar to LJ potential: the energy goes to zero when r goes to infinity. We need it for specific pair of atoms, not between two pair types, hence adding another pair interaction would involve pairs of atoms that are excluded from this interaction.

So far, bond_style quartic is the closest one but not ideal for two reasons. 1, there's an LJ term in energy of bond_style quartic, which is not necessary and complicates the model. 2, the bond_style quartic bond can be broken but cannot be rebuilt when bond atoms are within short distance again. 

Hence the ideal bond type would be only using the quartic terms in the current bond_style quartic, when r within cutoff. It should take constant energy value (can be U0 as in bond_style quartic) when r is beyond cutoff.  

**Further Information, Files, and Links**

Though this seems like an unusual bond to be useful, it will really make our modeling work easier.

**Comment by akohlmey** [comment]
Please note that most features in LAMMPS are not added by the LAMMPS developers, but contributed by LAMMPS users that had a specific need for a specific feature in LAMMPS. Please see https://docs.lammps.org/Modify.html for more information on how to add features to LAMMPS.

**Comment by akohlmey** [comment]
BTW: What you describe sounds a lot like what pair style `list` implements: https://docs.lammps.org/pair_list.html

**Comment by TerrySuun** [comment]
Yes, indeed. I'll try implement with pair_style list to see if it works for us.

**Comment by akohlmey** [comment]
After re-reading the description, I am thinking that a new bond style is not going to solve the problem, since the atoms may not move beyond the communication cutoff or else there will be bond atom lost errors or the communication cutoff must be extended and the calculation will slow down. Pair style `list` is more suited for the given conditions. If needed an additional functional form can be added.

I will close this issue now. Please submit a new issue if you need changes to Pair style `list` (no promises, however, how quickly they will be done. As already mentioned, it may be simpler that you make the change yourself and then submit a pull request).
