### ISSUE TITLE
Installing the downloaded packages

### ISSUE THREAD

**Issue by amirhajibabaei** [lammps/lammps#3513]
**Summary**

Using `cmake`, I tried to install the packages that need to be downloaded.
Everything worked well, but apparently `cmake install` didn't copy the downloaded packages to the installation prefix.

**LAMMPS Version and Platform**

current stable version: LAMMPS (23 Jun 2022 - Update 2)
OS: linux

**Details**
I used the following command (in `lammps/build` directory) to build and install lammps to the location specified by `$prefix`:
```bash
cmake                                           \
        -D CMAKE_INSTALL_PREFIX=$prefix         \
        -D LAMMPS_MACHINE=$machine              \
        -D BUILD_EXE=yes                        \
        -D BUILD_LIB=yes                        \
        -D BUILD_SHARED_LIBS=yes                \
        -D BUILD_TOOL=yes                       \
        -D BUILD_MPI=yes                        \
        -D BUILD_OMP=yes                        \
        \
        -C ../cmake/presets/oneapi.cmake        \
        -C ../cmake/presets/most.cmake          \
        -C ../cmake/presets/download.cmake      \
        -D PKG_PYTHON=no                        \
        -D PKG_LATTE=no                         \
        \
        -D FFT=MKL                              \
        -D WITH_GZIP=yes                        \
        -D LAMMPS_EXCEPTIONS=on                 \
        \
        ../cmake

make -j 8

make install
```
when tried to test it, this error occurred 
```bash
lmp_mpi: error while loading shared libraries: libkim-api.so.2: cannot open shared object file: No such file or directory
```
I noticed that the downloaded-and-built libs are not copied to `$prefix` (libkim is just the first one that the linker couldn't find).
The liblammps and excecutable are correctly copied, but not the downloaded packages.
I can make it work by adding the build directory to `LD_LIBRARY_PATH` so the issue is just copying to `$prefix`.
Additional info which might be useful is that these packages are present in the `lammps/build` directory in following folders:
```bash
$ ls -d *-prefix/
Eigen3_build-prefix/  kim_build-prefix/  mdi_build-prefix/  plumed_build-prefix/  scafacos_build-prefix/  voro_build-prefix/
```

**Comment by akohlmey** [comment]
@amirhajibabaei the automatic download of "external" packages is primarily intended for testing the functionality with ctest. Whether it is compatible with "make install" depends a bit on the individual package itself. Where it is possible, LAMMPS will in that case of automatic downloads try to request building static libraries and thus the resulting libraries will be included as a copy in liblammps.so. However, that is not the case for all packages. The OpenKIM package is one of them. In this case (and the same is true for Plumed2 for example), it is **not recommended** to use the automatic download, since you will be missing all the required tools and features and support commands and instead should download, configure, compile, and install those packages individually. You should also not be using the download.cmake preset.

**Comment by amirhajibabaei** [comment]
Thank you @akohlmey, this is helpful.
