### ISSUE TITLE
Excuting L.run(0) gives the TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by PNMZR** [lammps/lammps#3518]
**Summary**
When I excuted the following code:

```python
import math
from lammps import PyLammps

L = PyLammps()
L.units("real")
L.atom_style("molecular")

L.boundary("f f f")
L.neighbor(0.3, "bin")

L.dihedral_style("harmonic")
L.read_data("data.dihedral")
L.pair_style("zero", 5)
L.pair_coeff("*", "*")
L.mass(1, 1.0)
L.velocity("all", "set", 0.0, 0.0, 0.0)
L.run(0)
```
The code `L.run(0)` gives the `TypeError: 'NoneType' object is not iterable`.

I wonder if this is a bug, if so, please fix it, thanks.

**LAMMPS Version and Platform**

- LAMMPS version: LAMMPS-64bit-Python-23Jun2022-update2
- Platform: Win11 os

**Comment by akohlmey** [comment]
This is more likely due to a limitation of Windows. This has been a common occurrence with Windows and the PyLammps module over the years. The same script completes without error on Linux.

The general advice is to avoid "PyLammps" for any serious LAMMPS programming because of its shortcomings and performance limitations and use the the simpler and more effective "lammps" module instead. The following adapted version of your input runs well on Windows, too.

```python
import math
from lammps import lammps

lmp = lammps()
lmp.commands_string("""
units real
atom_style molecular

boundary f f f
neighbor 0.3 bin

dihedral_style harmonic
read_data data.dihedral
pair_style zero 5
pair_coeff * *
mass 1 1.0
velocity all set 0.0 0.0 0.0""")
lmp.command('run 0')
```

**Comment by akohlmey** [comment]
I cannot reproduce this on a Windows (virtual) machine either.
