### ISSUE TITLE
Create plane on the XY axis

### ISSUE THREAD

**Issue by iquasere** [lammps/lammps#3537]
Hi there!

I am trying to create a plane of atoms in the XY axis (Z=0), and trying to adjust the ```lattice``` command, since it seems to be the only way to rotate it from it's default XZ axis orientation (Y=0), by setting its orient to [1 0 0] and [0 1 0] faces (this should give me Z=0), if using the (0,0,0) point as part of the plane. This is the script
```
# NUFEB simulation with HETs and GAC

units si
atom_style atomic

boundary p p p

variable x equal 1e-05
variable y equal 1e-05
variable z equal 1e-05

region box block 0 ${x} 0 ${y} 0 ${z}
create_box 1 box

# create plane region
region plane block 0 ${x} 0 ${y} 0 0.0001 side in

lattice     hcp 1 orient x 1 0 0 orient y 0 1 0
# create plane
create_atoms 1 region plane

variable xx internal 0.0
variable yy internal 0.0
variable zz internal 0.0

shell mkdir vtk
dump 1 all vtk 1 vtk/dump*.vtu id type
```
But it gives me the same plane that I get by not adjusting the axis on the ```lattice``` command (note the axis orientation, it should be Z pointing up). 

![imagem](https://user-images.githubusercontent.com/16226371/203766744-d70bc776-5bb2-4e2c-9ef3-6cdc3928a37a.png)

Shouldn't the [100] and [010] faces return me something different from [100] and [101] faces?

**Comment by akohlmey** [comment]
> Shouldn't the [100] and [010] faces return me something different from [100] and [101] faces?

No, what you see is the expected behavior. The location and orientation of the plane is determined by the "region" command. The "lattice" command only provides a grid of possible atom positions. The "create_atoms" command then looks up which of those grid points are within the given region and places atoms there. This is all documented behavior.

If you want to rotate that plane. You can use the "displace_atoms" command *after* you created the plane at the location of the region.

P.S.: since this is not really a bug report or related to the implementation of LAMMPS, this kind of question is better asked in the LAMMPS forum, https://matsci.org/lammps
