### ISSUE TITLE
[BUG] EXTRA-PAIR+MOLECULE break MolPairStyle:coul_slater_long unit test

### ISSUE THREAD

**Issue by hammondkd** [lammps/lammps#3546]
**Summary**

Building LAMMPS using the EXTRA-PAIR package along with the MOLECULE package breaks the MolPairStyle:coul_slater_long unit test. It fails right after PairStyle.plain appears, but I don't actually see output indicating what failed.

**LAMMPS Version and Platform**

3Nov2022 (actually the latest develop branch)

**Expected Behavior**

(successful test)

**Actual Behavior**

119: [==========] Running 8 tests from 1 test suite.
119: [----------] Global test environment set-up.
119: [----------] 8 tests from PairStyle
119: [ RUN      ] PairStyle.plain
1/1 Test #119: MolPairStyle:coul_slater_long ....***Failed   19.09 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  19.10 sec

The following tests FAILED:
	119 - MolPairStyle:coul_slater_long (Failed)
Errors while running CTest

**Steps to Reproduce**

I reproduced this with only the following packages installed: PKG_EXTRA-PAIR, PKG_MOLECULE. It occurs when other packages are installed in addition to these two, but it seems to be an interaction between these two packages.

**Further Information, Files, and Links**

I tried to track down what the problem was with the test, but I am not familiar enough with the pair style tests to know what to look for, and the output from "ctest -R MolPairStyle:coul_slater_long -V" was not helpful in this respect.

**Comment by akohlmey** [comment]
> but it seems to be an interaction between these two packages.

No. It is because the KSPACE package is not present or rather the YAML file for the test is missing a prerequisite entry.

> I tried to track down what the problem was with the test, but I am not familiar enough with the pair style tests to know what to look for, and the output from "ctest -R MolPairStyle:coul_slater_long -V" was not helpful in this respect.

Yes, debugging those tests is a bit complicated because failures are not direct but because the underlying LAMMPS instance fails and there is (yet) no simple intercepting that unless LAMMPS is compiled with -DLAMMPS_EXCEPTIONS=on which is not the default. Once we would make the LAMMPS_EXCEPTIONS=on setting permanent and then there could be exception handling when running LAMMPS class instances.

What you can do now is to enable LAMMPS_EXCEPTIONS when compiling with ENABLE_TESTING on.
Then you can use `ctest -V` to get the exact command line that is executed (and the environment) and then can do:
```
gdb --args ./test_pair_style ../unittest/force-styles/tests/mol-pair-coul_slater_long.yaml
(gdb) catch throw
(gdb) run
```
Which will catch the error execption from the LAMMPS class and you can go up the stack frame and see what the error is:
```
[==========] Running 8 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 8 tests from PairStyle
[ RUN      ] PairStyle.plain

Catchpoint 1 (exception thrown), 0x00007ffff6eae651 in __cxxabiv1::__cxa_throw (obj=0xaf0020, tinfo=0xa2cbb0 <typeinfo for LAMMPS_NS::LAMMPSException>, dest=0x482be0 <LAMMPS_NS::LAMMPSException::~LAMMPSException()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:81
81	  PROBE2 (throw, obj, tinfo);
(gdb) up
#1  0x0000000000410ae3 in LAMMPS_NS::Error::all (this=this@entry=0xaa48f0, file="/home/akohlmey/compile/lammps/src/force.cpp", line=line@entry=646, 
    str="Unrecognized kspace style 'ewald' is part of the KSPACE package which is not enabled in this LAMMPS binary.") at /home/akohlmey/compile/lammps/src/error.cpp:172
172	  throw LAMMPSException(msg);
(gdb) 
```
