### ISSUE TITLE
[BUG] _MLIAP united work broke some kokkos functionaliality 

### ISSUE THREAD

**Issue by bathmatt** [lammps/lammps#3600]
**Summary**
This ebbace403a4f74eebe1dae017045cb2cb801569c commit broke Kokkos/ML-IAP for some tests because it added things to MLIAPData structure but ignored the Kokkos version.  Currently the only example that shows this is the MLIAP Unified example

I am going through and fixing this but to keep things working one needs to make sure data structures in MLIAP match between kokkos and non-kokkos.

**LAMMPS Version and Platform**
develop 

**Expected Behavior**
code runs with migration of data to the host

**Actual Behavior**
seg fault

**Steps to Reproduce**

Modify the following input deck to launch using kokkos 
mliap_unified_lj_Ar.py
37,38c37
< lmp = lammps.lammps(cmdargs=['-k', 'on', 'g', '1', '-sf', 'kk', '-pk', 'kokkos', 'neigh', 'full', 'newton', 'on', '-echo', 'both'])
< 
---
> lmp = lammps.lammps(cmdargs=['-echo','both'])

and just run as normal.

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
Please note that commit ebbace403a4f74eebe1dae017045cb2cb801569c was merged as part of PR #3458 in commit be98b5a168baf1f616f5d2f85b1204971444685a on Mon Sep 26 20:33:17 2022 -0400 which predates Kokkos support in ML-IAP which was merged in PR #3487 on Wed Nov 2 17:13:16 2022 -0400 so clearly the blame is not on the developers of PR #3458 since they would not know about supporting Kokkos.

**Comment by bathmatt** [comment]
Thanks, it was committed between when I forked and pushed.  I appolgize..

**Comment by bathmatt** [comment]
This is fixed in the upcoming PR #3606
