### ISSUE TITLE
[BUG] _Inconsistent Pressure values with shake

### ISSUE THREAD

**Issue by matiasf86** [lammps/lammps#3673]
Hello LAMMPS developers 

I am doing water SPCE simulations and I am getting weird values in the energies, pressure and enthalpy.
When I run 500spce water molecules with pair style lj/cut/coul/long with shake and without any time integration I get inconsistent thermodynamics values between Step 0 and the next ones 
I need to compare the energies or enthalpy of step zero with the other steps in my simulation and also I need to use shake for the water molecules  

My lammps version is LAMMPS (24 Mar 2022)

**Expected Behavior**

As I am not integrating my system I expect to get the same thermodynamic out for all steps

**Actual Behavior**

I get different thermodynamic output between step zero and the other ones I show the output

Step         TotEng         PotEng         KinEng        Enthalpy        Press           Temp          E_pair         E_vdwl         E_coul         E_long    
         0  -4659.2821     -5540.2879      881.00583     -4863.5386     -911.62376      295.85505     -5540.2879      1034.3093      22018.721     -28593.319    
         1  -4659.2256     -5540.2314      881.00583     -4719.1351     -267.384        295.85505     -5540.2314      1034.3091      22018.778     -28593.319    
         2  -4659.2256     -5540.2314      881.00583     -4719.1351     -267.384        295.85505     -5540.2314      1034.3091      22018.778     -28593.319

The difference in pressure stands out  -911.62376 step 0  vs   -267.384 the next steps, this translates in a very different enthalpy

Also, which is the correct value ?

When I do not use shake the expected behavior is observed 

Step         TotEng         PotEng         KinEng        Enthalpy        Press           Temp          E_pair         E_vdwl         E_coul         E_long    
         0  -4659.2726     -5540.2785      881.00583     -619.84088      18028.514      197.17091     -5540.2879      1034.3093      22018.721     -28593.319    
         1  -4659.2726     -5540.2785      881.00583     -619.84088      18028.514      197.17091     -5540.2879      1034.3093      22018.721     -28593.319    
         2  -4659.2726     -5540.2785      881.00583     -619.84088      18028.514      197.17091     -5540.2879      1034.3093      22018.721     -28593.319

**Steps to Reproduce**

With one step it suffices  to see the inconsistency 

**Further Information, Files, and Links**

i attached the input files to reproduced the behavior and the log output with shake and without 

Thanks
Matias 
 
[test_run_input.txt](https://github.com/lammps/lammps/files/10889447/test_run_input.txt)
[500wat.txt](https://github.com/lammps/lammps/files/10889448/500wat.txt)
[log_no_shake.txt](https://github.com/lammps/lammps/files/10889449/log_no_shake.txt)
[log_shake.txt](https://github.com/lammps/lammps/files/10889450/log_shake.txt)

**Comment by akohlmey** [comment]
@matiasf86 This behavior is due to a peculiarity of the SHAKE algorithm. If you study the documentation, you will see that it is designed to be use with the regular Verlet algorithm where you start from the positions at the current and the previous time step. The velocities are then approximated. LAMMPS uses a Verlocity Verlet integration and thus some missing data needs to be generated/collected by the fix. This is initialized at the first step and then can be used for subsequent steps without a problem. Thus effectively the computed pressure contributions from fix shake are not correct on the zero-th time step due to missing data, but will be correct on subsequent steps.

You can see the difference by either using `fix_modify 000 virial no` or setting the velocity for all atoms to 0.0 `velocity all set 0.0 0.0 0.0`. There there is only a small difference in pressure between the first and second step because the constraints are not yet properly fulfilled on the zero-th step due to the conversion from (slightly truncated) numbers read in from the data file versus the full precision stored in memory.

Since you are not propagating the atoms, but the timestep is set to the default value, the estimator in fix shake will assume regular timestepping and thus the estimate is "better" on step 0 than on subsequent steps. You can see that by adding fix nve to your input.

**Comment by matiasf86** [comment]
Hello Axel, 
Thank you for the explanation !, 
I will take this into account and find a workaround for what I want to do.
