### ISSUE TITLE
[Feature Request] Hybrid Bond coefficients are unextractable from a simulation

### ISSUE THREAD

**Issue by jamesdalg** [lammps/lammps#3741]
**Summary**

"Unlike other bond styles, the hybrid bond style does not store bond coefficient info for individual sub-styles in a [binary restart files](https://docs.lammps.org/restart.html). Thus when restarting a simulation from a restart file, you need to re-specify bond_coeff commands." https://docs.lammps.org/bond_hybrid.html

This seems easy enough to deal with when one pre-specifies all the bonds, but it becomes a bit tricky when using replicate, when bonds are added, when bonds are deleted in a certain region, etc. Right now I have a huge molecule that I'm dealing with (40k atoms) and it just becomes incredibly tedious to hand code everything.  I have had a simulation that previously used 27M atoms and... it just becomes impractical. LAMMPS is supposed to be "large scale" ("Large-scale Atomic/Molecular Massively Parallel Simulator"), but the fact that hybrid bonds have to be hard coded really makes it difficult to do so when using multiple bond types.

**Detailed Description**

Essentially, one cannot write hybrid style coefficients to disk. These styles are becoming common and it would really help if they were made more usable on longer (repeated) runs.
As a workaround... if one could just use write_coeffs, write_data, or something else to get the bonds coefficients out, that would be almost sufficient as a bit of scripting could fill in the gaps. Right now, there's no way to get the bond coefficients out of lammps after a hybrid style puts them in and modifies them.

**Comment by akohlmey** [comment]
> Right now I have a huge molecule that I'm dealing with (40k atoms) and it just becomes incredibly tedious to hand code everything.

This sounds like you are doing something incorrectly.

The number of bond types is usually very small and independent from the system size. If you assign a different bond type for each bond, then you are either misunderstanding something or your use case is *very* extreme and unusual.

Also, using a hybrid bond style is very unusual. Most force fields require a consistent bond style and then the hybrid limitation is not used. The hybrid bond style is only needed when mixing different force fields and the valid applications of that use case are very limited.

>  but it becomes a bit tricky when using replicate

The replicate command does *not* affect the number of bond types. So your concern does not apply

> when bonds are added, when bonds are deleted in a certain region

Same as before, neither of these commands change the total number of bond types (this is locked in when creating the simulation cell). It is perfectly valid to have bond types for which no bonds exist. It is not possible to add bonds with a type that did not exist before. And when the total number of bond types cannot change, you can just input the bond coefficients the exact same way as before.

**Comment by jamesdalg** [comment]
Every bond is defined with precise coefficients, a priori, in this published simulation. Every bond is a different type, using the same set of hybrid styles for each bond in a large crystal structure. When you replicate thousands of defined bonds, you have to redefine them again in thousands of lines and then link them precisely to create a polymer.  Times are changing and simulations are getting bigger and more complex with greater computing power. I am only asking that LAMMPS keep with the times.

**Comment by akohlmey** [comment]
> Every bond is defined with precise coefficients, a priori, in this published simulation.
The fact that something is published doesn't make it less unusual. Lots of things get published these days...

You need to provide more tangible examples and scientific justification to make a convincing case. For example, in traditional force fields, the parameters of bonds are inferred from the participating atom types. That would not apply for your specific case, so how are the bond parameters derived then?

That said, it seems to me that using bond style hybrid is not the proper solution for this kind of use case, but rather writing a custom bond style that supports the required internal formats and possibly includes a method of deriving the bond parameters, if they are geometry dependent.

> I am only asking that LAMMPS keep with the times.

Sorry, but before this becomes a trend worth paying attention to, there has to be more than one person with a specific need. I understand that you personally have a different perspective, since this is your work, but that doesn't change how the vast majority of people set up and conduct simulations and I don't see any indication that that is changing.

**Comment by stanmoore1** [comment]
I agree with @akohlmey that writing a custom bond style that can store data in the restart file may be a good way forward, need to understand more about the model...

**Comment by akohlmey** [comment]
Since you are talking about polymers here, one more comment. The whole point of a polymer is that you are repeating monomer units. So you have the *same* kind of atoms, bonded to each other ib (mostly) the *same* way  and thus creating (mostly) the *same* environment and thus force fields use the same atom types and thus the same bond types.

Let's take a very simple example of a hydrocarbon polymer, say decane. So you have 10 carbon atoms (2 at the ends in CH3 configuration, and 8 in the middle in CH2 configuration), 2 CH3-CH2 sigma bonds, 7 CH2-CH2 sigma bonds, and 22 (= 8*2 + 2*3) C-H sigma bonds. So you need only 3 atom types (HC, CH2, CH3) and 3 bond types CH3-CH2, CH2-CH2, CH2/3-HC). At least that is how it would work for almost all force fields I know. Some use slightly more fine grained classifications, others less (e.g. the difference between CH3 and CH2 carbons is only in the partial charge but not in the LJ parameters and hence bond parameters are not affected). In a few cases there are different types, but the parameters are the same. If I now replicate the system to have a second decane molecule, that would have the exact *same* parameters, of course, so why would I need to apply new bond types?

So I am extremely curious about how one can motivate a force field where every bond needs a different set of parameters and - most importantly - how those parameters are then determined.

**Comment by jtclemm** [comment]
> Every bond is a different type

In applications where every bond is its own "type" and needs to store persistent data on a per-bond basis, LAMMPS provides a history feature for custom bond styles (https://github.com/lammps/lammps/blob/develop/src/fix_bond_history.cpp). This is the framework of the BPM package where every bond saves its unique initial length to define an equilibrium length and the actual type of the bond is reserved for specifying universal quantities like stiffness, failure criteria, etc. Using this fix, there shouldn't be any significant limitations on how many unique bonds can be supported (I've run up to ~10^7-10^8). Data can also evolve with time and is automatically written/read from restart files.

I'm curious what the exact model is.

**Comment by akohlmey** [comment]
@jamesdalg to summarize:
- If it was easy to support restarting for hybrid styles, it would have been implemented long ago. But in order to support writing complete restarts, additional functionality would be needed that would have to be added to *all* styles. The same applies to writing the Coeff sections for data file. Similarly, write_coeffs uses those data file functions to write out a temporary file and then post-processes that to follow the input file syntax instead.
- The argument about using scripting applies to the current situation as well, since you must provide the input somehow, so why not use that information?
- In order to get more specific assistance, we need to know more about the model. There are, obviously, alternate approaches, but we cannot provide any specific advice without understanding the model.

**Comment by akohlmey** [comment]
Closed for lack of feedback.
