### ISSUE TITLE
[BUG] _Cannot use periodic introduction when using Reaxff_

### ISSUE THREAD

**Issue by WildonCao** [lammps/lammps#3748]
**Summary**

Cannot use periodic introduction when using reaxff. 
Lammps will report an error: "ERROR: Must not have electric field component in direction of periodic boundary when using charge equilibration with ReaxFF. (src/REAXFF/fix_qeq_reaxff.cpp:413)"

**LAMMPS Version and Platform**
LAMMPS Version: 
Platform: Ubuntu Linux

This is the file I used for testing：
[test.zip](https://github.com/lammps/lammps/files/11300095/test.zip)

**Comment by akohlmey** [comment]
This is the desired behavior.

When you apply a constant field, then your potential decreases or increases across the entire system. This leads to an unphysical inconsistency with periodic boundaries since at some point the potential would have to "jump up" to to get back to the value where the periodic image starts, that would lead to a discontinuity in the force. Thus an electric field can only be applied along non-periodic directions.

**Comment by WildonCao** [comment]
Thanks.
