### ISSUE TITLE
[BUG] Using TALLY package with GPU yields all zeros

### ISSUE THREAD

**Issue by M-S-Jacobs2727** [lammps/lammps#3752]
**Summary**

When running an example script with compute pe/tally, compute pe/mol/tally, and compute pe/atom, they all give identical results when running on the CPU. When I run them with the GPU, the first two give results of "0" for every timestep, but compute pe/atom is still correct.

**LAMMPS Version and Platform**

LAMMPS (28 Mar 2023 - Development)
Linux, ppc64 (Summit, ORNL)
GPU: NVidia Tesla V100

**Expected Behavior**

I expect that the CPU and GPU runs should give similar results.

**Actual Behavior**

The GPU version yields "0".

**Steps to Reproduce**

I've altered the in.melt example to show the issue. I use `atom_style molecular` and set the molecule IDs to test pe/mol/tally as well.
See attached script and log file for the CPU and GPU runs.

[in.melt.txt](https://github.com/lammps/lammps/files/11326981/in.melt.txt)

CPU run: `mpirun -n 1 lmp -i in.melt`
[cpu_log.txt](https://github.com/lammps/lammps/files/11326979/cpu_log.txt)
GPU run: `mpirun -n 1 lmp -i in.melt -sf gpu -pk gpu 1`
[gpu_log.txt](https://github.com/lammps/lammps/files/11326980/gpu_log.txt)

**Further Information, Files, and Links**

Interestingly, when testing the other computes in the TALLY package, I noticed that `compute heat/flux/tally` gives the same results when outputting its global vector in either the CPU or GPU run.

**Comment by akohlmey** [comment]
The GPU package compute functions do not call `Pair::ev_tally()` and thus *none* of the TALLY package compute styles can produce any useful output with GPU acceleration (same for KOKKOS, BTW). It would be a performance killer anyway, since `Pair::ev_tally()` is called for every pair of atoms and thus would require extremely frequent GPU to host data transfers and would interfere with GPU parallelization.

**Comment by stanmoore1** [comment]
Seems like the code through throw an error though if using TALLY with GPU or KOKKOS packages, if they are returning all zeros.

**Comment by akohlmey** [comment]
> Seems like the code through throw an error though if using TALLY with GPU or KOKKOS packages, if they are returning all zeros.

For Kokkos there is already a test and it refuses any use of the compute styles with an error. For other cases, it is not so simple, since there can be a mix of accelerated and non-accelerated pair styles in a hybrid pair style, and (some) data still tallied.

PR #3753 implements a mechanism to print a warning if no data has been tallied at all.
