### ISSUE TITLE
[Feature Request] USER-DRUDE Add further criteria to identify drude core-particle pairs

### ISSUE THREAD

**Issue by Alexandrina-Chen** [lammps/lammps#3772]
**Summary**

Currently, the fix_drude uses the assumption that, "drude particle only bonds to its own drude core, therefore the only 1-2 neighbor of one drude particle is its corresponding core", to construct the "drudeid" array, which stores the drude pairs. For the drude cores, the assumption is similar that only one drude particle bonds to a drude core. A recent JCTC paper [1] suggests that splitting the non-Coulombic force between the Drude core and shell can avoid spurious polarizations in the absence of an electric field. This splitting will cause a drude particle bonds to more than one atom, therefore above assumption will no longer work and leads to the wrong identification of drude pairs. I assume that adding another judgement criteria, like distance, would help solve this problem.

**Detailed Description**

In the current USER-DRUDE implementation (like most other MD softwares), it only puts Coulombic interactions on the drude particles, and assign the entirety of the non-Coulombic forces (like lj, bond forces, etc...) to the cores. Therefore, it is straightforward and reasonable to use the 1-2 neighbor of the drude particles to find the drude core-particle pairs. However, the paper [1] proves that such treatment will cause spurious polarizations, even in the absence of an electric field. They propose that the non-Coulomb forces and atomic charge must be divided between the core and the particle weighted by their mass to eliminate the spurious polarizations. Another benefit for this symmetrizing is that the choice of the mass of drude particles will be more flexible, and can even possible to  explicitly polarize hydrogen atoms. 

This symmetrizing will add bonds between cores and particles that don't belong to the same drude pair (like, i_core bonds to j_particle). This will cause wrong drudeid construction. My intuitive solution is,  for drude particles, loop over all 1-2 neighbors of it and calculate the distance between the particle and the neighbors. Due to the fact that the drude particle and core should be quite close (typically less than 0.2 angstrom), it is maybe possible to use this additional distance criteria (make 0.3 angstrom to avoid any extreme condition) to help correctly identify the drude pairs. For the drude cores, the procedure is similar, loop over all drude particle 1-2 neighbors and calculate the distance. This modification should not affect traditional drude force fields, since such distance criteria is always true. It is possible that there are other more reasonable solutions to implement the symmetrizing drude models. I really appreciate any suggestions and ideas. If there is any workaround, that I didn't realize, to implement this idea without changing the source code, I apologize in advance. 

I am not familiar with c++, therefore I am afraid that I can't implement this idea myself. I appreciate any help!

**Further Information, Files, and Links**

[1] [Amro Dodin* and Phillip L. Geissler, J. Chem. Theory Comput. XXXX, XXX, XXX−XXX](https://doi.org/10.1021/acs.jctc.3c00278)

**Comment by agiliopadua** [comment]
I've read the paper you mention. As I understood, the idea is to also displace the core-core interaction potential to avoid a spurious polarisation effect. However, this effect seems to be very small. The authors of the paper use very simple, extreme model systems:
- the mass of the shell (Drude) and core are the same; in most applications the Drude mass is 0.4 u with most atoms being 12 u or above (1/30); in Fig. 3A we see that the difference between the traditional Drude model and the new one vanishes for mass ratios under 1/4; 
- the "molecules" are diatomic with only 1 polarizable atom, not representative of most molecular systems studied using polarizable force fields where interactions between neighbouring polarizable atoms need to be carefully handled;
- equipartition between center-of-mass and intramolecular degrees of freedom is handled correctly with temperature-grouped NH thermostats [10.1021/acs.jpclett.9b02983] while keeping relative Drude degrees of freedom near 1 K; I don't see how the small core displacement relates to this, and anyway temperatures are identical to both models in the paper, Fig. 4C.

In my opinion, the variation of the Drude induced dipole model proposed in the paper is unnecessarily complicated for little or no benefit in practical systems. It is already difficult to make polarizable force fields robust in some cases (strong H-bonds or small, densely charged ions) without adding more complexity and computational cost.

Besides, I don't understand how the tiny displacement of the core interaction potential requires that bonds be formed between Drude particles and cores that do not belong to the same atom. Your suggestion to introduce such bonds does not make sense to me: each Drude particle represents the center of negative charge (the electron cloud) on each atomic site, its slight displacement from the core being determined by one clear physical quantity: the polarisability of the atom. I cannot understand the physical sense of having a Drude particle binding to another atom. If these bonds are labile then are we talking of a "reactive force field" where the "electrons" move around in molecules? Creating and removing such bonds at each timestep will imply a huge overhead and complicate the code very significantly.

The present infrastructure to implement a Drude induced dipole model is already quite involved (special neighbour relations, short-range damping functions, specific thermostats, etc.) and it seems to me that the effort of implementing your "intuitive solution" is not worth it.

You can try it yourself, of course, and contribute a new package, but please leave the Drude induced dipole model as it is in terms of the core-Drude bonds, since it is a productive research tool being used by a wide community to study a variety of systems. Improvements in short-range damping/smearing functions, in integrators, and in porting to GPU are always welcome!
