### ISSUE TITLE
[BUG] Termination after a raised MPIAbortException at KSPACE/pppm

### ISSUE THREAD

**Issue by amirhajibabaei** [lammps/lammps#3773]
**Summary**

When using the python interface with `kspace pppm` with `mpirun`, sometimes an exception is raised with the following message:
```
lammps.core.MPIAbortException: 'ERROR on proc 7: Out of range atoms - cannot compute PPPM (src/KSPACE/pppm.cpp:1839)\nLast command:'
```
The issue is that this exception is raised on only one of the parallel processes and other processes just hang; probably waiting for a communication with the failed process. This causes the job to drain the resources without doing anything unless cancelled manually.

**LAMMPS Version and Platform**

version: 20230328 
platform: ubuntu

I am using the conda installation from conda-forge. I should note that I manually switched `fftw` from  `nompi` to `mpi_openmpi` which may be related to the issue. Relevant lines of output of `conda list` shows:
```
lammps                    2023.03.28      py310h06d3ab3_openmpi_1    conda-forge
fftw                      3.3.10          mpi_openmpi_h4a81ba8_7    conda-forge
mpi4py                    3.1.4           py310h6075a6b_0    conda-forge
...
```

**Expected Behavior**

Once an exception or any other kind of failure happens, lammps should fully terminate or there should be a mechanism for catching the error on all processes.

If the issue is related to the version of `fftw` (`nompi` vs `mpi_*`) a documentation is needed.

**Actual Behavior**

After a `lammps.core.MPIAbortException` on a mpi processes (at least at `src/KSPACE/pppm.cpp:1839`), other processes hangs without releasing the resources. I have looked at https://docs.lammps.org/Python_error.html and it didn't work (Either `Exception` or `MPIAbortException` occurs only on one process).

**Steps to Reproduce**

It should be reproducible with `coul/long` using  `kspace_style pppm` long-range solver. Perhaps if the charged particles come too close or atoms move too fast so that they are not communicated on time.

**Comment by akohlmey** [comment]
This exception happens because your simulation has entered a bad state. There is no recovery for that.
And since there is no mechanism in MPI to forward exceptions across the communicator, the exception is only raised in on MPI process. The website https://docs.lammps.org/Python_error.html shows how to *catch* such an exception, but it is up to your Python code that calls LAMMPS to process it (the example shows "pass" which does nothing). The only way to completely terminate your calculation would be to call MPI_Abort() yourself through the `mpi4py` module, since LAMMPS cannot do it for you.

This is not something that can be fixed on the LAMMPS side. It is a case of GI-GO.

**Comment by stanmoore1** [comment]
@amirhajibabaei To put it in a different way, your simulation blew up and atoms moved too far in a single timestep. You may need to relax the system through energy minimization or otherwise figure out why you got such large forces. This error has been discussed many times in the past--could try searching through the mail list/MatSci archives. If you need more help, please start a thread on MatSci: https://matsci.org/c/lammps/40. Thanks.

**Comment by amirhajibabaei** [comment]
@stanmoore1 My main issue was more about "graceful exit" rather than the error itself. More precisely, I wanted the job to entirely stop when the exception is raised. As Axel pointed out, this should be done using mpi4py and somehow killing the  remaining/hanging processes. Nonetheless, the "kspace out of range atoms" error is tricky. In my case it occurs sometimes 10 nanoseconds into the simulation when it is already well equilibrated. I suspect this might be related to communication cutoff etc. If the issue persists I will start a thread on MatSci. Thanks!
