### ISSUE TITLE
Incorrect format of some .tersoff files in the potentials/ directory?

### ISSUE THREAD

**Issue by romangroger** [lammps/lammps#3774]
**Summary**

There seems to be an issue with some Tersoff files in the potentials directory. The manual says that the first atom is the central atom in the three-body interaction (i), the second is the atom bonded to it (j), and the third (k) is the atom that influences the i-j bond. Therefore, if we have a line in the potential file with elements X Y * (* is X or Y), the parameters in this line should be m_XY, gamma_XY, etc.  Of course, the parameters n, beta, lambda2, B, lambda1 need to be written only in the line with *=Y (i.e., when the second and third elements are the same). I have noticed that some potential files include the coefficients according to the first and THIRD element, i.e. for the X * Y line, they give m_XY, gamma_XY, etc. See an example below.

**LAMMPS Version and Platform**

LAMMPS (3 Aug 2022)
Linux 5.4.0-31-generic

**Details**

GaN.tersoff file (two lines with the same first and second elements -> coefficients should be the same and they are not):
```
Ga N  N  1.0 0.001632 0.000 65.20700 2.82100 -0.518000 1.0 1.0 2.63906 3864.27 2.90 0.20 2.93516 6136.44
Ga N  Ga 1.0 0.007874 1.846 1.918000 0.75000 -0.301300 1.0 0.0 0.00000 0.00000 2.87 0.15 0.00000 0.00000
```

GaN.tersoff file (two lines with the same first and third elements -> coefficients would in general be different and they are the same):
```
Ga N  N  1.0 0.001632 0.000 65.20700 2.82100 -0.518000 1.0 1.0 2.63906 3864.27 2.90 0.20 2.93516 6136.44
Ga Ga N  1.0 0.001632 0.000 65.20700 2.82100 -0.518000 1.0 0.0 0.00000 0.00000 2.90 0.20 0.00000 0.00000
```

In my opinion, this is the correct template for the .tersoff files when two elements are used. Please, correct me if not.

```
# first and second are X
X X X m_XX gamma_XX lambda3_XX c_XX d_XX h_XX n_XX beta_XX lambda2_XX B_XX R_XX D_XX lambda1_XX A_XX
X X Y m_XX gamma_XX lambda3_XX c_XX d_XX h_XX n_XX beta_XX 0.0        0.0  R_XX D_XX 0.0        0.0

# first and second are Y
Y Y Y m_YY gamma_YY lambda3_YY c_YY d_YY h_YY n_YY beta_YY lambda2_YY B_YY R_YY D_YY lambda1_YY A_YY
Y Y X m_YY gamma_YY lambda3_YY c_YY d_YY h_YY n_YY beta_YY 0.0        0.0  R_YY D_YY 0.0        0.0

# first and second are X, Y
X Y Y m_XY gamma_XY lambda3_XY c_XY d_XY h_XY n_XY beta_XY lambda2_XY B_XY R_XY D_XY lambda1_XY A_XY
Y X X m_XY gamma_XY lambda3_XY c_XY d_XY h_XY n_XY beta_XY lambda2_XY B_XY R_XY D_XY lambda1_XY A_XY
X Y X m_XY gamma_XY lambda3_XY c_XY d_XY h_XY n_XY beta_XY 0.0        0.0  R_XY D_XY 0.0        0.0
Y X Y m_XY gamma_XY lambda3_XY c_XY d_XY h_XY n_XY beta_XY 0.0        0.0  R_XY D_XY 0.0        0.0
```

**Comment by hammondkd** [comment]
Just so @athomps knows: If I recall correctly, there is a discrepancy between the Tersoff potential and the "bond order potential" that some use that is equivalent to it. We ran into this a few years ago when someone stood up at a conference and asked us why we were using a particular potential, which they claimed was massively wrong; turns out, the implementation that group was using was backwards (reversing the j and k indices), so they made up a new implementation that had the indices reversed. The potential they published gave me way-off numbers when I implemented it, and the only way I figured it out was to get the original file from them (which had the indices reversed), so...yeah, there's a discrepancy somewhere, but I'm not 100% certain it's LAMMPS's problem.

**Comment by romangroger** [comment]
Of course it is not a LAMMPS's problem. The format is described clearly in the documentation, it just seems that people are not reading it carefully. The problem is when someone fits the potential using LAMMPS with the wrong order of i, k, j,  because just swapping j<->k may result in a completely wrong parameterization. I checked that nothing much happens in the case of GaN.tersoff, but this may not be the case in general.

**Comment by athomps** [comment]
This is not a LAMMPS problem, it is simply a matter of which "typing rules" a particular parameterization of Tersoff is using.  The code input was set up by me in this rather long-winded manner so that all possible typing rules (or no rules) could be supported. For the input line `X Y Z`, one person might type the parameter values on X and Y, another on X and Z, and another might have different values for all possible X, Y, and Z. These are all valid choices.  The hard part, as @hammondkd noted, is that it is easy to make a mistake (even when writing a paper describing a potential), and so careful testing, verification, and reproduction of key published results is especially important.

**Comment by athomps** [comment]
Since no one has refuted my claim that this is not a bug in LAMMPS, I recommend closing this issue.

**Comment by lmhale99** [comment]
Hey, sorry for bringing this post back from the dead. I'm working on trying to build implementations for other published Tersoff potentials. How LAMMPS handles the parameters does seem to give all possibilities, but it is a bit unintuitive in some aspects.
- gamma and beta are technically variations of the same parameter, with gamma being defined ternary and beta binary.
- For the old Tersoff potentials that define binary interactions, these are typically represented in the LAMMPS ternary format according to i-k pairs.
- But the actual binary parameters seem to be applied on the i-j pairs. Or, at the very least beta is.
- Reproducing beta using gamma requires setting values on the i-j pairs despite the other ternary parameters being set on i-k. 

Now for the real predicament. I'm not sure that GaN.tersoff is correct.
- The versions in LAMMPS, NIST IPR, and OpenKIM all use gamma with values set to i-k pairs.
- Changing gamma to i-j pairs (or equivalently using beta) does not change the B1, B3, or B4 structure predictions. I think this is because there are only ABB interactions in those bulk phases and are thus unaffected by swapping i-j and i-k.
- Predictions for the B2 structures are different between the i-j and i-k variations. They are also, unfortunately, different from the values reported in the paper.  So I don't know which one, if either, is a correct representation of the original publication.
