### ISSUE TITLE
[BUG] Unable to enable hipFFT-backend with KSPACE + Kokkos with cmake

### ISSUE THREAD

**Issue by skyreflectedinmirrors** [lammps/lammps#3775]
**Summary**

We noticed that our build was not utilizing the hipFFT backend for KSPACE.

```
-- Kokkos Architecture: VEGA90A
-- <<< FFT settings >>>
-- Primary FFT lib:  KISS
-- Using double precision FFTs
```

**LAMMPS Version and Platform**

Develop from ~ a month ago: 56b5291529f197dbabec397dbaa66939be6f562a
MI-200 system w/ ROCm 5.4.3

**Expected Behavior**

We want to be able to enable the hipFFT backend for KSPACE.

**Actual Behavior**

The issue (seems) to stem from a lack of the `KSPACE`'s package awareness of `Kokkos`, and vice-versa.
Namely:

https://github.com/lammps/lammps/blob/fceff845c7ae434ce8bfe1ca6adf1313e67af2dd/cmake/Modules/Packages/KSPACE.cmake#L13

Sets the available choices for the "FFT" variable to be FFTW, KISS, and MKL.

Meanwhile:

https://github.com/lammps/lammps/blob/fceff845c7ae434ce8bfe1ca6adf1313e67af2dd/cmake/Modules/Packages/KSPACE.cmake#L11

sets the default FFT backend to "KISS" in the case that FFTW is not found, while

https://github.com/lammps/lammps/blob/fceff845c7ae434ce8bfe1ca6adf1313e67af2dd/cmake/Modules/Packages/KSPACE.cmake#L15

enforces the FFT selection to be in the FFTW/KISS/MKL list.

Finally:

https://github.com/lammps/lammps/blob/fceff845c7ae434ce8bfe1ca6adf1313e67af2dd/cmake/Modules/Packages/KOKKOS.cmake#LL139C13-L139C16

Selects `hipFFT` IFF the FFT choice is not KISS.  It appears to me that the same problem would prevent selection of the cuFFT backend as well, but I haven't dug into it as far.

**Steps to Reproduce**

from within lammps/build:

```
cmake -DPKG_KOKKOS=on    \
      -DPKG_KSPACE=on   \
      -DKokkos_ENABLE_HIP=on \
      -DKokkos_ENABLE_SERIAL=on \
      -DCMAKE_CXX_COMPILER=$(which hipcc) \
      -DKokkos_ARCH_VEGA90A=ON  ../lammps/cmake

...
-- <<< FFT settings >>>
-- Primary FFT lib:  KISS
-- Using double precision FFTs
-- Using non-threaded FFTs
-- Kokkos FFT: KISS
```

Or

```
cmake -DPKG_KOKKOS=on    \
      -DPKG_KSPACE=on   \
      -DKokkos_ENABLE_HIP=on \
      -DKokkos_ENABLE_SERIAL=on \
      -DCMAKE_CXX_COMPILER=$(which hipcc) \
      -DFFT=HIPFFT \
      -DKokkos_ARCH_VEGA90A=ON  ../lammps/cmake
...

CMake Error at Modules/LAMMPSUtils.cmake:18 (message):
  

  ########################################################################

  Invalid value 'HIP' for option FFT

  

  Possible values are:

  * KISS

  * FFTW3

  * MKL

  ########################################################################
Call Stack (most recent call first):
  Modules/Packages/KSPACE.cmake:15 (validate_option)
  CMakeLists.txt:525 (include)

```

**Further Information, Files, and Links**

I think this is a bit of a design flaw in the current cmake.  Basically, KSpace is included here: https://github.com/lammps/lammps/blob/fceff845c7ae434ce8bfe1ca6adf1313e67af2dd/cmake/CMakeLists.txt#L525

While, Kokkos gets included about a 100 lines later:

https://github.com/lammps/lammps/blob/fceff845c7ae434ce8bfe1ca6adf1313e67af2dd/cmake/CMakeLists.txt#L674

This means that there's no way for us to find whether hipfft/cufft are valid targets (on older ROCm installs at least, this was a problem), which is done by Kokkos:

https://github.com/lammps/lammps/blob/fceff845c7ae434ce8bfe1ca6adf1313e67af2dd/cmake/Modules/Packages/KOKKOS.cmake#L139

The easiest solution I can see is before including KSpace, we check if Kokkos is enabled.
If so, we set (e.g.,) a KOKKOS_FFT_VALUES variable (which defaults to "") to include cuFFT / hipFFT.
Then the KSpace validation check checks whether the FFT value provided is in either KOKKOS_FFT_VALUES _or_ FFT_VALUES.
Finally, in the Kokkos package we validate that the selected FFT value works for the backend selected (i.e., can't select cuFFT for HIP, and vice versa, and that hipFFT exists if selected).

Or, it's entirely possible I've missed something obvious here!

**Comment by skyreflectedinmirrors** [comment]
cc: @stanmoore1 -- migrated from slack

If you agree, I can mock up a CMake solution as described in the last paragraph above

**Comment by akohlmey** [comment]
> Or, it's entirely possible I've missed something obvious here!

You *must* not set -DFFT to anything other than an FFT that is supported on the CPU.

The proper solution would be to have a -DFFT_KOKKOS option that would default to KISS, but could be changed to other detected GPU accelerated FFTs (and *must* not be set to FFTW or MKL), if also there is the corresponding Kokkos device architecture enabled. This kind of setting and the corresponding checks should be added to cmake/Modules/Packages/KOKKOS.cmake

The GNU make build works around this issue by a) not checking for valid input and b) allowing users to set multiple -DFFT_<type>) settings.

You will get cuFFT with KOKKOS, if you select FFTW or MKL for the non-KOKKOS fft setting. I would assume the same is true for the HIP backend.

**Comment by akohlmey** [comment]
On second thought, if you want KISS for CPU and non-KISS FFTs for KOKKOS, you may also need to change source code *and* do some thorough testing for all the different settings and permutations so that the CMake scripts do not allow invalid combinations or compile non-functional code etc.

**Comment by skyreflectedinmirrors** [comment]
Ah, ok -- yeah, I can get by with the FFTW hack in the short term, but I agree that a `FFT_KOKKOS` option would be the solution.

**Comment by hagertnl** [comment]
I came across this GitHub issue as I've been dealing with the same problem for a long time now and have been using the Makefile-based builds instead, which don't do input validation...

One thing I notice with the FFTW workaround (to be clear, set FFT=FFTW3 and then the KOKKOS.cmake file will try to find hipfft, since FFT is not KISSFFT) is that the FFT types are in if/elif/elif/... order, with the priority being FFT_MKL, FFT_FFTW3, FFT_CUFFT, then FFT_HIPFFT. So even if `-DFFT_HIPFFT` is defined, if `-DFFT_FFTW3` is defined too, I believe that would take priority. For example, when I set FFT=FFTW3 in CMake, I would get the following compilation command:
`/opt/rocm-5.5.1/bin/hipcc -DFFT_FFTW3 -DFFT_FFTW_THREADS -DFFT_HIPFFT`
which seems to fall into this exact case. LAMMPS would still use FFTW3 in this case.

It sounds like there's still some red tape with the different settings and permutations that's blocking the addition of an `FFT_KOKKOS` option, or am I understanding that wrong? I am happy to help try to move this forward, if an extra set of hands is helpful.

What it seemed like a possible solution could be to use `ifdef FFT_KOKKOS_x` instead of `ifdef FFT_x` for all files that use those defines in src/KOKKOS. Then, `-DFFT_x` and `-DFFT_KOKKOS_x` command-line flags can peacefully coexist - the files in src/KSPACE will use `-DFFT_x` for CPU-based FFTs, and the files in src/KOKKOS will use `-DFFT_KOKKOS_x` for Kokkos-aware FFTs. If `FFT_KOKKOS_x` is not set, then default it to `FFT_x`.

Is this a correct understanding of the problem and a possible solution?

**Comment by hagertnl** [comment]
@stanmoore1 @akohlmey I just wanted to follow up on this -- is adding `FFT_KOKKOS_x` to the Kokkos files which currently use `FFT_x` a viable solution? If we compile a binary with KOKKOS included, then users could have a GPU FFT if they use Kokkos suffixes and have a CPU FFT if they don't use the Kokkos suffix. I'm not sure if I'm just missing something. I'm happy to contribute some cycles to draft this up and update documentation, if it sounds reasonable.

**Comment by stanmoore1** [comment]
@hagertnl it sounds good to me, but @akohlmey is the CMake expert.

**Comment by akohlmey** [comment]
> @hagertnl it sounds good to me, but @akohlmey is the CMake expert.

This is not an issue for CMake, but something that needs to be set consistently across both build systems and for all permutations of supported FFTs. This is tricky business since few people have access to hardware where they can verify all permutations and the logic for choosing FFTs is a bit different between the two build systems. With the GNU make build you can not choose a specific FFT library and it will fall back to KISS fft. For CMake, a setting is made within CMake from a preset autodetected default. The difficulty is that for GNU make it is valid to select two FFT libraries for as long one of them is for GPUs, but in CMake it is not allowed. As indicated, the solution is to decouple this and then allow independent settings for CPU based FFT and KOKKOS supported FFT and then verify each for valid choices and only allow combinations that are compatible with each other. The latter has to be done within the source code through preprocessor checks.

**Comment by hagertnl** [comment]
I put a draft PR up: https://github.com/lammps/lammps/pull/4007
I did not yet modify any of the CMake build system or docs, but how does this look? I tested using the Make build system and was able to run a CPU-only water box with KISSFFT with the same binary as GPU-enabled water box with hipFFT.

I basically just did a `sed s/FFT_/FFT_KOKKOS_/g` through the files in KOKKOS subdirectory, with some minor modifications and edits.
