### ISSUE TITLE
lto related error when building with Kokkos (cmake)

### ISSUE THREAD

**Issue by RandomDefaultUser** [lammps/lammps#3808]
**Summary**

This is not exactly a bug, more a question for clarification. I have been trying to build LAMMPS with Kokkos on my local machine. I get an error that I can clearly track to the compilation using an link time optimization flag (Probably because it was set as compiler default on my machine?). However, I could not figure out a suitable way to disable the flag using the cmake pipeline. 

**LAMMPS Version and Platform**

I use a forked version of LAMMPS (https://github.com/mala-project/lammps), based on the recent HEAD of development. I operate on Pop!_OS 22.04 (a Ubuntu derivative) using an RTX 3080 GPU. 

**Details**

I am using the following cmake command:

```
cmake ../cmake -D BUILD_MPI=yes 
-D PKG_ML-SNAP=yes 
-D Kokkos_ENABLE_CUDA=yes 
-D Kokkos_ARCH_HOSTARCH=NATIVE # Working on my local machine
-D Kokkos_ARCH_GPUARCH=AMPERE86 # The eGPU I use for development has CC 8.6
-D CMAKE_CXX_COMPILER=/home/fiedlerl/tools/lammps_parallel/lib/kokkos/bin/nvcc_wrapper # Checked the path, is correct
```

When building I get this error:

```
/tmp/cc1ua6Kd.s:14660: Error: symbol `fatbinData' is already defined
lto-wrapper: fatal error: g++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```

I think this is related to: https://github.com/kokkos/kokkos/issues/4757. I have tried the flags `CMAKE_INTERPROCEDURAL_OPTIMIZATION=FALSE` and  `Kokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE=ON` but to no avail. 

However I got this to run by _manually_ removing all instances of `-flto` from the CMakeCache and CMakeList files generated automatically. Thereafter, compilation succeeds. What is the correct way to get this behavior?

**Comment by stanmoore1** [comment]
@RandomDefaultUser is this still an issue? I do not know the answer to your question, but we could ask the Kokkos or NVIDIA developers.

**Comment by stanmoore1** [comment]
Also what CMake version are you using?

**Comment by crtrott** [comment]
No idea where this is coming from. CMakeCache.txt might help a bit to understand this.

**Comment by stanmoore1** [comment]
Also you could try updating to latest LAMMPS which uses Kokkos v4, and try a newer CMake too.

**Comment by RandomDefaultUser** [comment]
Hi, this is in principle still an issue, however, due to thesis work I haven't been able to look into it much the past couple of months. I will try your suggestions as soon as possible, and post the additional info requested then!

**Comment by akohlmey** [comment]
@RandomDefaultUser we're closing this issue now due to it running stale and our inability to reproduce it. Please create a new issue if this persists after updating to the latest LAMMPS feature release.

**Comment by RandomDefaultUser** [comment]
Hi @akohlmey, yes that makes sense, sorry for not getting back to it in a while. If I can reproduce it once I update our framework to a new version, I will open a new issue. Thank you!

**Comment by jjramsey** [comment]
I think I found the culprit, which also affects GROMACS as well: https://gromacs.bioexcel.eu/t/error-installing-gromacs-2022-c-one-definition-rule/5322/11

The problem is that some distributions, such as Ubuntu, build their MPICH packages so that their MPI wrappers use the `-flto` flags. That's why they show up even though there's nothing in the CMake files for LAMMPS or Kokkos that adds those flags. This is also why `CMAKE_INTERPROCEDURAL_OPTIMIZATION=FALSE` and `Kokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE=ON` are ineffective as well, because they weren't added by the CMake machinery for adding link-time optimization, but by CMake's FindMPI module trusting that whatever flags shown by running `mpicxx -compile-info` were actually suitable for compilation and linking.

I've found that the workaround for GROMACS works for LAMMPS as well. After running `cmake` with all the desired flags to configure LAMMPS, run it *again* like this:
```sh
cmake -DMPI_CXX_COMPILE_OPTIONS="" /path/to/cmake/files/in/lammps/src/tree
``` 
This basically edits the previous build config created by the first run of CMake, changing whatever was the original value of `MPI_CXX_COMPILE_OPTIONS` in `CMakeCache.txt` to the empty string.

Of course, this workaround assumes that the original value of `MPI_CXX_COMPILE_OPTIONS` only contains the options than break the LAMMPS build. If not, you should probably set `MPI_CXX_COMPILE_OPTIONS` to a semicolon-separated list of the options that you want to keep, rather than just the empty string.
