### ISSUE TITLE
[BUG] Possible bug in install.py?

### ISSUE THREAD

**Issue by RandomDefaultUser** [lammps/lammps#3838]
**Summary**

I think there is a small bug in the `install.py` or I am doing something completely wrong. 

**LAMMPS Version and Platform**

Current LAMMPS develop head.

**Expected Behavior**

I try to install the LAMMPS python bindings via `python3 install.py -p lammps -l ../build/liblammps.so -v ../src/version.h`, which used to work.

**Actual Behavior**

I get the error "ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/fiedlerl/tools/lammps_parallel/python/lammps-2023.3.28-cp310-cp310-linux_x86_64.whl' " 

**Steps to Reproduce**

(See expected behavior)

**Further Information, Files, and Links**

The wheel does briefly exist in `build-python` folder, which gets deleted in line 113 of the install script. The wheel is not moved to `olddir` - it is only moved when a `wheeldir` is specified, which I do not do. As long as one is specified (which is probably the case for many users), this bug would never occur. I fixed this locally by adding 
```  else:
    shutil.copy(wheel, olddir)
```
beginning in line 108. If that is a useful/correct addition, I can open a PR for this.

**Comment by akohlmey** [comment]
This is a bit of a "half-bug".

The documentation primarily documents and recommends to execute "make install-python" in the folder where you have compiled LAMMPS (regardless of whether you do a CMake or a traditional make build).

How this was realized, however, was changed recently in commit ab48b834f79defb51ef8df3eba138784f3fa6ab8 to work around race conditions with concurrent builds on the CI servers that share the same copy of the source code. Those changes include that "make install-python" now always use the -w flag to set the location of building the wheel into the (unique) build folder instead of the python folder.

There are two possible solutions to address this:
- make -w a required flag
- add an else branch around line 108 that copies the created wheel to olddir as suggested

The latter has the advantage that it requires fewer changes so I implemented it in commit d23cebf9f16908ba8d7a587f203570b7ce90b44a

That said, since you are not using any non-default settings, I would strongly recommend to use "make install-python" in the build folder and not be affected by this issue regardless.

**Comment by akohlmey** [comment]
> Current LAMMPS develop head.

BTW: This cannot be since your wheel has the numeric version 2023.3.28. If this was the current development head revision, it would have been 2023.6.15

**Comment by RandomDefaultUser** [comment]
Thanks, that make sense and I agree, the `else` branch seems like the easiest solution for now. 
I will look into `make install-python` for my use case, thank you. 
Oh and you are right, my branch is a bit behind, I did not realize that, sorry!
