### ISSUE TITLE
[BUG] "-xHost" option leads to wrong simulation results without any error.

### ISSUE THREAD

**Issue by abhpc** [lammps/lammps#3891]
**Summary**

When LAMMPS is compiled with Intel oneAPI 2023.1.0 using the "xHost" (or "xCORE-AVX2/xCORE-AVX512"), there will be wrong results on command "lattice". Remove the "-xHost" option in Makefile solve this issue, while the computing speed is ~10% lower.

**LAMMPS Version and Platform**

LAMMPS Version: 23Jun2022
System OS: CentOS 7.3
Compiler: Intel oneAPI 2023.1.0
CPU: Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz

**Expected Behavior**

Create Cu (FCC lattice) along [110] direction, when the lattice dimension is 10x10x10, there will be 8000 atom created.
```
lattice  fcc 3.615 origin 0 0 0 orient x 1 1 0 orient y 0 0 1 orient z 1 -1 0
region sbox     block 0 10 0 10 0 10 units lattice
```

The normal computional log shows:
```
lattice  fcc 3.615 origin 0 0 0 orient x 1 1 0 orient y 0 0 1 orient z 1 -1 0
Lattice spacing in x,y,z = 5.112382 3.615 5.112382
region sbox     block 0 10 0 10 0 10 units lattice
create_box 1 sbox
Created orthogonal box = (0 0 0) to (51.12382 36.15 51.12382)
  1 by 1 by 1 MPI processor grid
create_atoms 1 region sbox
Created 8000 atoms
  using lattice units in orthogonal box = (0 0 0) to (51.12382 36.15 51.12382)
  create_atoms CPU = 0.003 seconds
``` 

**Actual Behavior**
The wrong computation log shows:
```
lattice  fcc 3.615 origin 0 0 0 orient x 1 1 0 orient y 0 0 1 orient z 1 -1 0
Lattice spacing in x,y,z = 5.112382 3.615 5.112382
region sbox     block 0 10 0 10 0 10 units lattice
create_box 1 sbox
Created orthogonal box = (0 0 0) to (51.12382 36.15 51.12382)
  1 by 1 by 1 MPI processor grid
create_atoms 1 region sbox
Created 7920 atoms
  using lattice units in orthogonal box = (0 0 0) to (51.12382 36.15 51.12382)
  create_atoms CPU = 0.002 seconds
```
There are only 7920 atoms created. This leads to initial dislocations.

**Steps to Reproduce**

Using the Makefile.intel_cpu_intelmpi:

(a) for the normal case, remove the option "-xHost";

(b) for the wrong case, remain the option "-xHost".

Both compiled lammps can run without any errors, while result of case (b) is remarkably wrong.

**Comment by akohlmey** [comment]
This is more the result of a very risky choice of input file settings and the consequences of finite precision of floating point math.

By using origin 0.0 0.0 0.0 of the lattice command, you create a situation where atoms will be placed *exactly* at the box boundaries and thus leading to ambiguities whether to include or exclude them. For non-rotated lattices, this usually works out and LAMMPS tries its best to avoid creating atoms multiple times. But with rotations come trigonomic functions that those may lead to approximations and thus atoms that are supposed to be exactly on the box boundary may now be either a tiny bit inside or a tiny bit outside and thus the count of created atoms and thus the resulting structure will be incorrect. This is not only for using the Intel compiler with high optimization, but due to its extremely aggressive optimization and vectorization it will be emphasized.

However, that can be trivially avoided by shifting the lattice origin, e.g. to 0.1 0.1 0.1 
Shifting the simulation box by a similar margin will have the same effect. Of course, doing both will cancel and lead to the same situation.
Please check with one of those settings changed.

**Comment by abhpc** [comment]
> 

Thank you very much. It works.
