### ISSUE TITLE
support for global parameters in fix adapt/fep

### ISSUE THREAD

**Issue by cjknight** [lammps/lammps#4014]
I was enabling a new pair_style to run with adapt/fep that uses a global scaling factor, as opposed to a type-pair parameter, and stumbled upon this hard-coded line that looks like it's been there for a while. I can understand why it's gone unnoticed based on what's listed in documentation, but seems unintended.

https://github.com/lammps/lammps/blob/0c4a1cb21d020f1379e36be6b7c2ec9a931eed79/src/FEP/fix_adapt_fep.cpp#L288

Tests so far seem to work as expected just commenting the line.

**Comment by akohlmey** [comment]
It has come to my attention very recently and a fix has been included in PR #4004, but as far as I can tell, fix adapt/fep does *not* support global scale parameters. When you compare the source to fix adapt, you can see that branches for that are missing. This is my understanding why nobody has noticed that. It will take significant work to make fix adapt/fep compatible since fix adapt has diverged over time quite a bit and picked up features and changes that are missing in fix adapt/fep

**Comment by cjknight** [comment]
ok... I can work around that easy enough. And I see ad->pdim != 2 now triggers an error to avoid segfault.

This issue can be closed. Sorry for the noise.
