### ISSUE TITLE
[BUG] Technically Timer::get_timeout_remain is buggy (can return timer inactive when it has just expired)

### ISSUE THREAD

**Issue by twhitehead** [lammps/lammps#4065]
I am working on a fix that can start the pre-compution of some items on the GPU in `end_of_step`. I can't do this if the next step can be cancelled though as the pre-compution cannot be undone and is only valid if the next step runs for sure.

There seems to be no function other than `Timer::get_timeout_remain()` to tell you if a timer has been set. Looking at the implementation though
```
// get remaining time in seconds. 0.0 if inactive, negative if expired
double Timer::get_timeout_remain()
{
  return (_timeout < 0.0) ? 0.0 : _timeout + timeout_start - platform::walltime();
}
```
I see it can technically tell you no timer has been set (return 0.0) if it is called at the exact moment a set timer expires. Now, probably, the timer resolution is such that the odds of this happening are insurmountably small, but it still seems wrong.

I also see that timeouts can only happen on certain step multiples.
```
class Timer : protected Pointers {
 public:
  ...
  bool check_timeout(int step)
  {
    if (_timeout == 0.0) return true;
    if (_nextcheck != step)
      return false;
    else
      return _check_timeout();
  }
  ...
```
This would mean that I could pre-compute on most timesteps even if a timer is set, except there is no way to determine if this is one of those steps or not from the public API.

Also, shouldn't that be `_nextcheck < step` as otherwise correctness depends on this function being called for `_nextstep == step` so it can set `_timeout = 0.0` and continue to return `true` for future calls (which is the case as it is called , but still).

**Comment by akohlmey** [comment]
> I am working on a fix that can start the pre-compution of some items on the GPU in `end_of_step`. I can't do this if the next step can be cancelled though as the pre-compution cannot be undone and is only valid if the next step runs for sure.

This is making an invalid assumption. There is no reliable way to predict the future and a timer can be expired at *any* time by something calling `timer->force_timeout()`.

Also, there are two concerns:
- your pre-computed data can become invalid if any of the data you are using as input is changed by some other fixes in between `Fix::end_of_step()` and when you access the pre-computed data (when? and which data is the pre-computation based on). As a minimum, you would have to require that your fix is going to be the last one being executed at that stage.
- your description implies that you are directly modifying data (which?) that is used and updated later, but that is making the assumption that the data you are modifying is not accessed at any time while you are doing your pre-computation. Otherwise the data those other step(s) get to see would depend on when your pre-computation happens and in which order.

> I also see that timeouts can only happen on certain step multiples.

No. The check for whether a timer has run out can be done every N steps to reduce the overhead from this check. That is true. This is because active timers are the unusual scenario and when implementing the functionality it was required to impose as little overhead as possible for the common case of no timeout being set. But that does not mean the timer cannot expire. It can be forced to expire, e.g. through using "fix halt" or when LAMMPS is run through the library interface. LAMMPS-GUI uses the latter by running LAMMPS and the GUI different threads so the GUI can remain active including its "stop run" feature. This will call the library function to expire the timer and thus stop the run interactively.

I will have a closer look at your concerns about the two timer functions. There may be room for improvement, but I have not yet seen any problem. But that may be simply because *very* few users make use of this feature. That said, I would be much more worried about the two principal design problems I was mentioning.

**Comment by akohlmey** [comment]
> Now, probably, the timer resolution is such that the odds of this happening are insurmountably small, but it still seems wrong.

The function `Timer::get_timeout_remain()` is only used for diagnostic output  with the "timeremain" thermo keyword and there it does not matter whether it outputs 0.0 when the timer is just expiring. If one would want to improve anything here it would be avoiding to return a *negative* remaining time. The logic of this function is that it returns 0.0 when there is no more remaining time either because there is no timeout set or when the timer is expired.

Functionality that depends on timeouts uses `Timer::check_timeout()`. You can set the frequency of that check with the "timer every" command and that one *will* report a just expired timer as expired.

The way to check whether a timeout is set is with neither of the two functions but with `Timer::has_timeout()`.

**Comment by akohlmey** [comment]
`Timer::get_timeout_remain()` changed as indicated above in commit 82f106c12a6b2768196a5b7ab93a820072787908

**Comment by twhitehead** [comment]
Thanks. It was some Lattice Boltzmann code. The calculation I am wanting to start early is the fluid relaxation.

The equilibrium distribution you are relaxing to has an external forcing term that depends on the velocity and position of the particle though, so for it to be valid the number of particles and their velocities positions has to not change between `end_of_step` and `initial_integrate`.

Currently I have
```
if ( update->ntimestep < update->laststep && !timer->get_timeout_remain() ) {
  ... start fluid relaxation early ...
}
```
but maybe that isn't correct? Can a timeout still be forced if no timer was set?

It may not be such an issue if it cannot done. Now that I have been looking at the code more, I am not certain how much of a performance boost it gives as it involves a trade off with more fluid neighbour point exchanging.

**Comment by akohlmey** [comment]
> Can a timeout still be forced if no timer was set?

Yes, I have already explained that.
