### ISSUE TITLE
LAMMPS installtion still required the deprecated and removed Intel classic compilers (icc, icpc)

### ISSUE THREAD

**Issue by SerpentByte** [lammps/lammps#4083]
**Summary**

LAMMPS installtion still required the deprecated and removed Intel classic compilers (icc, icpc)

**LAMMPS 2023 2 Aug, Linux**

**Details**

When compiling LAMMPS using intel compiler from OneAPI, the makefiles search for the removed icpc and icc compilers. This needs to updated with a search for icpx and icx. If someone can guide me to which makefile is searching for these when ```make intel_cpu_intelmpi``` is used, I can update my local version. This will allow me to install the latest lammps with intel compilers.

**Comment by akohlmey** [comment]
LAMMPS can very well be compiled with the LLVM based Intel compilers. It is just so that for the INTEL package, specifically, the classic compilers have been more reliable and performant, and for everything else there is next to no benefit over using the GNU or Clang compilers. Thus, nobody has yet cared to provide specific machine makefiles.
When using the GNU make based traditional build systems, the machine makefiles are merely a suggestion and typically must be customized to the local systems. They are not *mean* to be the definite input.

When using the more modern CMake based build system, there is a suitable preset (because the CMake system is much more capable of automatically adjust to the local system once it knows the compilers), but you can just also define the compilers from the cmake command line using standard CMake conventions.

Detailed information about how to adapt your build configuration for either build system is given in the LAMMPS manual: https://docs.lammps.org/Build.html
Feel free to submit a pull request with a suitable Intel LLVM compatible machine makefile.
