### ISSUE TITLE
[BUG] "boost_serialization" option missing in PLUMED.cmake

### ISSUE THREAD

**Issue by zhucongx** [lammps/lammps#4137]
**Summary**

When building the PLUMED from scratch together with LAMMPS, the CMake file "cmake/Modules/Packages/PLUMED.cmake" mentions the build options either "--enable-modules=-adjmat:+crystallization:-dimred:+drr:+eds:-fisst:+funnel:+logmfd:+manyrestraints:+maze:+opes:+multicolvar:-pamm:-piv:+s2cm:-sasa:-ves" for Windows system or "--enable-modules=all" for others. 

However, building option "--enable-boost_serialization" is necessary for the module DRR according to the plumed documentation (https://www.plumed.org/doc-v2.8/user-doc/html/_e_a_b_f_m_o_d.html). Maybe it's better to add the building option "--enable-boost_serialization" in line 48 and line 130 of the file  "PLUMED.camke"

**Comment by akohlmey** [comment]
The `--enable-boost_serialization` requires the installation of the Boost libraries and headers. This cannot be assumed in the general case and hence this option is not used for the automatic Plumed build through the CMake scripting.

However, this automatic build is primarily meant to be used for automated testing.  To get the most out of Plumed you need a *full installation* so that you also have the various utilities and so on available. At that point, you can configure and compile Plumed any which way you personally prefer. It will also speed up compilation of LAMMPS since you don't have to wait for Plumed to be compiled (which can take a while) when you compile LAMMPS regularly.

There is no need to make a change to the automatic download and compile for that reason.
