### ISSUE TITLE
Temperature in charmm2lammps generated input file

### ISSUE THREAD

**Issue by ZappD0S** [lammps/lammps#4175]
I am currently using charmm2lammps and I noticed that in the generated LAMMPS configuration file there's this line 

`velocity        all create 0.0 12345678 dist uniform`

According to the documentation, the first value after `create` is the temperature. Why is it set to 0?

Thanks

**LAMMPS Version and Platform**

Update 3 for Stable release 2 August 2023

**Comment by akohlmey** [comment]
> Why is it set to 0?

It is an arbitrary choice that doesn't do any harm. The charmm2lammps script does not know what you want to study and how well equilibrated your initial geometry is. The generated input is just a template that demonstrates a possible input that can be (and should be!) edited as needed. There is not much to it.

**Comment by ZappD0S** [comment]
Yes, I see your point. The thing is, some other parameters are set to reasonable values. Wouldn't it make sense to add comments that specify which parameters **must** be edited? It might still be useful to run this configuration mostly unchanged (but with reasonable values) purely for demonstrative purposes.

**Comment by akohlmey** [comment]
@ZappD0S 0K is as reasonable as would be, e.g. 300K. In fact, if you don't assign an initial temperature, 0K will be the default. Since most initial geometries are already of high potential energy, adding too much kinetic energy can be counterproductive. The best choice can only be found with experimenting and knowing the details of the individual geometry and its force field parameterization. Any sufficiently *competent* practitioner in MD simulations should be capable of making such choices and for everybody else any choice is as bad as the other and thus they need to train themselves (or get trained) accordingly. The same goes for flagging which setting needs to be changed. It could be almost anything or next to nothing depending on the boundary conditions.

If you don't like how charmm2lammps is set up, you can a) change the script to your personal liking (it is not very difficult) or b) use alternate approaches like https://charmm-gui.org or EMC (https://montecarlo.sourceforge.net/emc/Welcome.html) or other tools listed here: https://www.lammps.org/prepost.html#builders

**Comment by ZappD0S** [comment]
@akohlmey Thank you a lot for going into more detail. Apologies if my comment sounded a bit too conceited. Just one final question: does what you say about the high potential energy of the initial conformation still holds if one runs a minimization first? In the charmm2lammps input the `minimize` has the maximum number of iterations set to a really small value (is this just to avoid intial conformations with an abnormally high energy?), so I guess that at least in this case the answer is yes.

**Comment by akohlmey** [comment]
> does what you say about the high potential energy of the initial conformation still holds if one runs a minimization first?

Yes. Your geometry may be metastable and thus the minimization be stuck until running the MD drops the system down the potential hypersurface. 

That said, for most common systems, it is sufficient to just run one minimization for a moderate number of steps to "take the edge off". Running a full minimization may push the system too far away into a low energy configuration that can then take extra time to break up.

For some systems, additional commands are required (e.g. fix setforce 0.0 0.0 0.0 on parts of the system) to relax the system in stages and retain some overall geometry (this applies for example on bilayers).
