### ISSUE TITLE
Documentation Error for the C-API

### ISSUE THREAD

**Issue by Joroks** [lammps/lammps#4208]
The C-API reference for `lammps_extract_variable` (https://docs.lammps.org/Library_objects.html#_CPPv423lammps_extract_variablePvPKcPKc)

Lists two strings with wich to acces the length of a vector:
- "GET_VECTOR_SIZE"
- "LMP_SIZE_VECTOR"

However it seems that only "LMP_SIZE_VECTOR" actually works.

Because you're not supposed to free the pointer you get when asking for a Vector Style Variable except for when you also pass "LMP_SIZE_VECTOR" for the group parameter to get he size of the vector, it's easy to accidentally free the wrong data which results in a crash.

**Comment by akohlmey** [comment]
@Joroks thanks for your report. It looks like the documentation for this command has not been updated at the last refactor. In general, the testing for a string is confusing, especially when that string is otherwise used as an integer constant. Thus I have simplified this between providing NULL (returns the vector) and non-NULL (returns the vector length as allocated int pointer). I've also updated and corrected the embedded documentation and provided one example.
These changes are in the pending pull request #4212.
