### ISSUE TITLE
[BUG] _fix nonaffine/displacement not work in rerun

### ISSUE THREAD

**Issue by guoke1990** [lammps/lammps#4216]
**Summary**

I use rerun to calculate nonaffine displacement by using fix nonaffine/displacement command, but results give all zero value for this fix calculation when I dump it.

**LAMMPS Version and Platform**

LAMMPS (17 Apr 2024) on Windows

**Expected Behavior**

This fix should give the non-zero value. Rather than using rerun, I re-perform the simulation, it works. 

**Actual Behavior**

But when I use rerun, I only get zero value, which is, of course, wrong result.

**Steps to Reproduce**

units 		real
dimension 	3
processors 	* * *
boundary 	p p p
atom_style 	charge

read_data	L300K.dat

include		pot.mod

timestep      1

#fix 1 all nve

fix 3 all nonaffine/displacement 100 d2min custom 3.5 fixed 0
dump            3 all custom 100 stressd.text id type  x y z f_3[1]

rerun  stressy.text first 5610000 every 100000 dump x y z

**Further Information, Files, and Links**

I also try to change the value after the keyword “nonaffine/displacement” to match the dump file, but none of them works.

**Comment by jtclemm** [comment]
Thank you for reporting the issue. The simple answer is that fix nonaffine/displacement is not intended to work with the rerun command. The fix saves reference states at specific timesteps and there's no guarantee that said timesteps are included within the snapshots. 

The more detailed answer is that fix nonaffine/displacement only calculates values during the post_run() integration step when the variable `setupflag` isn't set. This never happens with the rerun command since it doesn't run dynamics. This behavior could be changed by carefully editing the logic here:
https://github.com/lammps/lammps/blob/56a9192cf3245912891caf0c4d96762674867b24/src/EXTRA-FIX/fix_nonaffine_displacement.cpp#L261
at the cost of unnecessary evaluations during a normal run. However, since there's no guarantee that the requested reference states are in the snapshot I'd hesitate to add partial support for the rerun command. 

@akohlmey do you know how fix ave/time (or a similar fix) handles the rerun command since it has a similar issue (there's no guarantee the timesteps needed for its evaluation are in the snapshots for the rerun command)?
