### ISSUE TITLE
[Feature Request] Error message support in static member functions

### ISSUE THREAD

**Issue by bozhang-hpc** [lammps/lammps#4222]
**Summary**

Neither current `error->all/one("foobrar")` or `utils::logmesg(lmp, "foobar")` is supported in a static member function of a class.
The compile time error are these:
`error: invalid use of member ‘LAMMPS_NS::Pointers::error’ in static member function`
`error: invalid use of member ‘LAMMPS_NS::Pointers::lmp’ in static member function`

It would be very useful if the error and log capabilities could be extended to static member functions.

**Detailed Description**

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
This is a built-in problem of static member functions. They are effectively just a global function in the namespace of the class. The way to work around this limitation would be to pass either the error class pointer or the LAMMPS class pointer as argument to the static function (since static functions have no access to the "this" pointer) as it is done for the "global" functions in the utils namespace where there is no "this" either; see utils::logmesg() requiring `lmp` as an argument or utils::missing_cmd_args() which takes a pointer to the error class as an argument.

Of course, the better solution is to avoid static members altogether.

At any rate, LAMMPS cannot change how C++ works, so there is nothing that can be done beyond what I mentioned.
