### ISSUE TITLE
[Feature Request] mpi4py 4.0.0 was released but LAMMPS requires mpi4py >=2,<=3

### ISSUE THREAD

**Issue by jan-janssen** [lammps/lammps#4253]
**Summary**

LAMMPS internally restricts the mpi4py version to be 2 or 3: 
https://github.com/lammps/lammps/blob/develop/python/lammps/core.py#L372

As mpi4py version 4 was just released it would be great if LAMMPS could add support for mpi4py version 4.

**Detailed Description**

mpi4py version 4.0.0 release https://github.com/mpi4py/mpi4py/releases/tag/4.0.0 

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
The change is easy to do. It will be in an upcoming pull request and also backported to the stable version.
I had already successfully tested with mpi4py 4.0.0 while checking out the bug report issue #4249 
Please note that the check in question only applies when you want to pass an MPI communicator from python to LAMMPS. Without that, LAMMPS already works with mpi4py 4.0.0 out of the box.

**Comment by acgc99** [comment]
Hello, new to LAMMPS here. I downloaded ``LAMMPS-64bit-latest-MSMPI.exe`` and installed "LAMMPS 64-bit 15Jun2023-MSMPI -- MD Simulation Software". I installed ``mpi4py`` version 4 without problems. But I get the error related to this issue about ``mpi4py`` version. I tried to install version 3 without success (I don't know why). I wouldn't like to have another version of python installed (lower version might work?) since that would break compatibility with other personal codes I'm using for LAMMPS output. I wonder if the LAMMPS installer could be updated.

**Comment by akohlmey** [comment]
> I downloaded `LAMMPS-64bit-latest-MSMPI.exe` and installed "LAMMPS 64-bit 15Jun2023-MSMPI -- MD Simulation Software".

*Where* did you download this and *when*?
The current latest version should be 19Nov2024 and the current stable version is 29Aug2024-update1

As you can see from the information above, this feature request was completed on Aug 5, 2024 and thus *cannot* be present in any older version. The first stable version that has this change is 2Aug2023-update4 followed by the 29Aug2024 release which were both released around the same time.

**Comment by acgc99** [comment]
Mmm I downloaded I yesterday. I have just downloaded again and installed the true latest version. Yesterday, a collegue sent me the 2023 version and I also downloaded the latest one from the web. It seems there was a name clashing while saving installers.
