### ISSUE TITLE
LAMMPS PDF Documenation review

### ISSUE THREAD

**Issue by rbberger** [lammps/lammps#4274]
Current version: https://docs.lammps.org/Manual.pdf

Pages reviewed:
- [x] 123 - 399
- [x] 400 - 672
- [x] 673 - 948
- [x] 949 - 1220
- [x] 1221 - 1497
- [x] 1498 - 1770
- [ ] 1771 - 2042
- [ ] 2043 -  2314
- [x] 2315 - 2589
- [x] 2590 - 2838

**Comment by sjplimp** [comment]
Here are my comments on 2590-2838

(a) 2678 - pair style tracker - do not see it in alphabetic list of styles, p 127
(b) 2837 - dump styles chapter is empty
(c) 2867 - Biblio chapter has a single entry
(d) 2869 and 2871 - Python and Fortran pages are near empty ?
(e) 2885, 2886 - index pages have 2-column overlaps

**Comment by akohlmey** [comment]
> Here are my comments on 2590-2838
> 
> (a) 2678 - pair style tracker - do not see it in alphabetic list of styles, p 127
It is at the top where the other "non-standard" pair styles like hybrid, list, or kim are listed.

>  (b) 2837 - dump styles chapter is empty

Should be fixed with the latest changes in #4275 

> (c) 2867 - Biblio chapter has a single entry

That would be the *second* bibliograpy. This is generated when some file uses the LaTeX \cite like mechanism. Since we do not use it and use references and put the citations at the bottom of each .rst file, the (first) bibliography is compiled manually (it needs updating...)

> (d) 2869 and 2871 - Python and Fortran pages are near empty ?

There is only one Fortran module and two Python modules properly referenced in the documentation.
Changed the sphinx configuration to skip creating those.

> (e) 2885, 2886 - index pages have 2-column overlaps

This is a tricky one. Some indexed lines are very long. I've tried to shorten some by changing the sphinx configuration. For example for all C++ code the "LAMMPS_NS::" prefix is now dropped. That has the benefit that classes and functions are sorted into sections by their name and don't all show up under "L".
I've also included some LaTeX hack that will configure the index to be single column.

CI run just finished. The resulting PDF is here: https://ci.lammps.org/job/dev/job/pull_requests/job/build_docs/10336/artifact/lammps/doc/Manual.pdf

**Comment by rbberger** [comment]
@akohlmey I've noticed that the CI generated PDF is a bit different to the one produced locally with newer Sphinx. Should we use a newer container just for the docs? Example:

docs.lammps.org build:
![Screenshot from 2024-08-14 14-20-48](https://github.com/user-attachments/assets/5eb1693c-9ff1-4843-88a4-b3c43b48f706)


local build:

![Screenshot from 2024-08-14 14-21-43](https://github.com/user-attachments/assets/7d07fe6e-50ea-46cc-ab3a-6b29f4976c69)

**Comment by akohlmey** [comment]
> @akohlmey I've noticed that the CI generated PDF is a bit different to the one produced locally with newer Sphinx. Should we use a newer container just for the docs? Example:

I thought the sphinx version is downloaded via pip into the docenv virtual environment.

I faintly remember the round edges... it is some optional extension, IIRC. Let me check.

**Comment by rbberger** [comment]
> > @akohlmey I've noticed that the CI generated PDF is a bit different to the one produced locally with newer Sphinx. Should we use a newer container just for the docs? Example:
> 
> I thought the sphinx version is downloaded via pip into the docenv virtual environment.
> 
> I faintly remember the round edges... it is some optional extension, IIRC. Let me check.

It could just be that it's missing a `make clean-all` at the very beginning of the CI job.

**Comment by akohlmey** [comment]
> It could just be that it's missing a `make clean-all` at the very beginning of the CI job.

Ah, now I remember. See the following:

```
Package sphinx Warning: The package pict2e is required for rounded boxes.
(sphinx)                It does not seem to be available on your system.
(sphinx)                Options for setting radii will be ignored.


Package sphinx Warning: The package ellipse is required for elliptical corners.

(sphinx)                It does not seem to be available on your system.
(sphinx)                All non-straight corners will use circle arcs..
```

So it is not a sphinx issue, but newer sphinx versions will add the round corners, if additional LaTeX packages are included. We can do this without rebuilding the container. Just had to do a similar thing to change the index to just one column.

**Comment by akohlmey** [comment]
@rbberger check out: https://ci.lammps.org/job/dev/job/pull_requests/job/build_docs/10342/artifact/lammps/doc/Manual.pdf

We should perhaps copy some more (obscure) LaTeX styles to the distribution to make it easier for people creating the PDF version instead of chasing down the packages and installing them. On Fedora this has been quite tedeous.

**Comment by rbberger** [comment]
> We should perhaps copy some more (obscure) LaTeX styles to the distribution to make it easier for people creating the PDF version instead of chasing down the packages and installing them. On Fedora this has been quite tedeous.

Ok now we just need to understand where the icons came from.

**Comment by akohlmey** [comment]
> Ok now we just need to understand where the icons came from.

I am drawing a blank there. I may have installed the required package for some other project where it was required and not optional.

**Comment by akohlmey** [comment]
@rbberger found the package, fontawesome. But "backdoor" installation is not so awesome since it ships its own font. So it is not just LaTeX code and that is where my expertise is getting thin. So building a new container is probably the only remaining solution.  Testing it locally right now.

**Comment by akohlmey** [comment]
New container is built and the build_docs configuration updated for pull requests, develop, release, and stable to use the new container.

**Comment by akohlmey** [comment]
Success:
https://ci.lammps.org/job/dev/job/pull_requests/job/build_docs/10347/artifact/lammps/doc/Manual.pdf

**Comment by ndtrung81** [comment]
1) Page 2316: Style cosine/squared, pair coeff commands i and j should be capitalized for atom types.
2) Page 2324: Style coul/diel, epsilon_D(r) connects to limiting regimes: \epsilon_D(r ) connects two limiting regimes; “The lower limit of epsilon_D(r->0)= “
3) Page 2325 References: “Stiles , Hubbard”, “Lenart , Jusufi” extra blank spaces
4) Page 2327: Styles coul/slater/* compute
5) Page 2338: Style cut/dipole/cut, “between particles I and J” : I and J should be in lower case (i and j) to be consistent with the equations and other parts of the documentation.
6) Page 2343 Pair dpd, “The GPU-accelerated versions of these styles “ -> “Styles with a gpu suffix”
7) Page 2373: Style eff, eff/long (not yet available) --> Remove the 2 paragraphs
8) Page 2379: Style exp6/rx, equation brackets too short
9) Page 2381: pair tersoff <pair tersoff> -- link to doc page  :doc:`pair tersoff <pair_tersoff> `
10) Page 2396: pair gran/hooke  \Delta (in front of s_t) is not rendered correctly in the PDF (showing as a black square) Could be using \boldsymbol{\Delta} instead of \mathbf{\Delta}
11) Page 2406 pair granular, with vroll,  \Omega is not rendered correctly in the PDF (showing as a black square) Could be  using \boldsymbol{\Omega} instead of \mathbf{\Omega}
12) Page 2462 Style lj/cut/coul/wolf, “coul/wolf” should be lj/cut/coul/wolf
13) Page 2552 Style oxdna2 spaces and end of line characters (red) show
14) Page 2564 Style pedone examples outside of the box (indentation)

@akohlmey I rebuilt the doc and found the pages have shifted from the version where the pages 2315-2589 I am responsible for. So I created the PR #4279 to show the changes to the relevant .rst files. Hopefully it is more convenient to incorporate the edits.

**Comment by jmgoff** [comment]
1. P. 1368 make language in fix ave/atom for Nfreq, Nevery requirements similar to others.  Nfreq must be a multiple of Nevery and Nevery must be non-zero even if Nrepeat is 1. Also, the timesteps contributing to the average value cannot overlap, i.e. Nrepeat*Nevery can not exceed Nfreq.
2. P. 1372, make language in fix ave/chunk for Nfreq, Nevery requirements similar to others. “Nfreq must be a multiple of Nevery and Nevery must be non-zero even if Nrepeat is 1. Also, the timesteps contributing to the average value cannot overlap, i.e. Nrepeat*Nevery cannot exceed Nfreq.”
3. P. 1386 Changed multiple instances of formatting in fix ave/grid for Nfreq, Nevery, Nrepeat -made consistent with formatting with fix ave/atom, fix ave/chunch (this was mostly just switching from italics to math mode to maintain consistency with other fix ave commands)
4. P. 1398 make language in fix ave/time for Nfreq, Nevery requirements similar to others. “Nfreq must be a multiple of Nevery and Nevery must be non-zero even if Nrepeat is 1. Also, the timesteps contributing to the average value cannot overlap, i.e. Nrepeat*Nevery cannot exceed Nfreq.”


p. 1471 (Stylistic) fix edpd/source fix tdpd/source pages melded together. I’ve seen it like this with some other sets of related fixes or sets of pairstyles. (Did not edit)

Making a PR with the changes here:  #4285

**Comment by athomps** [comment]
Thanks to all the reviewers.  I have one high level suggestion/request. The attribution "The LAMMPS Developers," is not sufficiently concrete.  Can we add a reference to an explicit list of authors/developers, either inside the document or linking to `https://www.lammps.org/authors.html`
