### ISSUE TITLE
[Feature Request] Add pair_write support for hbond/dreiding/morse and hbond/dreiding/lj

### ISSUE THREAD

**Issue by EiPiFun** [lammps/lammps#4307]
**Summary**

Add pair_write support for hbond/dreiding/morse and hbond/dreiding/lj

**Detailed Description**

I cannot use pair_write to output/debug hbond/dreiding/morse and hbond/dreiding/lj potentials.

This is especially important cause I open another issue to add angleoffset for hbond/dreiding/morse and hbond/dreiding/lj.
https://github.com/lammps/lammps/issues/4306

I want to confirm that my modifications are right.

Thanks for your work.

**Comment by akohlmey** [comment]
@EiPiFun It is not possible to support pair_write for these pair styles. The pair_write functionality depends on implementing the Pair::single() function for a given pair style. This computes the potential energy and force of a pair of atoms for a given set of atom types depending on their distance. However, this cannot be applied to the hbond pair styles, since they are not pairwise additive as they depend on the location of a third atom. So a single distance does not capture the potential. Please see the implementation of the Pair::compute() function where you have a 3-fold nested loop instead of the 2-fold nested loop of pairwise additive potentials like lj/cut or morse.
