### ISSUE TITLE
Does improper/harmonic consider angle range in (180°-360°)?

### ISSUE THREAD

**Issue by EiPiFun** [lammps/lammps#4332]
**Summary**

I read the computation code and I find that improper/harmonic use acos/arccos to compute improper.
I just want to make sure that the improper angle is ranged in 0°-180° instead of 0°-360°, or does the improper/harmonic support equilibrium angle higher than 180°？

**LAMMPS Version and Platform**

LAMMPS version Aug292024 on Rocky Linux 9

**Details**

I read the computation code and I find that improper/harmonic use acos/arccos to compute improper.
I just want to make sure that the improper angle is ranged in 0°-180° instead of 0°-360°, or does the improper/harmonic support equilibrium angle higher than 180°？

You can check the code here:

https://github.com/lammps/lammps/blob/develop/src/MOLECULE/improper_harmonic.cpp

![image](https://github.com/user-attachments/assets/847316f3-7bbc-4758-817c-069be248a5fc)

![image](https://github.com/user-attachments/assets/c12da5dc-b927-4f2e-8a04-0134705bf3f5)

**Comment by akohlmey** [comment]
@EiPiFun two points
1. This is a question for the LAMMPS Development category in the MatSci forum not the github issue tracker. We are tracking *LAMMPS* issues here, not your personal concerns. If you feel there is a bug we need proof.
2. You can easily check the behavior of the implementation by constructing some typical and extreme geometries and see what results you get. impropers are a bit inconsistent throughout LAMMPS since their implementations are contributed by many different people.

**Comment by EiPiFun** [comment]
Sorry, I know them now.

**Comment by EiPiFun** [comment]
Actually I think the code is clear, I just find it hard to persuade others. You are right, I will construct some examples to test, then I will know if there is a difference between 150° and 210°. I think this will be persuasive enough. Thanks!
