### ISSUE TITLE
[BUG]  GRANULAR package fix_pour: frequency of insertion not updated if timestep changed after defining fix_pour in input script

### ISSUE THREAD

**Issue by cgadal** [lammps/lammps#4338]
**Summary**

The frequency of insertion (`nfreq` in fix_pour.cpp) is not updated if timestep dt is changed _after_ defining the fix pour in the input script. This is unexpected, since all examples using the fix pour set the time step after defining the fix pour.

**LAMMPS Version and Platform**

Develop branch, last commit, Ubuntun 20.04

**Expected Behavior**

From the examples, we expect that change of the time step, even after defining the fix pour, would be taken into account in the pouring of particles. Indeed, the number of timesteps between two insertion events is defined as the time needed for a particle to reach the bottom of the insertion zone divided by the time step dt.

Otherwise, we should modify the examples, and explicitly mention this restriction in the documentation.

**Actual Behavior**

Changing `timestep        0.001` in [this example](https://github.com/lammps/lammps/blob/develop/examples/granular/in.pour.flatwall)  to `timestep        0.0001` will not change the number of steps between insertion events, while it should multiply it by 10.

Moving the line `timestep        something` before:

https://github.com/lammps/lammps/blob/b95f7c2ab2b9cba44c3f690b9bfb16b36cc11b98/examples/granular/in.pour.flatwall#L49-L50

will update it properly.

**Comment by jtclemm** [comment]
Good catch. It does look like fix pour calculates a lot of settings in the constructor which assumes nothing changes between the fix declaration and the run command (e.g. number of atoms, timestep # and size, etc.). 

I think the best solution is to move any such calculations into the _init()_ method (ensuring they are only run once) to capture any potential changes.

<del>However, I'm not sure what you mean by "since all examples using the fix pour set the time step after defining the fix pour." All the examples have the timestep defined before, e.g. </del>

https://github.com/lammps/lammps/blob/b95f7c2ab2b9cba44c3f690b9bfb16b36cc11b98/examples/pour/in.pour#L22-L30

Nevermind, I see the scripts in /examples/granular/ have timestep set after the fix. I assume these examples are what you were referring to.

**Comment by jtclemm** [comment]
I made the changes in PR #4339. Are you able to check whether these updates resolve this issue (and #4337)?

Thanks!

**Comment by cgadal** [comment]
Just ran a couple of examples I had on my laptop from this PR and everything went as expected! Thanks for fixing this this fast :)

**Comment by jtclemm** [comment]
Great, thanks again for reporting and testing. I'll mark the PR as ready for review.
