### ISSUE TITLE
[BUG] Can not fetch potentials while building with CMake

### ISSUE THREAD

**Issue by obsqrbtz** [lammps/lammps#4368]
**Summary**

Failing to build lammps with CMake due to lack of access to `LAMMPS_POTENTIALS_URL` (https://download.lammps.org/potentials). When trying to access this URL from web browser there is `Error 403 Forbidden`.

**LAMMPS Version and Platform**

Lammps: Latest stable version [stable_29Aug2024_update1](https://github.com/lammps/lammps/tree/stable_29Aug2024_update1).

Platform: Archlinux, upgraded 30.10.2024

**Expected Behavior**

Successfull build.

**Actual Behavior**

Fail on the `FetchPotentials` stage of the build process:

https://github.com/lammps/lammps/blob/6d634dc646a075c16ec87ec9d3f7355bb8f905c1/cmake/CMakeLists.txt#L45-L46

https://github.com/lammps/lammps/blob/6d634dc646a075c16ec87ec9d3f7355bb8f905c1/cmake/CMakeLists.txt#L628

**Steps to Reproduce**

1. Get stable_29Aug2024_update1 sources. 
2. Run:
```
cmake -S cmake -B build
```

**Comment by akohlmey** [comment]
> When trying to access this URL from web browser there is `Error 403 Forbidden`.

This is the intended behavior. You can only download individual potential files, not view the entire folder.

Since you don't provide any specific error messages for the actual cmake command, it is not possible to determine the reason for the failure. It certainly works for lots of people and for the automated testing and much more. There must be something special about your machine setup, for example a lack of a suitable SSL implementation or a CMake installation without support for it or something else that I cannot imagine right now.

You can work around the attempt to download by adding `-D DOWNLOAD_POTENTIALS=no` to the CMake configuration command line.
