### ISSUE TITLE
[BUG] _Replace With Suitable Title_MPI errors when running tad with multiple  replicas

### ISSUE THREAD

**Issue by vhjbhc** [lammps/lammps#4402]
**Summary**

The NEB calculation barrier using the tad command was suddenly interrupted, and the NEB calculation was performed normally several times at the beginning, but at some point it was interrupted

**LAMMPS Version and Platform**
LAMMPS (2 Aug 2023);
NAME="Ubuntu"
mpirun (Open MPI) 4.1.6

**Expected Behavior**

**Actual Behavior**
Why is tad not working properly

**Steps to Reproduce**

[lammps.txt](https://github.com/user-attachments/files/18035908/lammps.txt)
[p.log](https://github.com/user-attachments/files/18035979/p.log)
![微信图片_20241206173825](https://github.com/user-attachments/assets/c6f809d1-9ba3-48d6-b0df-d636f3ec08f6)
![微信图片_20241206173844](https://github.com/user-attachments/assets/5d39b0e6-a38b-4a2d-a0cc-6b4549f7d4b3)
![微信图片_20241206173849](https://github.com/user-attachments/assets/73591e78-fd3e-46dc-9816-49af38b1006e)
![微信图片_20241206173853](https://github.com/user-attachments/assets/7b0ed843-8f79-4873-aff5-8ee27618f7ff)

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
You are posting to the wrong GitHub repository. You are using the deepmd pair style, which requires you to use code not maintained by the LAMMPS developers, so we cannot reproduce and track down the issue. Only if you can reproduce it by using only components that are within the LAMMPS distribution, we may take a look. Otherwise, you will have to ask the deeppot developers to have a closer look. Please also note, that your base LAMMPS version is not up-to-date, so you may be encountering a bug that may have already been fixed.
