### ISSUE TITLE
3rd law violation with fix restrain dihedral when running on multiple processors

### ISSUE THREAD

**Issue by cmanion** [lammps/lammps#463]
When fix restrain dihedral is run on multiple processors and when the dihedral crosses processor boundaries, the dihedral seems to be applying random forces violating newton's 3rd law. 

Running the following with a single processor works fine and by the end of the simulation the molecule has moved negligibly from its original position. Running on two more processors results in the molecule starting to translate and spin out of control at about timestep 240,000.
[azobenzene.txt](https://github.com/lammps/lammps/files/959908/azobenzene.txt)
[fixRestrainTest.txt](https://github.com/lammps/lammps/files/960042/fixRestrainTest.txt)
This does not occur if a dihedral with the same potential as the fix restrain dihedral is used.
[dihedralTest.txt](https://github.com/lammps/lammps/files/960043/dihedralTest.txt)

**Comment by akohlmey** [comment]
I don't think that there is much that can be done to avoid this artifact. This is what is usually referred to, as the flying icecube syndrome. The problem is, that fix restrain has to do an additional minimum image convention  check and correction on the three constituent bond lengths of the dihedral, which can incur additional numerical noise to the force computation. 

The way to counteract this effect is to apply fix momentum to the system, e.g. like this:
```
fix azo1 all restrain dihedral 4 7 8 9 20.0 20.0 360
fix_modify azo1 energy yes
fix squash all  momentum 100 linear 1 1 1 angular rescale
```
