### ISSUE TITLE
Extending current pair_styles to be adaptive to local temperatures

### ISSUE THREAD

**Issue by LishengCheng** [lammps/lammps#469]
I am working on the fusion and integration of polymer melts, where thermal diffusion closely couples with molecular dynamics. Coarse-grain (CG) molecular dynamics simulations are useful to get insights into such processes. However, CG parameters of pairwise potential are sometime (or maybe usually) dependent on temperature. In order to deal with this problem, I would like to make modifications to the pair_styles in Lammps to make them adaptive to the local temperature in the simulation box.

**Comment by andeplane** [comment]
I'm just curious, will this not change the rules of statistical physics? The common results assuming that `P = 1/Z exp(-E/kT)`, E being independent of T, no longer holds. What happens with thermodynamics in this case?

**Comment by LishengCheng** [comment]
It is truth that the nonbonded potentials have been assumed to be independent of temperature in a lot of coarse-graining scheme. However, this actually is inadequate since the free energy contains not only enthalpy, but also the part of entropy, which is dependent of temperature. That is why such kinds of coarse-grained parameters are effective only in a not so wide range of temperature to avoid  deviations from what it should be. The modification of pair_styles is expected to give the chance to run MD simulations for a much wide range of situations, including thermal expasion and other complex thermal processes.

**Comment by akohlmey** [comment]
@LishengCheng Please have a look at pair style dpd, which incorporates local "temperature" through including particle velocities. The only adjustment required in the case of this pair style, is that updated velocity information has to be communicated to ghost atoms, which is done through the `comm_modify` command.

Please also keep in mind, that "local temperature" is not really a sound statistical mechanical concept. However, kinetic energy is, and you cannot get more local than looking at the energy of individual atoms.

**Comment by LishengCheng** [comment]
@akohlmey Thank you for your advice. I would like to calculate the "local temperature" from the velocities of a group of atoms in local regions, rather than individul ones.

**Comment by akohlmey** [comment]
@LishengCheng your request and descriptions are too vague for any action. Please note that you have access not just to individual pairs but through the neighbor list to the entire environment up to the interaction cutoff. just do two loops over the neighbors of each atom: the first to collect the kinetic energy in the environment of each atom and then use that information in the second loop. you probably want to have some tapering for that. The EAM pair potentials collect a local "density" to which neighboring atoms contribute, communicate it and then do a second loop to compute the forces.

at any rate, there is no reason to continue this discussion here. the issue is closed. if you want to discuss more, you may try the lammps-users mailing list, but i would have little hope that you'll get more info than what you already have. you can open a new issue, if you have a specific proposal or some demo code for how to implement what you are looking for and can make a convincing case then you can open a new issue.
