### ISSUE TITLE
Elastic script

### ISSUE THREAD

**Issue by GitHub-ccd** [lammps/lammps#48]
Would it be possible to change the Elastic script (dispalcement.mod) to include the compliance tensor and calculate the polycrystalline averages of Bulk, Young's and Shear modulus? If the compliance tensor can be calculated we can easily calculate the K, E and G Voigh, Ruess and Hill averages.

**Comment by akohlmey** [comment]
Open source software like LAMMPS lives from the contributions of its users. Many features in LAMMPS exist because somebody was interested in them and figured out how to implement them. The LAMMPS developers welcome such contributions and will include be glad to include them, if they are reasonably well done and documented.

**Comment by akohlmey** [comment]
Please contact Aidan Thompson, the author of the script in question, at athomps@sandia.gov and mention this github issue #48.
I have forwarded your suggestion to him and he has looked into it and has some suggestion for how to handle this, but he needs somebody to help him do proper validation and careful testing.

**Comment by akohlmey** [comment]
Script to post-process LAMMPS logfile from ELASTIC runs was added to the repo in commit 20f13bf13ddf2fdd46d8f0d6d6623192ac29d98b

**Comment by GitHub-ccd** [comment]
Dear Dr. Tompson,
I'd be more than happy to help you with calculations and validation.
Sincerely,
Chamila

Chamila Chathuranga Dharmawardhana, PhD
Department of Chemical and Biological Engineering
University of Colorado Boulder
3415 Colorado Avenue Boulder,
CO 80309-0596
