### ISSUE TITLE
Wrong exponent in compute_hexorder_atom

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#503]
I'm working on a 2d material and was going to use compute hexorder/atom to measure the order parameter. I'm adding a feature where you can use voronoi neighbors instead of the nearest `nnn` neighbors. When I looked through the code, it the exponent `ndegree` is not used and `nnn` is wrongly used in [line 251](https://github.com/lammps/lammps/blob/master/src/compute_hexorder_atom.cpp#L251) and [lines 262-264](https://github.com/lammps/lammps/blob/master/src/compute_hexorder_atom.cpp#L262).

**Comment by akohlmey** [comment]
Please note, that there is no need to file an issue and submit a pull request for the same issue. A pull request is essentially an issue with a branch attached. It'll be easier for people to manage and review, if the explanation for what a pull request is correcting, if it was directly included, rather than referring to an issue.

**Comment by andeplane** [comment]
Yeah I'll close this one and update the PR and do that in the future!
