### ISSUE TITLE
LJ cutoff in AIREBO

### ISSUE THREAD

**Issue by CF17** [lammps/lammps#514]
Looking at the airebo code, I think that the cutoff used in the input file is not really used to compute the vdw interaction. I am wondering if the line of code in the FLJ subroutine `sigcut = 3.0;` should not be replaced by `sigcut = cutlj;`.

**Comment by v0i0** [comment]
You're likely correct.
Has this actually been an issue for you, or is it just something you noticed in the code?
I.e. does this change fix anything for you?

How/Would you adjust `sigwid` if a user decides on a different cutoff multiplier than 3?
My main concern is that the transition region induced by the `slw` term should probably not extend into the LJ "well/wall region" itself.

Currently any cutoff multiplier larger than 3 is useless, and anything lower results in a real, hard cutoff, because the potential is only actually zero after 3 sigma.
Note that the `slw` term does not appear in the original AIREBO paper, so it's hard to tell what's correct.

Certainly the documentation should be updated to reflect the effect `cutlj` has, and caution users from using values other than 3.

**Comment by CF17** [comment]
@v0i0 this actually was an issue for me because I wanted to increase the cutoff for LJ interaction.  I modified the code and I introduced the following lines:
` sigwid = 0.84/3.0*cutlj;`
`sigcut = cultlj;`

With this code, when `cutlj=3.0` then `sigwid=0.84` as in the original code and if I introduce a different value for `cutlj` then `sigwid` is scaled appropriately. 

The best would be that both the start and end points of the cutoff function were read from the input file as in the pair_style lj/charmm/coul/charmm. Default value for airebo being 2.16 and 3.0.

**Comment by v0i0** [comment]
My suggestion would be to add a fourth, optional parameter to the AIREBO pair style.
I.e. your use-case would be covered by `pair_style airebo 3.0 1 1 2.16`.
If it is not given, we retain the old behaviour.
If it is given, we set `sigcut = cutlj` and `sigmin = <that fourth param>`.
This should not take a whole lot of time to implement, and keep the behaviour of the code stable.
Of course, the documentation should be updated to reflect all the behaviours that exist in there.
Would that work for you?
