### ISSUE TITLE
[Feature Request] Minimize with KOKKOS

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#518]
I'm curious, why isn't energy minimization supported with KOKKOS? I have multiple times had this issue where I need to run non-KOKKOS version to do minimization. Is there something I can look into maybe?

**Comment by akohlmey** [comment]
Regular minimization requires a specialized "driver" class, similar to `VerletKokkos` to manage access to the system data. However, there is significantly more porting work required for minimization, since it appears you'd need to port the classes `Min`, `MinLinesearch` and `MinCG` or `MinSD` all to have KOKKOS compatible data access. Some minimization styles, e.g. `MinQuickMin` may be easier to port (as they implement some variant of damped dynamics). In fact, you might even consider implementing it as a fix to be run using the KOKKOS-enabled Verlet driver and using the `Timer::force_timeout()` feature to terminate the run, once minimization criteria are met. Even easier would be to implement simulated annealing by porting `fix viscous` to KOKKOS.

**Comment by stanmoore1** [comment]
Right, the biggest issue is the CUDA version. It needs all of the data movement between host and device to work properly.

**Comment by stanmoore1** [comment]
I started working on this.
