### ISSUE TITLE
Colvars library compile issue

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#587]
Colvars library doesn't seem to be compiling correctly using the lastest version of master. For example, when starting from a new checkout, 

<pre>
$ make -j8 -f Makefile.g++
Makefile.common:4: ../../src/Makefile.package.settings: No such file or directory
make: *** No rule to make target `../../src/Makefile.package.settings'.  Stop.
</pre>

If I install and build with Kokkos, and then clean and try to build the colvars lib, it doesn't build anything, even though I just cleaned:

<pre>
$ make -j8 -f Makefile.g++ clean
rm -f colvaratoms.o colvarbias_abf.o colvarbias_alb.o colvarbias.o colvarbias_histogram.o colvarbias_meta.o colvarbias_restraint.o colvarcomp_angles.o colvarcomp_coordnums.o colvarcomp.o colvarcomp_distances.o colvarcomp_protein.o colvarcomp_rotations.o colvar.o colvardeps.o colvargrid.o colvarmodule.o colvarparse.o colvarproxy.o colvarscript.o colvartypes.o colvarvalue.o libcolvars.a
$ make -j8 -f Makefile.g++
make: Nothing to be done for `KokkosCore_config.h'.
</pre>

**Comment by giacomofiorin** [comment]
I presume that you were compiling the library before issuing `make yes-user-colvars` or equivalent `make yes-*` command?  Good to know, thanks for reporting it very quickly.

Axel's commit 66154e8a8b31fcfa1ce512908a249d4175257a28 temporarily works around the error condition, and I added clearer instructions in the README.

That `include` is used to detect the package settings for LAMMPS, so that future additions to Colvars can be compiled conditionally (e.g. Python support).  While the issue is moot right now, I specifically wanted to get a clear idea of the possible error conditions.

Unfortunately, there does not seem to be a robust way to share information with the packages about LAMMPS compilation flags and package settings.

In my opinion, the only build order that should be allowed is:
1. Enable all needed packages with `make yes-package`
2. Build all enabled packages and LAMMPS core.
Steps 1 and 2 should not mix.

For what is worth, this particular problem is absent in the CMake build system implemented by @junghans  and @rbberger, where most packages inherit compile flags used by the core LAMMPS files, and unless I'm mistaken, also package settings as well.

**Comment by giacomofiorin** [comment]
I also have to confess to being naive in my tests, since I didn't enable Kokkos, which has a ton of definitions and dependencies imported in `Makefile.package.settings` (second part of your issue).

To avoid similar issues with other packages, I disabled the inclusion of `Makefile.package.settings` by Colvars in #589.  The script `Install.py` still detects compiler flags from the machine Makefiles.

**Comment by stanmoore1** [comment]
@giacomofiorin thanks. Yes, in our regression test scripts, the libraries are built first and then LAMMPS is built.
