### ISSUE TITLE
Compilation fails when using Intel compiler and USER-OMP package

### ISSUE THREAD

**Issue by wesbarnett** [lammps/lammps#637]
## Summary

Compilation of LAMMPS fails when using Intel compiler and USER-OMP package

## Type of Issue

Bug Report

## LAMMPS Version

Both the stable 11Aug2017 and master branches.

## Expected Behavior

Successful compilation.

## Actual Behavior

Several compiler errors occur (output linked below) and build fails.

## Steps to Reproduce

Although the bug is also in the MPI build, the simplest way to reproduce is to do a serial build. Clone the lammps repository. Change `g++` to `icpc` in `src/MAKE/Makefile.serial`. Change dir to `src`. Use `make-user-omp`. Then do `make serial`.

## Further Information, Files, and Links

Intel build succeeds when not using USER-OMP package. GNU compiler (g++) succeeds at compilation with or without package. [Here is the output](https://gist.githubusercontent.com/wesbarnett/aec944bf09bcfbdd2df21509dc3b81ca/raw/061cef05ae03bcb5532d77d47180309cd598a795/gistfile1.txt) of the failure.

**Comment by akohlmey** [comment]
This is not a bug, but documented behavior. When using the Intel compiler, you **must** use the `-restrict` flag, or you get the compile error you are seeing. There was initially a different mechanism in place that would signal that pointers do no alias, that compiled the code without error messages, but based on information from an expert at Intel, this was changed, because the "non error" version had no effect on Intel compilers.
