### ISSUE TITLE
A missing semicolon in fix_wall_lj93_kokkos.cpp

### ISSUE THREAD

**Issue by mkanski** [lammps/lammps#656]
Hi,

A compilation of LAMMPS **(version 1 SEP 2017)** with KOKKOS fails at file fix_wall_lj93_kokkos.cpp. There should be a semicolon in line 34. After adding it the compilation finishes without error.

Michal

**Comment by akohlmey** [comment]
This applies only to the git "master" branch, **not** patch 1 Sep 2017, i.e. the "unstable" branch.
Also, the issue has already been noticed in our regression tests and the correction is already available in PR #655 which is just not yet merged, though. Unless you are participating in development, it is probably preferable to follow the "unstable" branch instead of "master".
