### ISSUE TITLE
Gromacs installation

### ISSUE THREAD

**Issue by NABIAHAMAD** [lammps/lammps#756]
Hi,
I am installing gromacs-5.1.4 software on a cluster locally, I do not have root privilege. I stuck on the last step **make install** .  Can I install this software locally or not ? 

Thank you

**Comment by Pakketeretet2** [comment]
Why are you asking Gromacs questions on the LAMMPS Github page?

On Dec 29, 2017 7:24 AM, "nabi ahamad" <notifications@github.com> wrote:

Hi,
I am installing gromacs-5.1.4 software on a cluster locally, I do not have
root privilege. I stuck on the last step *make install* . Can I install
this software locally or not ?

Thank you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lammps/lammps/issues/756>, or mute the thread
