### ISSUE TITLE
LAMMPS GIT repository history contains some big digital files

### ISSUE THREAD

**Issue by numericalfreedom** [lammps/lammps#767]
## Summary

_GIT repository contains some big digital files_

## Type of Issue

_Just a comment_

## Detailed Description (Enhancement Suggestion)
_
In the GIT history, a command "git commit -a ..." has been issued and the repo history contains the huge digital file atc/lib/libatc.a

Basically, this doesn't cause any harm just blows up the GIT repo history size.
_

## LAMMPS Version (Bug Report)

_ The LAMMPS GIT repository history _

## Expected Behavior (Bug Report)

_ Does not affect computation results _

## Actual Behavior (Bug Report)

_Does not affect computation results _

## Steps to Reproduce (Bug Report)

_ It is recommended to pull the GIT LAMMPS repo with the --depth option in order to eliminate the huge digital file from history locally. _

## Further Information, Files, and Links

_ The removal of parts in the GIT repo history is quite difficult and tedious. Maybe, some day a fresh LAMMPS repository can be started. Commits with the -a option should be avoided. _

**Comment by akohlmey** [comment]
This is known issue and stems from the time when LAMMPS was developed in a subversion repository and some people had set up an automated commit to that repository. This cannot happen anymore, because *all* contributions must be submitted via a pull request and are reviewed by at least one core developer. There have been some thorough thinking about fixing the repository, but the way git works, it cannot be done without rewriting the entire history up to that point of the faulty commits. That however, would create a massive fission of developer branches and thus massive headaches for all external developers (and especially those with limited knowledge of git, i.e. the bulk of them). Thus we have decided that having those few files in there is the lesser issue. Since all data transfers in git are incremental, this is a one-time effect anyway.

**Comment by junghans** [comment]
@numericalfreedom just use `git clone --shallow-since=<date>` and only clone the last year or so.

**Comment by numericalfreedom** [comment]
Thank You very much gentlemen, I spent sometime playing around with the the entire git history and exactly found out, what You have explained me in detail.
