### ISSUE TITLE
thermo_style "atoms" keyword not giving proper number of atoms (with fixed boundary)

### ISSUE THREAD

**Issue by erozic** [lammps/lammps#825]
## Summary

When boundary is of type _fixed_ the ```atoms``` thermo keyword is not updated to the correct number of atoms each step, but only on steps when ```thermo``` gives the output. This is unlike the behavior of the ```density``` keyword, or other thermo keywords, and prevents this keyword being used in other variables and calculations, for example the time average of the number of atoms.

## Type of Issue

Bug Report

## LAMMPS Version

11-Aug-2017

## Expected Behavior (Bug Report)

The expected behavior, in my opinion, would be for the ```atoms``` thermo keyword to give the exact, correct number of atoms on each step of the simulation, just like the ```density``` and other thermo keywords do.

## Actual Behavior (Bug Report)

The actual behavior is that the ```atoms``` thermo keyword gives the correct number of atoms only on steps when ```thermo``` is printing the output, and in the steps in between it doesn't take into account the number of atoms that have exited the simulation box.
I have checked this by using _periodic_ and _fixed_ boundaries in conjunction with a ```gcmc``` fix that adds/removes atoms. When the boundary is defined as _periodic_ then everything is OK, but when the boundary is defined as _fixed_ then the number of atoms reported by the ```atoms``` keyword is changing in line with the removal/addition of atoms by the ```gcmc``` fix, but doesn't decrease with atoms exiting the simulation box. That this is the case can be checked by excluding the ```gcmc``` fix and keeping the dynamics, in which case the atoms just fly out of the simulation box, and also by counting the number of atoms by using ```count(all)``` in a variable, which gives the correct number.
However, the two numbers become the same, i.e. the ```atoms``` keyword is reset to the correct value, just before the ```thermo``` command gives its output (I guess that is recalculates the number of atoms before it outputs it).

## Steps to Reproduce (Bug Report)

The bug can be reproduced as explained above. I have attached an input file ([atoms_bug.in.txt](https://github.com/lammps/lammps/files/1780847/atoms_bug.in.txt)) and two output files generated by it, one for a _fixed_ boundary ([n_rho_fixed.dat.txt](https://github.com/lammps/lammps/files/1780848/n_rho_fixed.dat.txt)) and one for a _periodic_ boundary ([n_rho_periodic.dat.txt](https://github.com/lammps/lammps/files/1780849/n_rho_periodic.dat.txt)), that demonstrate the bug.
The output files have the number of atoms for each step "calculated" in three different ways, by using the ```atoms``` keyword, by using ```count(all)``` and by using the ```density``` and ```vol``` keywords. It can be seen that when the boundary is _fixed_ the first column differs from the other two, and in such a way that it doesn't count the atoms that flew out of the simulation box. This is evidenced by the fact that with a _periodic_ boundary all three columns are the same, and can also be cross-checked by running the input script with the ```gcmc``` fix commented-out.

**Comment by sjplimp** [comment]
The problem is that updating the global count of atoms with fixed boundaries requires
doing an MPI_Allreduce every timestep.  Which is not something we're willing to do.  Slows
down the code in many scenarios.  So it should ideally only be updated if the code uses it,
which is why it is updated when thermo is output.   So can you explain this line better:

when the boundary is defined as fixed then the number of atoms reported by the atoms keyword is changing in line with the removal/addition of atoms by the gcmc fix, but doesn't decrease with atoms exiting the simulation box. 

Is this referring to thermo output or something else in between thermo outputs?

Steve

**Comment by erozic** [comment]
@sjplimp Aaaah, I see. Well, that makes sense, I guess. But then I wonder how is the ```density``` _thermo_ keyword able to produce the correct density on each timestep, and not only on those timesteps that _thermo_ outputs, since it needs the data about all atoms to do that?

In any case, if the ```atoms``` keyword doesn't give the correct number of atoms on all timesteps, but just the ones _thermo_ outputs on, then I think it should at least say so in the documentation, since that behavior is different from other _thermo_ keywords and quite unexpected (at least was to me, because I had the impression one could use thermo keywords anywhere and on all timesteps).

The line you quoted is referring to using the keyword on timesteps between _thermo_ outputs. So the ```atoms``` keyword gives a correct exact number of atoms ONLY on _thermo_ output, and is not to be used elsewhere in the script (if boundaries are _fixed_).

**Comment by sjplimp** [comment]
@erozic  yes. I agree with your assessment that the "atoms" keyword is inconsistent.  What
we'll do is force an Allreduce for the atom count triggered by use of that keyword, on
timesteps other than the thermo output.  E.g. in between thermo output for fix ave/time
like you are doing in your script.  The lost check (possible error or waning) will still only
happen at thermo timesteps.

**Comment by akohlmey** [comment]
@sjplimp here is another reminder that you had promised to address this issue in May 2018. Adding it to the milestone for the next stable release.

**Comment by sjplimp** [comment]
Posting a PR for this today.  @erozic you should check if this fixes your test case.  I only
put the recalc of total atom count in the thermo variable "atoms".  So it should work if
that is used, e.g., in a variable that is invoked on a timestep inbetween thermo outputs.
But there maybe other places I'm not thinking of where atom->natoms is accessed
directly, in which case that value is still not updated until thermo output steps.  The issue is
that we want to preserve the check on lost atoms which happens each thermo output;
that uses the stored atom->natoms value to compare to compare to the current natoms.

**Comment by erozic** [comment]
@sjplimp I understand, I think this should be good enough. In any case, I've checked and it resolves my test case perfectly, the number of atoms is the same in all three ways of calculating it (including the natoms keyword) on every timestep, not just the ones thermo output on.
