### ISSUE TITLE
Wrong sign in ReaxFF taper function?

### ISSUE THREAD

**Issue by alexispaz** [lammps/lammps#828]
[taper7.txt](https://github.com/lammps/lammps/files/1786082/taper7.txt)
## Summary

I believe I have found a bug in the taper function of ReaxFF potential. I found this in the two versions: reax (fortran) and reax/c (cpp). 

## Type of Issue

This is a Bug Report

## Detailed Description (Enhancement Suggestion)

In file `lib/reaxff/reax_charges.F`, subroutine `tap7th`, the coeficient `SWC0` is computed using the following line:

```
SWC0=(-35.0D0*SWA3*SWB2*SWB2+21.0D0*SWA2*SWB3*SWB2+
     $7.0D0*SWA*SWB3*SWB3+SWB3*SWB3*SWB)/D7
```

I have made the math using Maxima (see atached script) and I hav found that the correct line should be

```
SWC0=(-35.0D0*SWA3*SWB2*SWB2+21.0D0*SWA2*SWB3*SWB2-
     $7.0D0*SWA*SWB3*SWB3+SWB3*SWB3*SWB)/D7
```

Note the change of + to - before the `7.0D0` literal. 

The same bug is found in `src/pair_reax.cpp` (`taper_setup` procedure) and `USER-REAXC/fix_qeq_reax.cpp` (`init_taper` procedure). I have not checked further replicas, since I do not know the lammps code to properly do that.

## LAMMPS Version (Bug Report)

`0b3f1b8a1`, tag: `stable_11Aug2017`
Also tested in `5e9d257ec`

## Expected Behavior (Bug Report)

Taper function should go from 1 to 0.

## Actual Behavior (Bug Report)

Since the `SWC0` parameter is incorrect, the taper function will introduce an arbitrary factor in the energy values. I believe this factor will affect only in Van der Waals and Coulomb terms, but I am not an expert of the ReaxFF code. This bug should not have an effect on the dynamics.

## Steps to Reproduce (Bug Report)

I guess this can be detected when comparing energy values. I found it by just checking the math and compare it with the source code.

## Further Information, Files, and Links

I am attaching the Maxima script that I made to solve the taper coefficients.

**Comment by alexispaz** [comment]
We just realize that if the Lower tapper radius is zero, i.e. this line in the force field file:

`0.0000 !Lower Taper-radius `

`SWC0` calculation will not be affected by the bug, that is, the wrong sign in the term does not matters because that term will be zero in this case.

**Comment by athomps** [comment]
Yes, this is an error in the code, dating back to the original serial FORTRAN ReaxFF code. Well spotted. It survived undetected because SWA is set to zero in every parameterization of ReaxFF that I was able to check. For positive values of SWA, the switching function is shifted upward by a large positive amount. This would introduce drastic shifts in both the energy and force contributions from non-bonded and Coulombic interactions.  The following files are affected and should be changed (replace final + with -):

[athomps@s974522 src]$ grep -A1 '(-35.0' */*
KOKKOS/pair_reaxc_kokkos.cpp:  k_tap.h_view(0) = (-35.0*swa3*swb2*swb2 + 21.0*swa2*swb3*swb2 +
KOKKOS/pair_reaxc_kokkos.cpp-                     7.0*swa*swb3*swb3 + swb3*swb3*swb ) / d7;
QEQ/fix_qeq_shielded.cpp:  Tap[0] = (-35.0*swa3*swb2*swb2 + 21.0*swa2*swb3*swb2 +
QEQ/fix_qeq_shielded.cpp-            7.0*swa*swb3*swb3 + swb3*swb3*swb ) / d7;
REAX/pair_reax.cpp:  swc0=(-35.0e0*swa3*swb2*swb2+21.0e0*swa2*swb3*swb2+
REAX/pair_reax.cpp-        7.0e0*swa*swb3*swb3+swb3*swb3*swb)/d7;
USER-REAXC/fix_qeq_reax.cpp:  Tap[0] = (-35.0*swa3*swb2*swb2 + 21.0*swa2*swb3*swb2 +
USER-REAXC/fix_qeq_reax.cpp-            7.0*swa*swb3*swb3 + swb3*swb3*swb) / d7;
USER-REAXC/reaxc_init_md.cpp:  workspace->Tap[0] = (-35.0*swa3*swb2*swb2 + 21.0*swa2*swb3*swb2 +
USER-REAXC/reaxc_init_md.cpp-                     7.0*swa*swb3*swb3 + swb3*swb3*swb ) / d7;

[athomps@s974522 src]$ grep -A1 '(-35.0' ../lib/reax/*
../lib/reax/reax_charges.F:      SWC0=(-35.0D0*SWA3*SWB2*SWB2+21.0D0*SWA2*SWB3*SWB2+
../lib/reax/reax_charges.F-     $7.0D0*SWA*SWB3*SWB3+SWB3*SWB3*SWB)/D7

**Comment by alexispaz** [comment]
Thank you for the confirmation. Another related thing... I believe there should be a conditional to set the smoothing factor to be always 1 below `SWA`. This is only needed if `SWA` is grater than zero, which have never happened yet, but it could be healthy to do it. I guess this is not needed for `SWB` because of the neighbor list.

**Comment by athomps** [comment]
bugfix in #830 are correct and will have no effect on energy or force for current ReaxFF parameterizations.

**Comment by athomps** [comment]
I agree that current code does not enforce Tap=1 for r<swa, therefore is wrong. Again, does not matter for swa=0.
