### ISSUE TITLE
LAMMPS crashes silently when using PyLammps

### ISSUE THREAD

**Issue by erozic** [lammps/lammps#844]
## Summary

When using ```PyLammps```, LAMMPS and the python script crash without any ERROR message when one uses the object-oriented access assignment, e.g.
```lmp.ukits("lj")``` ("ukits" instead of "units", on purpose, to have an error)
as opposed to the explicit ```command``` invocation, e.g.
```lmp.command("ukits lj")```

## Type of Issue

Bug Report

## Version

LAMMPS (11 Aug 2017)

## Expected Behavior (Bug Report)

LAMMPS should always crash with some indication that an ERROR happened, not just die silently. Also, it should be consistent in what it does, regardless of what approach one uses.

**Comment by rbberger** [comment]
That's what `-DLAMMPS_EXCEPTIONS` is for. The default error behavior is to kill the process. This way an exception is raised instead.

**Comment by erozic** [comment]
@rbberger Hi and thanks for the answer. However, I'm not sure you understood me completely. So, without the flag for exceptions, if you write e.g. ```PyLammps.ukits("lj")``` in your python script, it will just terminate without any output at all, any indication at all as to what happened, as if it finished normally. This is very bad behaviour for the user, and it stems from the way the PyLammps wrapper is coded in python, not LAMMPS itself.
This is obviously so because LAMMPS prints out an "ERROR" statement before crashing (without throwing an exception, if this flag is not set), and you can see that ERROR statement on stdout if you run LAMMPS directly or if you run it from your python script using explicit commands, e.g. ```PyLammps.command("ukits lj")```.

So basicaly what I'm saying is that ```PyLammps.command("ukits lj")``` and ```PyLammps.ukits("lj")``` should give the same output, and they don't, and that's because of how PyLammps if coded.

**Comment by rbberger** [comment]
@erozic We created the exceptions flag for this very reason and to enable a more Pythonic way of handling errors.

LAMMPS writes the error message only to stdout (aka "screen") and the log file. PyLammps captures stdout to operate. Without the exceptions flag the Python interpreter has no chance to flush the buffer it uses internally. The process just **dies**. `PyLammps.command("ukits lj")` doesn't use the buffering, that's why you see the error message. So in short: if you want to use `PyLammps.ukits("lj")` and get a decent error message use the exceptions flag. 

Btw, suppressing the output is by design. If you want it you need to add `verbose=True`. However, because of the buffering and the process being killed, that won't work in the error case.

**Comment by erozic** [comment]
@rbberger Thanks again for the answer. I understand your point, but I still think that two very different behaviours from commands that are expected to be equivalent is confusing/bad (as evidenced at least by this little conversation of ours).
My minimal suggestion to you as a "fix" is that at least the expectation of equivalence is then changed, meaning that the documentation should make it clear that the two ways are not equivalent and that it isn't true that:
"Compiling the shared library with C++ exception support provides a better error handling experience. Without exceptions the LAMMPS code will terminate the current Python process with an error message."
which is what the PyLammps tutorial in the documentation now says.
Also, you know better and are aware of reasons why this is maybe a bad idea, but I don't see why the shared library wouldn't support exceptions as a default, and that this functionality can then be turned off, instead of how it is now...
Cheers!
