### ISSUE TITLE
NaN in potential energy and pressure tensor when using reaxff/c with the checkqeq no lgvdw yes options

### ISSUE THREAD

**Issue by evoyiatzis** [lammps/lammps#876]
## Summary

I am trying to simulate Si crystal using the reax/c command with checkqeq no lgvdw yes options. The force field parameters are the ones contained in the 'standard' ffield.reax.lg file. The computed potential energy for the initial step is NaN (in particular the v_ew element) and the pressure tensor gets a NaN value. 

Note: Using the same in and data files but with (i) the force field provided in the supporting information of https://pubs.acs.org/doi/abs/10.1021/jp3086649 and (ii) with the command pair_style      reax/c NULL checkqeq no lgvdw no , the simulation proceeds without any issue.

[jp3086649_si_002.txt](https://github.com/lammps/lammps/files/1931335/jp3086649_si_002.txt)

## Type of Issue

'Bug Report' 

## LAMMPS Version (Bug Report)

LAMMPS stable version 30 March 2018 

## Expected Behavior (Bug Report)

The expected behavior is a finite value for the potential energy and the pressure tensor

## Steps to Reproduce (Bug Report)

I attach a zip file with the in and data files to reproduce the same behavior.
[bug_report.zip](https://github.com/lammps/lammps/files/1931299/bug_report.zip)

**Comment by mkanski** [comment]
It's because the ffield.reax.lg is inconsistent - interactions in C/H/O/N/S systems use additional core repulsion (last three parameters in the fourth line in the elements section of the force field file), while Si does not. 
Change the sixth and eighth parameter in the fourth line of Si element parameters to 1.0 and everything should work. This modification does not introduce changes in potential energy since the seventh parameter - interaction energy - remains zero.

**Comment by evoyiatzis** [comment]
Thanks for the response. It seems to work (at least no NaN in short runs). Can you push the changes in the ffield.reax.lg file?

**Comment by mkanski** [comment]
I can't push the changes and I don't think it is a good idea anyway, since it will only solve NaNs for this particular parametrization and there should be a more permanent solution. 

Another issue is how legit are the parameters for Si. Silicon is not mentioned in the ReaxFF-lg paper (DOI: 10.1021/jp201599t). In the paper (DOI: 10.1063/1.1831277), which is a base for ReaxFF-lg it is only stated the the new potential is compatible with the older one for Si/SiO. However, the parameters for this Si/SiO ReaxFF (DOI: 10.1021/jp0276303) are slightly different than the ones in the ffield.reax.lg.

**Comment by athomps** [comment]
i agree.

--
      Aidan P. Thompson
      01444 Multiscale Science
      Sandia National Laboratories
      PO Box 5800, MS 1322      Phone: 505-844-9702
      Albuquerque, NM 87185     Fax  : 505-845-7442
      E-mail:athomps@sandia.gov Cell : 505-218-1011

**Comment by akohlmey** [comment]
PR #957 contains the edits to force field file and also adds more thorough checks on the compatibility of the force field file and error out when the file is not compatible with the lgvdw setting.
