### ISSUE TITLE
Uninitialized memory issue in rcb.cpp

### ISSUE THREAD

**Issue by Azrael3000** [lammps/lammps#888]
Hi,

as mentioned in a previous issue, I'm currently porting rcb to LIGGGHTS and I have stumbled across another bug in LAMMPS. It's a bit of a corner case as it involves only one atom, but it should be handled correctly regardless.

In src/rcb.cpp:460 there is an `if (smaller > largest)` now if we have one particle you will see that lo[*] = hi[*] and because of this smaller == largest == 0 for all values of `dim`. This causes this particular part of the code to never be run. In particular the `memcpy` inside this if is never executed. This causes an unitialized memory access in line 472. Additionally, `dim` is initialized with `-1` and thus the accesses in 484 and 485 are problematic. Additionally, `valuehalf_select` is never initialized either.

I propose two changes to fix this issue:

 1. Initialize `largest` with `-1` to ensure that the `if` is true at least once.
 2. The real change though is that I propose to modify the shrinking routine performed at the beginning of balance such that it has at least some extent. The code, inserted after `src/balance.cpp:643` is as follows:

```
    // ensure that that the box has at least some extent.
    const double nproc_rt = domain->dimension == 3 ?
                            cbrt(static_cast<double>(comm->nprocs)) :
                            sqrt(static_cast<double>(comm->nprocs));
    const double min_extent = ceil(nproc_rt)*neighbor->skin;
    for (int i = 0; i < domain->dimension; i++)
    {
      if (shrinkall[3+i]-shrinkall[i] < min_extent)
      {
        const double mid = 0.5*(shrinkall[3+i]+shrinkall[i]);
        shrinkall[3+i] = std::min(mid + min_extent*0.5, boxhi[i]);
        shrinkall[i]   = std::max(mid - min_extent*0.5, boxlo[i]);
      }
    }
```

These two changes solve all issues for me and my tests do not indicate any adverse behaviour. If I miss something with these modifications please let me know.

Kind regards,
Arno
DCS Computing GmbH

**Comment by akohlmey** [comment]
@Azrael3000 something doesn't add up here. Line 643 is in an unused function that is only kept around for historic reasons.  `shrinkall`, `boxhi` (not `bboxhi`?) `boxlo` are not declared anywhere in rcp.cpp.
Would you mind submitting this rather as a pull request?
Thanks.

**Comment by Azrael3000** [comment]
@akohlmey you probably looked at line 643 in `rcb.cpp` but instead you should be looking at `balance.cpp` as noted in my original post. Does this clear up the confusion? Note that your commit 08475e5 does this wrong. The second part of the diff should go to `balance.cpp`

**Comment by akohlmey** [comment]
@sjplimp have you looked at #928 since?

**Comment by sjplimp** [comment]
@Azrael3000 Hi Arno - two parts to your suggested code changed.  First is changing largest = -1.0
to avoid an issue if there is a single particle with a size = 0.0 box around it, to insure some
cut is selected.  I agree with that one.  For the 2nd one, I'm not as clear.  I think a size=0.0
sub-box could occur at some level of recursion within RCB even if the initial box is finite size.
E.g. when you start with particles on a perfect lattice and Natoms < Procs.  Then the new
sub-box could be of 0.0 size in one or more dims in order to break ties when lots of particles have the same coord (at the lattice spacing).  So just setting the box to some arbitrary finite size
at the beginning (sqrt or cube-root of procs * neighbor skin), seems somewhat adhoc.  And I don't know that it prevents a sub-box -> 0.0 size in all cases.  So the real Q is what problem is it causing for a sub-box size to be 0.0?  If the first bug (largest = -1.0) is fixed, can you explain a remaining
problem that occurs?  Is the test script simply to run RCB on P procs for a single particle?
I'm thinking RCB and the subsequent tiled comm should work even if sub-box sizes are 0.0.
If we need to prevent any sub-box from not being 0.0 size in any dimension, then
we likely need to enforce that inside the RCB recursion.
