### ISSUE TITLE
Use of `sed -i` is not portable

### ISSUE THREAD

**Issue by ellio167** [lammps/lammps#965]
## Summary

Use of `sed -i -e ...` in Install.sh and Make.sh files in not portable

## Type of Issue

Suggestion for an Enhancement

## Detailed Description (Enhancement Suggestion)

The `-i` option of sed is not portable.  On gnu the option is `-i[extension]` on Darwin it is `-i extension`. So, on osX the command `sed -i -e "...." filename.abc` creates a backup file named `filename.abc-e` (in addition to making the desired change to `filename.abc`)

The solution suggested here (https://unix.stackexchange.com/questions/92895/how-can-i-achieve-portability-with-sed-i-in-place-editing) is:

`sed -e "...." filename > filename.new`
`mv -- filename.new filename`

**Comment by akohlmey** [comment]
@ellio167 this is surprising, since those flags have been in those files for a long time, and there are quite a few people using MacOS X. So i would have expected this to show up. in fact, i recall, that we had some changes made to accommodate the idiosyncrasies in the BSD version of sed vs. those of GNU sed. I know we had people on different BSD derived OSes test them, including MacOSX.

Can you describe a scenario where the current behavior is causing a problem (outside of leaving an unwanted file behind)?

**Comment by ellio167** [comment]
> Can you describe a scenario where the current behavior is causing a problem (outside of leaving an unwanted file behind)?

No... I don't think it is ever causing a problem.  It is just leaving the unwanted file. (so, obviously low priority...)

**Comment by akohlmey** [comment]
With the positive progress of CMake support, which doesn't require these kind of tricks, we can flag this with "won't fix" and let it rest in peace.
